// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0--rc1
// source: scv3_stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceCenterStream_Connect_FullMethodName = "/servicecenterv3.stream.ServiceCenterStream/Connect"
)

// ServiceCenterStreamClient is the client API for ServiceCenterStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServiceCenterStream 是 v3 数据面唯一服务。注册、发现、配置都走 Connect。
type ServiceCenterStreamClient interface {
	// 统一双向流（Bidirectional Streaming）
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type serviceCenterStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceCenterStreamClient(cc grpc.ClientConnInterface) ServiceCenterStreamClient {
	return &serviceCenterStreamClient{cc}
}

func (c *serviceCenterStreamClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServiceCenterStream_ServiceDesc.Streams[0], ServiceCenterStream_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceCenterStream_ConnectClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// ServiceCenterStreamServer is the server API for ServiceCenterStream service.
// All implementations must embed UnimplementedServiceCenterStreamServer
// for forward compatibility.
//
// ServiceCenterStream 是 v3 数据面唯一服务。注册、发现、配置都走 Connect。
type ServiceCenterStreamServer interface {
	// 统一双向流（Bidirectional Streaming）
	Connect(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedServiceCenterStreamServer()
}

// UnimplementedServiceCenterStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceCenterStreamServer struct{}

func (UnimplementedServiceCenterStreamServer) Connect(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedServiceCenterStreamServer) mustEmbedUnimplementedServiceCenterStreamServer() {}
func (UnimplementedServiceCenterStreamServer) testEmbeddedByValue()                             {}

// UnsafeServiceCenterStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceCenterStreamServer will
// result in compilation errors.
type UnsafeServiceCenterStreamServer interface {
	mustEmbedUnimplementedServiceCenterStreamServer()
}

func RegisterServiceCenterStreamServer(s grpc.ServiceRegistrar, srv ServiceCenterStreamServer) {
	// If the following call panics, it indicates UnimplementedServiceCenterStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceCenterStream_ServiceDesc, srv)
}

func _ServiceCenterStream_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceCenterStreamServer).Connect(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceCenterStream_ConnectServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// ServiceCenterStream_ServiceDesc is the grpc.ServiceDesc for ServiceCenterStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceCenterStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicecenterv3.stream.ServiceCenterStream",
	HandlerType: (*ServiceCenterStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ServiceCenterStream_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "scv3_stream.proto",
}
