// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: scv3_config.proto

// 文件名 scv3_config.proto，避免与旧包 config.proto 撞 protobuf 全局注册表。

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigChangeType int32

const (
	ConfigChangeType_CONFIG_CHANGE_TYPE_UNSPECIFIED ConfigChangeType = 0
	ConfigChangeType_CONFIG_CHANGE_TYPE_ADD         ConfigChangeType = 1
	ConfigChangeType_CONFIG_CHANGE_TYPE_UPDATE      ConfigChangeType = 2
	ConfigChangeType_CONFIG_CHANGE_TYPE_DELETE      ConfigChangeType = 3
)

// Enum value maps for ConfigChangeType.
var (
	ConfigChangeType_name = map[int32]string{
		0: "CONFIG_CHANGE_TYPE_UNSPECIFIED",
		1: "CONFIG_CHANGE_TYPE_ADD",
		2: "CONFIG_CHANGE_TYPE_UPDATE",
		3: "CONFIG_CHANGE_TYPE_DELETE",
	}
	ConfigChangeType_value = map[string]int32{
		"CONFIG_CHANGE_TYPE_UNSPECIFIED": 0,
		"CONFIG_CHANGE_TYPE_ADD":         1,
		"CONFIG_CHANGE_TYPE_UPDATE":      2,
		"CONFIG_CHANGE_TYPE_DELETE":      3,
	}
)

func (x ConfigChangeType) Enum() *ConfigChangeType {
	p := new(ConfigChangeType)
	*p = x
	return p
}

func (x ConfigChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_scv3_config_proto_enumTypes[0].Descriptor()
}

func (ConfigChangeType) Type() protoreflect.EnumType {
	return &file_scv3_config_proto_enumTypes[0]
}

func (x ConfigChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigChangeType.Descriptor instead.
func (ConfigChangeType) EnumDescriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{0}
}

type ConfigEventType int32

const (
	ConfigEventType_CONFIG_EVENT_UNSPECIFIED ConfigEventType = 0
	ConfigEventType_CONFIG_EVENT_PUBLISHED   ConfigEventType = 1
	ConfigEventType_CONFIG_EVENT_ROLLED_BACK ConfigEventType = 2
	ConfigEventType_CONFIG_EVENT_DELETED     ConfigEventType = 3
)

// Enum value maps for ConfigEventType.
var (
	ConfigEventType_name = map[int32]string{
		0: "CONFIG_EVENT_UNSPECIFIED",
		1: "CONFIG_EVENT_PUBLISHED",
		2: "CONFIG_EVENT_ROLLED_BACK",
		3: "CONFIG_EVENT_DELETED",
	}
	ConfigEventType_value = map[string]int32{
		"CONFIG_EVENT_UNSPECIFIED": 0,
		"CONFIG_EVENT_PUBLISHED":   1,
		"CONFIG_EVENT_ROLLED_BACK": 2,
		"CONFIG_EVENT_DELETED":     3,
	}
)

func (x ConfigEventType) Enum() *ConfigEventType {
	p := new(ConfigEventType)
	*p = x
	return p
}

func (x ConfigEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_scv3_config_proto_enumTypes[1].Descriptor()
}

func (ConfigEventType) Type() protoreflect.EnumType {
	return &file_scv3_config_proto_enumTypes[1]
}

func (x ConfigEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigEventType.Descriptor instead.
func (ConfigEventType) EnumDescriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{1}
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_scv3_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// ConfigData 是配置内容。草稿没有 version/md5；已发布才有。
type ConfigData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,3,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=contentType,proto3" json:"contentType,omitempty"`
	ConfigContent string                 `protobuf:"bytes,5,opt,name=configContent,proto3" json:"configContent,omitempty"`
	ContentMd5    string                 `protobuf:"bytes,6,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`
	ConfigDesc    string                 `protobuf:"bytes,7,opt,name=configDesc,proto3" json:"configDesc,omitempty"`
	ConfigVersion int64                  `protobuf:"varint,8,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigData) Reset() {
	*x = ConfigData{}
	mi := &file_scv3_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigData) ProtoMessage() {}

func (x *ConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigData.ProtoReflect.Descriptor instead.
func (*ConfigData) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigData) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigData) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigData) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *ConfigData) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfigData) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *ConfigData) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

func (x *ConfigData) GetConfigDesc() string {
	if x != nil {
		return x.ConfigDesc
	}
	return ""
}

func (x *ConfigData) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// ConfigHistory 是一次已发布快照。回滚请用 configVersion，不要用 configHistoryId。
type ConfigHistory struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigHistoryId int64                  `protobuf:"varint,1,opt,name=configHistoryId,proto3" json:"configHistoryId,omitempty"` // 遗留字段，客户端应忽略
	NamespaceId     string                 `protobuf:"bytes,2,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName       string                 `protobuf:"bytes,3,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId    string                 `protobuf:"bytes,4,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	ContentType     string                 `protobuf:"bytes,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	ConfigContent   string                 `protobuf:"bytes,6,opt,name=configContent,proto3" json:"configContent,omitempty"`
	ContentMd5      string                 `protobuf:"bytes,7,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`
	ConfigVersion   int64                  `protobuf:"varint,8,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	ChangeType      ConfigChangeType       `protobuf:"varint,9,opt,name=changeType,proto3,enum=servicecenterv3.config.ConfigChangeType" json:"changeType,omitempty"`
	ChangeReason    string                 `protobuf:"bytes,10,opt,name=changeReason,proto3" json:"changeReason,omitempty"`
	ChangedBy       string                 `protobuf:"bytes,11,opt,name=changedBy,proto3" json:"changedBy,omitempty"`
	ChangeTime      int64                  `protobuf:"varint,12,opt,name=changeTime,proto3" json:"changeTime,omitempty"` // Unix 毫秒
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigHistory) Reset() {
	*x = ConfigHistory{}
	mi := &file_scv3_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigHistory) ProtoMessage() {}

func (x *ConfigHistory) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigHistory.ProtoReflect.Descriptor instead.
func (*ConfigHistory) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigHistory) GetConfigHistoryId() int64 {
	if x != nil {
		return x.ConfigHistoryId
	}
	return 0
}

func (x *ConfigHistory) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigHistory) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigHistory) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *ConfigHistory) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfigHistory) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *ConfigHistory) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

func (x *ConfigHistory) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ConfigHistory) GetChangeType() ConfigChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ConfigChangeType_CONFIG_CHANGE_TYPE_UNSPECIFIED
}

func (x *ConfigHistory) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

func (x *ConfigHistory) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *ConfigHistory) GetChangeTime() int64 {
	if x != nil {
		return x.ChangeTime
	}
	return 0
}

type ConfigKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,3,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigKey) Reset() {
	*x = ConfigKey{}
	mi := &file_scv3_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigKey) ProtoMessage() {}

func (x *ConfigKey) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigKey.ProtoReflect.Descriptor instead.
func (*ConfigKey) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigKey) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigKey) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigKey) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Config        *ConfigData            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_scv3_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConfigResponse) GetConfig() *ConfigData {
	if x != nil {
		return x.Config
	}
	return nil
}

type SaveConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	ContentMd5    string                 `protobuf:"bytes,5,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfigResponse) Reset() {
	*x = SaveConfigResponse{}
	mi := &file_scv3_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigResponse) ProtoMessage() {}

func (x *SaveConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigResponse.ProtoReflect.Descriptor instead.
func (*SaveConfigResponse) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{5}
}

func (x *SaveConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveConfigResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SaveConfigResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SaveConfigResponse) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

type ListConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Configs       []*ConfigData          `protobuf:"bytes,3,rep,name=configs,proto3" json:"configs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,4,opt,name=nextPageToken,proto3" json:"nextPageToken,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsResponse) Reset() {
	*x = ListConfigsResponse{}
	mi := &file_scv3_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsResponse) ProtoMessage() {}

func (x *ListConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigsResponse) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{6}
}

func (x *ListConfigsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListConfigsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListConfigsResponse) GetConfigs() []*ConfigData {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListConfigsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListConfigsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetConfigHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	History       []*ConfigHistory       `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	NextPageToken string                 `protobuf:"bytes,4,opt,name=nextPageToken,proto3" json:"nextPageToken,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigHistoryResponse) Reset() {
	*x = GetConfigHistoryResponse{}
	mi := &file_scv3_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigHistoryResponse) ProtoMessage() {}

func (x *GetConfigHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetConfigHistoryResponse) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConfigHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConfigHistoryResponse) GetHistory() []*ConfigHistory {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetConfigHistoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetConfigHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RollbackConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	NewVersion    int64                  `protobuf:"varint,4,opt,name=newVersion,proto3" json:"newVersion,omitempty"`
	ContentMd5    string                 `protobuf:"bytes,5,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackConfigResponse) Reset() {
	*x = RollbackConfigResponse{}
	mi := &file_scv3_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackConfigResponse) ProtoMessage() {}

func (x *RollbackConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackConfigResponse.ProtoReflect.Descriptor instead.
func (*RollbackConfigResponse) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{8}
}

func (x *RollbackConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RollbackConfigResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RollbackConfigResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

func (x *RollbackConfigResponse) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

type PublishConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,3,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	ChangeReason  string                 `protobuf:"bytes,4,opt,name=changeReason,proto3" json:"changeReason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishConfigRequest) Reset() {
	*x = PublishConfigRequest{}
	mi := &file_scv3_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishConfigRequest) ProtoMessage() {}

func (x *PublishConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishConfigRequest.ProtoReflect.Descriptor instead.
func (*PublishConfigRequest) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{9}
}

func (x *PublishConfigRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *PublishConfigRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *PublishConfigRequest) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *PublishConfigRequest) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

type ListConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=pageToken,proto3" json:"pageToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_scv3_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{10}
}

func (x *ListConfigsRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ListConfigsRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ListConfigsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConfigsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type WatchConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataIds []string               `protobuf:"bytes,3,rep,name=configDataIds,proto3" json:"configDataIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigRequest) Reset() {
	*x = WatchConfigRequest{}
	mi := &file_scv3_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigRequest) ProtoMessage() {}

func (x *WatchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchConfigRequest) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{11}
}

func (x *WatchConfigRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *WatchConfigRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *WatchConfigRequest) GetConfigDataIds() []string {
	if x != nil {
		return x.ConfigDataIds
	}
	return nil
}

type GetConfigHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,3,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // 兼容：pageSize 为 0 时使用
	PageSize      int32                  `protobuf:"varint,5,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=pageToken,proto3" json:"pageToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigHistoryRequest) Reset() {
	*x = GetConfigHistoryRequest{}
	mi := &file_scv3_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigHistoryRequest) ProtoMessage() {}

func (x *GetConfigHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetConfigHistoryRequest) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfigHistoryRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *GetConfigHistoryRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GetConfigHistoryRequest) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *GetConfigHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetConfigHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetConfigHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type RollbackConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,3,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	TargetVersion int64                  `protobuf:"varint,4,opt,name=targetVersion,proto3" json:"targetVersion,omitempty"`
	ChangeReason  string                 `protobuf:"bytes,6,opt,name=changeReason,proto3" json:"changeReason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackConfigRequest) Reset() {
	*x = RollbackConfigRequest{}
	mi := &file_scv3_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackConfigRequest) ProtoMessage() {}

func (x *RollbackConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackConfigRequest.ProtoReflect.Descriptor instead.
func (*RollbackConfigRequest) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackConfigRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *RollbackConfigRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *RollbackConfigRequest) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *RollbackConfigRequest) GetTargetVersion() int64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

func (x *RollbackConfigRequest) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

// ConfigChangeEvent 由服务端推送，requestId 为空。删除时 config 为空。
type ConfigChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     ConfigEventType        `protobuf:"varint,1,opt,name=eventType,proto3,enum=servicecenterv3.config.ConfigEventType" json:"eventType,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix 毫秒
	NamespaceId   string                 `protobuf:"bytes,3,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,5,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	Config        *ConfigData            `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	ContentMd5    string                 `protobuf:"bytes,7,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangeEvent) Reset() {
	*x = ConfigChangeEvent{}
	mi := &file_scv3_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeEvent) ProtoMessage() {}

func (x *ConfigChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeEvent.ProtoReflect.Descriptor instead.
func (*ConfigChangeEvent) Descriptor() ([]byte, []int) {
	return file_scv3_config_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigChangeEvent) GetEventType() ConfigEventType {
	if x != nil {
		return x.EventType
	}
	return ConfigEventType_CONFIG_EVENT_UNSPECIFIED
}

func (x *ConfigChangeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConfigChangeEvent) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigChangeEvent) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigChangeEvent) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *ConfigChangeEvent) GetConfig() *ConfigData {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigChangeEvent) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

var File_scv3_config_proto protoreflect.FileDescriptor

const file_scv3_config_proto_rawDesc = "" +
	"\n" +
	"\x11scv3_config.proto\x12\x16servicecenterv3.config\"X\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\xd5\x02\n" +
	"\n" +
	"ConfigData\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x03 \x01(\tR\fconfigDataId\x12 \n" +
	"\vcontentType\x18\x04 \x01(\tR\vcontentType\x12$\n" +
	"\rconfigContent\x18\x05 \x01(\tR\rconfigContent\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\x06 \x01(\tR\n" +
	"contentMd5\x12\x1e\n" +
	"\n" +
	"configDesc\x18\a \x01(\tR\n" +
	"configDesc\x12$\n" +
	"\rconfigVersion\x18\b \x01(\x03R\rconfigVersionJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fR\n" +
	"changeTypeR\fchangeReasonR\tchangedBy\"\xd7\x03\n" +
	"\rConfigHistory\x12(\n" +
	"\x0fconfigHistoryId\x18\x01 \x01(\x03R\x0fconfigHistoryId\x12 \n" +
	"\vnamespaceId\x18\x02 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x03 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x04 \x01(\tR\fconfigDataId\x12 \n" +
	"\vcontentType\x18\x05 \x01(\tR\vcontentType\x12$\n" +
	"\rconfigContent\x18\x06 \x01(\tR\rconfigContent\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\a \x01(\tR\n" +
	"contentMd5\x12$\n" +
	"\rconfigVersion\x18\b \x01(\x03R\rconfigVersion\x12H\n" +
	"\n" +
	"changeType\x18\t \x01(\x0e2(.servicecenterv3.config.ConfigChangeTypeR\n" +
	"changeType\x12\"\n" +
	"\fchangeReason\x18\n" +
	" \x01(\tR\fchangeReason\x12\x1c\n" +
	"\tchangedBy\x18\v \x01(\tR\tchangedBy\x12\x1e\n" +
	"\n" +
	"changeTime\x18\f \x01(\x03R\n" +
	"changeTime\"o\n" +
	"\tConfigKey\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x03 \x01(\tR\fconfigDataId\"\x83\x01\n" +
	"\x11GetConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x06config\x18\x03 \x01(\v2\".servicecenterv3.config.ConfigDataR\x06config\"\x96\x01\n" +
	"\x12SaveConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\x05 \x01(\tR\n" +
	"contentMd5\"\xc3\x01\n" +
	"\x13ListConfigsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\aconfigs\x18\x03 \x03(\v2\".servicecenterv3.config.ConfigDataR\aconfigs\x12$\n" +
	"\rnextPageToken\x18\x04 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\"\xcb\x01\n" +
	"\x18GetConfigHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\ahistory\x18\x03 \x03(\v2%.servicecenterv3.config.ConfigHistoryR\ahistory\x12$\n" +
	"\rnextPageToken\x18\x04 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\"\xa0\x01\n" +
	"\x16RollbackConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"newVersion\x18\x04 \x01(\x03R\n" +
	"newVersion\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\x05 \x01(\tR\n" +
	"contentMd5\"\x9e\x01\n" +
	"\x14PublishConfigRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x03 \x01(\tR\fconfigDataId\x12\"\n" +
	"\fchangeReason\x18\x04 \x01(\tR\fchangeReason\"\x8e\x01\n" +
	"\x12ListConfigsRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x12\x1c\n" +
	"\tpageToken\x18\x04 \x01(\tR\tpageToken\"z\n" +
	"\x12WatchConfigRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12$\n" +
	"\rconfigDataIds\x18\x03 \x03(\tR\rconfigDataIds\"\xcd\x01\n" +
	"\x17GetConfigHistoryRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x03 \x01(\tR\fconfigDataId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bpageSize\x18\x05 \x01(\x05R\bpageSize\x12\x1c\n" +
	"\tpageToken\x18\x06 \x01(\tR\tpageToken\"\xd6\x01\n" +
	"\x15RollbackConfigRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x03 \x01(\tR\fconfigDataId\x12$\n" +
	"\rtargetVersion\x18\x04 \x01(\x03R\rtargetVersion\x12\"\n" +
	"\fchangeReason\x18\x06 \x01(\tR\fchangeReasonJ\x04\b\x05\x10\x06R\tchangedBy\"\xb8\x02\n" +
	"\x11ConfigChangeEvent\x12E\n" +
	"\teventType\x18\x01 \x01(\x0e2'.servicecenterv3.config.ConfigEventTypeR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12 \n" +
	"\vnamespaceId\x18\x03 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x04 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x05 \x01(\tR\fconfigDataId\x12:\n" +
	"\x06config\x18\x06 \x01(\v2\".servicecenterv3.config.ConfigDataR\x06config\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\a \x01(\tR\n" +
	"contentMd5*\x90\x01\n" +
	"\x10ConfigChangeType\x12\"\n" +
	"\x1eCONFIG_CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CONFIG_CHANGE_TYPE_ADD\x10\x01\x12\x1d\n" +
	"\x19CONFIG_CHANGE_TYPE_UPDATE\x10\x02\x12\x1d\n" +
	"\x19CONFIG_CHANGE_TYPE_DELETE\x10\x03*\x83\x01\n" +
	"\x0fConfigEventType\x12\x1c\n" +
	"\x18CONFIG_EVENT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CONFIG_EVENT_PUBLISHED\x10\x01\x12\x1c\n" +
	"\x18CONFIG_EVENT_ROLLED_BACK\x10\x02\x12\x18\n" +
	"\x14CONFIG_EVENT_DELETED\x10\x03BZ\n" +
	"\x1dcom.flux.servicecenter.configB\vConfigProtoZ,gateway/internal/servicecenterv3/proto;protob\x06proto3"

var (
	file_scv3_config_proto_rawDescOnce sync.Once
	file_scv3_config_proto_rawDescData []byte
)

func file_scv3_config_proto_rawDescGZIP() []byte {
	file_scv3_config_proto_rawDescOnce.Do(func() {
		file_scv3_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scv3_config_proto_rawDesc), len(file_scv3_config_proto_rawDesc)))
	})
	return file_scv3_config_proto_rawDescData
}

var file_scv3_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scv3_config_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_scv3_config_proto_goTypes = []any{
	(ConfigChangeType)(0),            // 0: servicecenterv3.config.ConfigChangeType
	(ConfigEventType)(0),             // 1: servicecenterv3.config.ConfigEventType
	(*ConfigResponse)(nil),           // 2: servicecenterv3.config.ConfigResponse
	(*ConfigData)(nil),               // 3: servicecenterv3.config.ConfigData
	(*ConfigHistory)(nil),            // 4: servicecenterv3.config.ConfigHistory
	(*ConfigKey)(nil),                // 5: servicecenterv3.config.ConfigKey
	(*GetConfigResponse)(nil),        // 6: servicecenterv3.config.GetConfigResponse
	(*SaveConfigResponse)(nil),       // 7: servicecenterv3.config.SaveConfigResponse
	(*ListConfigsResponse)(nil),      // 8: servicecenterv3.config.ListConfigsResponse
	(*GetConfigHistoryResponse)(nil), // 9: servicecenterv3.config.GetConfigHistoryResponse
	(*RollbackConfigResponse)(nil),   // 10: servicecenterv3.config.RollbackConfigResponse
	(*PublishConfigRequest)(nil),     // 11: servicecenterv3.config.PublishConfigRequest
	(*ListConfigsRequest)(nil),       // 12: servicecenterv3.config.ListConfigsRequest
	(*WatchConfigRequest)(nil),       // 13: servicecenterv3.config.WatchConfigRequest
	(*GetConfigHistoryRequest)(nil),  // 14: servicecenterv3.config.GetConfigHistoryRequest
	(*RollbackConfigRequest)(nil),    // 15: servicecenterv3.config.RollbackConfigRequest
	(*ConfigChangeEvent)(nil),        // 16: servicecenterv3.config.ConfigChangeEvent
}
var file_scv3_config_proto_depIdxs = []int32{
	0, // 0: servicecenterv3.config.ConfigHistory.changeType:type_name -> servicecenterv3.config.ConfigChangeType
	3, // 1: servicecenterv3.config.GetConfigResponse.config:type_name -> servicecenterv3.config.ConfigData
	3, // 2: servicecenterv3.config.ListConfigsResponse.configs:type_name -> servicecenterv3.config.ConfigData
	4, // 3: servicecenterv3.config.GetConfigHistoryResponse.history:type_name -> servicecenterv3.config.ConfigHistory
	1, // 4: servicecenterv3.config.ConfigChangeEvent.eventType:type_name -> servicecenterv3.config.ConfigEventType
	3, // 5: servicecenterv3.config.ConfigChangeEvent.config:type_name -> servicecenterv3.config.ConfigData
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_scv3_config_proto_init() }
func file_scv3_config_proto_init() {
	if File_scv3_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scv3_config_proto_rawDesc), len(file_scv3_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scv3_config_proto_goTypes,
		DependencyIndexes: file_scv3_config_proto_depIdxs,
		EnumInfos:         file_scv3_config_proto_enumTypes,
		MessageInfos:      file_scv3_config_proto_msgTypes,
	}.Build()
	File_scv3_config_proto = out.File
	file_scv3_config_proto_goTypes = nil
	file_scv3_config_proto_depIdxs = nil
}
