// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: scv3_registry.proto

// 文件名 scv3_registry.proto，避免与旧包 registry.proto 撞 protobuf 全局注册表。

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstanceStatus 是人工/注册状态，与 HealthyStatus 正交。
type InstanceStatus int32

const (
	InstanceStatus_INSTANCE_STATUS_UNSPECIFIED    InstanceStatus = 0 // 按 UP 处理
	InstanceStatus_INSTANCE_STATUS_UP             InstanceStatus = 1
	InstanceStatus_INSTANCE_STATUS_DOWN           InstanceStatus = 2
	InstanceStatus_INSTANCE_STATUS_STARTING       InstanceStatus = 3
	InstanceStatus_INSTANCE_STATUS_OUT_OF_SERVICE InstanceStatus = 4
)

// Enum value maps for InstanceStatus.
var (
	InstanceStatus_name = map[int32]string{
		0: "INSTANCE_STATUS_UNSPECIFIED",
		1: "INSTANCE_STATUS_UP",
		2: "INSTANCE_STATUS_DOWN",
		3: "INSTANCE_STATUS_STARTING",
		4: "INSTANCE_STATUS_OUT_OF_SERVICE",
	}
	InstanceStatus_value = map[string]int32{
		"INSTANCE_STATUS_UNSPECIFIED":    0,
		"INSTANCE_STATUS_UP":             1,
		"INSTANCE_STATUS_DOWN":           2,
		"INSTANCE_STATUS_STARTING":       3,
		"INSTANCE_STATUS_OUT_OF_SERVICE": 4,
	}
)

func (x InstanceStatus) Enum() *InstanceStatus {
	p := new(InstanceStatus)
	*p = x
	return p
}

func (x InstanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scv3_registry_proto_enumTypes[0].Descriptor()
}

func (InstanceStatus) Type() protoreflect.EnumType {
	return &file_scv3_registry_proto_enumTypes[0]
}

func (x InstanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceStatus.Descriptor instead.
func (InstanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{0}
}

// HealthyStatus 是探测结果。
type HealthyStatus int32

const (
	HealthyStatus_HEALTHY_STATUS_UNSPECIFIED HealthyStatus = 0 // 按 HEALTHY 处理
	HealthyStatus_HEALTHY_STATUS_HEALTHY     HealthyStatus = 1
	HealthyStatus_HEALTHY_STATUS_UNHEALTHY   HealthyStatus = 2
	HealthyStatus_HEALTHY_STATUS_UNKNOWN     HealthyStatus = 3
)

// Enum value maps for HealthyStatus.
var (
	HealthyStatus_name = map[int32]string{
		0: "HEALTHY_STATUS_UNSPECIFIED",
		1: "HEALTHY_STATUS_HEALTHY",
		2: "HEALTHY_STATUS_UNHEALTHY",
		3: "HEALTHY_STATUS_UNKNOWN",
	}
	HealthyStatus_value = map[string]int32{
		"HEALTHY_STATUS_UNSPECIFIED": 0,
		"HEALTHY_STATUS_HEALTHY":     1,
		"HEALTHY_STATUS_UNHEALTHY":   2,
		"HEALTHY_STATUS_UNKNOWN":     3,
	}
)

func (x HealthyStatus) Enum() *HealthyStatus {
	p := new(HealthyStatus)
	*p = x
	return p
}

func (x HealthyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scv3_registry_proto_enumTypes[1].Descriptor()
}

func (HealthyStatus) Type() protoreflect.EnumType {
	return &file_scv3_registry_proto_enumTypes[1]
}

func (x HealthyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthyStatus.Descriptor instead.
func (HealthyStatus) EnumDescriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{1}
}

// NamingEventType 是命名推送类型。节点事件用 NODE_*，不再使用 INSTANCE_* 字符串。
type NamingEventType int32

const (
	NamingEventType_NAMING_EVENT_UNSPECIFIED       NamingEventType = 0
	NamingEventType_NAMING_EVENT_SERVICE_ADDED     NamingEventType = 1
	NamingEventType_NAMING_EVENT_SERVICE_UPDATED   NamingEventType = 2
	NamingEventType_NAMING_EVENT_SERVICE_DELETED   NamingEventType = 3
	NamingEventType_NAMING_EVENT_NODE_REGISTERED   NamingEventType = 4
	NamingEventType_NAMING_EVENT_NODE_UPDATED      NamingEventType = 5
	NamingEventType_NAMING_EVENT_NODE_DEREGISTERED NamingEventType = 6
	NamingEventType_NAMING_EVENT_NODE_EVICTED      NamingEventType = 7
	NamingEventType_NAMING_EVENT_NODE_OFFLINE      NamingEventType = 8
)

// Enum value maps for NamingEventType.
var (
	NamingEventType_name = map[int32]string{
		0: "NAMING_EVENT_UNSPECIFIED",
		1: "NAMING_EVENT_SERVICE_ADDED",
		2: "NAMING_EVENT_SERVICE_UPDATED",
		3: "NAMING_EVENT_SERVICE_DELETED",
		4: "NAMING_EVENT_NODE_REGISTERED",
		5: "NAMING_EVENT_NODE_UPDATED",
		6: "NAMING_EVENT_NODE_DEREGISTERED",
		7: "NAMING_EVENT_NODE_EVICTED",
		8: "NAMING_EVENT_NODE_OFFLINE",
	}
	NamingEventType_value = map[string]int32{
		"NAMING_EVENT_UNSPECIFIED":       0,
		"NAMING_EVENT_SERVICE_ADDED":     1,
		"NAMING_EVENT_SERVICE_UPDATED":   2,
		"NAMING_EVENT_SERVICE_DELETED":   3,
		"NAMING_EVENT_NODE_REGISTERED":   4,
		"NAMING_EVENT_NODE_UPDATED":      5,
		"NAMING_EVENT_NODE_DEREGISTERED": 6,
		"NAMING_EVENT_NODE_EVICTED":      7,
		"NAMING_EVENT_NODE_OFFLINE":      8,
	}
)

func (x NamingEventType) Enum() *NamingEventType {
	p := new(NamingEventType)
	*p = x
	return p
}

func (x NamingEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NamingEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_scv3_registry_proto_enumTypes[2].Descriptor()
}

func (NamingEventType) Type() protoreflect.EnumType {
	return &file_scv3_registry_proto_enumTypes[2]
}

func (x NamingEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NamingEventType.Descriptor instead.
func (NamingEventType) EnumDescriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{2}
}

type RegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryResponse) Reset() {
	*x = RegistryResponse{}
	mi := &file_scv3_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryResponse) ProtoMessage() {}

func (x *RegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryResponse.ProtoReflect.Descriptor instead.
func (*RegistryResponse) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegistryResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Service 是服务定义。node 仅注册请求可带，用于一次写入一个实例；读路径不要填。
type Service struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId        string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName          string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName        string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceType        string                 `protobuf:"bytes,4,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	ServiceVersion     string                 `protobuf:"bytes,5,opt,name=serviceVersion,proto3" json:"serviceVersion,omitempty"`
	ServiceDescription string                 `protobuf:"bytes,6,opt,name=serviceDescription,proto3" json:"serviceDescription,omitempty"`
	ProtectThreshold   float64                `protobuf:"fixed64,7,opt,name=protectThreshold,proto3" json:"protectThreshold,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags               map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Node               *Node                  `protobuf:"bytes,10,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_scv3_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Service) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Service) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Service) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *Service) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *Service) GetServiceDescription() string {
	if x != nil {
		return x.ServiceDescription
	}
	return ""
}

func (x *Service) GetProtectThreshold() float64 {
	if x != nil {
		return x.ProtectThreshold
	}
	return 0
}

func (x *Service) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Service) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// Node 是服务实例。ephemeral 未设置时按临时实例处理。
type Node struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NamespaceId    string                 `protobuf:"bytes,2,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName      string                 `protobuf:"bytes,3,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName    string                 `protobuf:"bytes,4,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	IpAddress      string                 `protobuf:"bytes,5,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	PortNumber     int32                  `protobuf:"varint,6,opt,name=portNumber,proto3" json:"portNumber,omitempty"`
	Weight         float64                `protobuf:"fixed64,7,opt,name=weight,proto3" json:"weight,omitempty"`
	Ephemeral      *bool                  `protobuf:"varint,8,opt,name=ephemeral,proto3,oneof" json:"ephemeral,omitempty"`
	InstanceStatus InstanceStatus         `protobuf:"varint,9,opt,name=instanceStatus,proto3,enum=servicecenterv3.registry.InstanceStatus" json:"instanceStatus,omitempty"`
	HealthyStatus  HealthyStatus          `protobuf:"varint,10,opt,name=healthyStatus,proto3,enum=servicecenterv3.registry.HealthyStatus" json:"healthyStatus,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_scv3_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Node) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Node) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Node) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Node) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Node) GetPortNumber() int32 {
	if x != nil {
		return x.PortNumber
	}
	return 0
}

func (x *Node) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Node) GetEphemeral() bool {
	if x != nil && x.Ephemeral != nil {
		return *x.Ephemeral
	}
	return false
}

func (x *Node) GetInstanceStatus() InstanceStatus {
	if x != nil {
		return x.InstanceStatus
	}
	return InstanceStatus_INSTANCE_STATUS_UNSPECIFIED
}

func (x *Node) GetHealthyStatus() HealthyStatus {
	if x != nil {
		return x.HealthyStatus
	}
	return HealthyStatus_HEALTHY_STATUS_UNSPECIFIED
}

func (x *Node) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ServiceKey 只标识服务。注销节点必须走 NodeKey。
type ServiceKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceKey) Reset() {
	*x = ServiceKey{}
	mi := &file_scv3_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceKey) ProtoMessage() {}

func (x *ServiceKey) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceKey.ProtoReflect.Descriptor instead.
func (*ServiceKey) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceKey) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ServiceKey) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ServiceKey) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type NodeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeKey) Reset() {
	*x = NodeKey{}
	mi := &file_scv3_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeKey) ProtoMessage() {}

func (x *NodeKey) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeKey.ProtoReflect.Descriptor instead.
func (*NodeKey) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{4}
}

func (x *NodeKey) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=nodeId,proto3" json:"nodeId,omitempty"` // 注册时带了 node 才有值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_scv3_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterServiceResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterServiceResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Service       *Service               `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_scv3_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{6}
}

func (x *GetServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *GetServiceResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_scv3_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DiscoverNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverNodesResponse) Reset() {
	*x = DiscoverNodesResponse{}
	mi := &file_scv3_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverNodesResponse) ProtoMessage() {}

func (x *DiscoverNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverNodesResponse.ProtoReflect.Descriptor instead.
func (*DiscoverNodesResponse) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoverNodesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DiscoverNodesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DiscoverNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"` // 空表示命名空间下全部组
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`  // 0 表示不分页
	PageToken     string                 `protobuf:"bytes,4,opt,name=pageToken,proto3" json:"pageToken,omitempty"` // 上一页返回的 nextPageToken
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_scv3_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{9}
}

func (x *ListServicesRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ListServicesRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ListServicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListServicesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Services      []*Service             `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	NextPageToken string                 `protobuf:"bytes,4,opt,name=nextPageToken,proto3" json:"nextPageToken,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_scv3_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{10}
}

func (x *ListServicesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListServicesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListServicesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListServicesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DiscoverNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	HealthyOnly   bool                   `protobuf:"varint,4,opt,name=healthyOnly,proto3" json:"healthyOnly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverNodesRequest) Reset() {
	*x = DiscoverNodesRequest{}
	mi := &file_scv3_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverNodesRequest) ProtoMessage() {}

func (x *DiscoverNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverNodesRequest.ProtoReflect.Descriptor instead.
func (*DiscoverNodesRequest) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{11}
}

func (x *DiscoverNodesRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *DiscoverNodesRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *DiscoverNodesRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DiscoverNodesRequest) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

// SubscribeServicesRequest 在当前 Connect 上追加服务名订阅。
type SubscribeServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceNames  []string               `protobuf:"bytes,3,rep,name=serviceNames,proto3" json:"serviceNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServicesRequest) Reset() {
	*x = SubscribeServicesRequest{}
	mi := &file_scv3_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServicesRequest) ProtoMessage() {}

func (x *SubscribeServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServicesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeServicesRequest) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeServicesRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *SubscribeServicesRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *SubscribeServicesRequest) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

type SubscribeNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"` // 空则订阅整个命名空间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeNamespaceRequest) Reset() {
	*x = SubscribeNamespaceRequest{}
	mi := &file_scv3_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeNamespaceRequest) ProtoMessage() {}

func (x *SubscribeNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeNamespaceRequest.ProtoReflect.Descriptor instead.
func (*SubscribeNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeNamespaceRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *SubscribeNamespaceRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

// ServiceChangeEvent 由服务端推送，requestId 为空。
type ServiceChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     NamingEventType        `protobuf:"varint,1,opt,name=eventType,proto3,enum=servicecenterv3.registry.NamingEventType" json:"eventType,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix 毫秒
	NamespaceId   string                 `protobuf:"bytes,3,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Service       *Service               `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`
	ChangedNode   *Node                  `protobuf:"bytes,8,opt,name=changedNode,proto3" json:"changedNode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceChangeEvent) Reset() {
	*x = ServiceChangeEvent{}
	mi := &file_scv3_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChangeEvent) ProtoMessage() {}

func (x *ServiceChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChangeEvent.ProtoReflect.Descriptor instead.
func (*ServiceChangeEvent) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{14}
}

func (x *ServiceChangeEvent) GetEventType() NamingEventType {
	if x != nil {
		return x.EventType
	}
	return NamingEventType_NAMING_EVENT_UNSPECIFIED
}

func (x *ServiceChangeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ServiceChangeEvent) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ServiceChangeEvent) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ServiceChangeEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceChangeEvent) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceChangeEvent) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ServiceChangeEvent) GetChangedNode() *Node {
	if x != nil {
		return x.ChangedNode
	}
	return nil
}

// HeartbeatRequest 只续命。service 可选，用于刷新定义/实例元数据，不是断线恢复通道。
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Service       *Service               `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_scv3_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scv3_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_scv3_registry_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

var File_scv3_registry_proto protoreflect.FileDescriptor

const file_scv3_registry_proto_rawDesc = "" +
	"\n" +
	"\x13scv3_registry.proto\x12\x18servicecenterv3.registry\"Z\n" +
	"\x10RegistryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\xc9\x04\n" +
	"\aService\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceName\x12 \n" +
	"\vserviceType\x18\x04 \x01(\tR\vserviceType\x12&\n" +
	"\x0eserviceVersion\x18\x05 \x01(\tR\x0eserviceVersion\x12.\n" +
	"\x12serviceDescription\x18\x06 \x01(\tR\x12serviceDescription\x12*\n" +
	"\x10protectThreshold\x18\a \x01(\x01R\x10protectThreshold\x12K\n" +
	"\bmetadata\x18\b \x03(\v2/.servicecenterv3.registry.Service.MetadataEntryR\bmetadata\x12?\n" +
	"\x04tags\x18\t \x03(\v2+.servicecenterv3.registry.Service.TagsEntryR\x04tags\x122\n" +
	"\x04node\x18\n" +
	" \x01(\v2\x1e.servicecenterv3.registry.NodeR\x04node\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x04\n" +
	"\x04Node\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12 \n" +
	"\vnamespaceId\x18\x02 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x03 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x04 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tipAddress\x18\x05 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"portNumber\x18\x06 \x01(\x05R\n" +
	"portNumber\x12\x16\n" +
	"\x06weight\x18\a \x01(\x01R\x06weight\x12!\n" +
	"\tephemeral\x18\b \x01(\bH\x00R\tephemeral\x88\x01\x01\x12P\n" +
	"\x0einstanceStatus\x18\t \x01(\x0e2(.servicecenterv3.registry.InstanceStatusR\x0einstanceStatus\x12M\n" +
	"\rhealthyStatus\x18\n" +
	" \x01(\x0e2'.servicecenterv3.registry.HealthyStatusR\rhealthyStatus\x12H\n" +
	"\bmetadata\x18\v \x03(\v2,.servicecenterv3.registry.Node.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_ephemeral\"|\n" +
	"\n" +
	"ServiceKey\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceNameJ\x04\b\x04\x10\x05R\x06nodeId\"!\n" +
	"\aNodeKey\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\"y\n" +
	"\x17RegisterServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06nodeId\x18\x04 \x01(\tR\x06nodeId\"\xbb\x01\n" +
	"\x12GetServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\aservice\x18\x03 \x01(\v2!.servicecenterv3.registry.ServiceR\aservice\x124\n" +
	"\x05nodes\x18\x04 \x03(\v2\x1e.servicecenterv3.registry.NodeR\x05nodes\"b\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06nodeId\x18\x03 \x01(\tR\x06nodeId\"\x81\x01\n" +
	"\x15DiscoverNodesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x05nodes\x18\x03 \x03(\v2\x1e.servicecenterv3.registry.NodeR\x05nodes\"\x8f\x01\n" +
	"\x13ListServicesRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x12\x1c\n" +
	"\tpageToken\x18\x04 \x01(\tR\tpageToken\"\xc5\x01\n" +
	"\x14ListServicesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\bservices\x18\x03 \x03(\v2!.servicecenterv3.registry.ServiceR\bservices\x12$\n" +
	"\rnextPageToken\x18\x04 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\"\x9a\x01\n" +
	"\x14DiscoverNodesRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceName\x12 \n" +
	"\vhealthyOnly\x18\x04 \x01(\bR\vhealthyOnly\"~\n" +
	"\x18SubscribeServicesRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fserviceNames\x18\x03 \x03(\tR\fserviceNames\"[\n" +
	"\x19SubscribeNamespaceRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\"\x92\x03\n" +
	"\x12ServiceChangeEvent\x12G\n" +
	"\teventType\x18\x01 \x01(\x0e2).servicecenterv3.registry.NamingEventTypeR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12 \n" +
	"\vnamespaceId\x18\x03 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x04 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x05 \x01(\tR\vserviceName\x12;\n" +
	"\aservice\x18\x06 \x01(\v2!.servicecenterv3.registry.ServiceR\aservice\x124\n" +
	"\x05nodes\x18\a \x03(\v2\x1e.servicecenterv3.registry.NodeR\x05nodes\x12@\n" +
	"\vchangedNode\x18\b \x01(\v2\x1e.servicecenterv3.registry.NodeR\vchangedNode\"g\n" +
	"\x10HeartbeatRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12;\n" +
	"\aservice\x18\x02 \x01(\v2!.servicecenterv3.registry.ServiceR\aservice*\xa5\x01\n" +
	"\x0eInstanceStatus\x12\x1f\n" +
	"\x1bINSTANCE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12INSTANCE_STATUS_UP\x10\x01\x12\x18\n" +
	"\x14INSTANCE_STATUS_DOWN\x10\x02\x12\x1c\n" +
	"\x18INSTANCE_STATUS_STARTING\x10\x03\x12\"\n" +
	"\x1eINSTANCE_STATUS_OUT_OF_SERVICE\x10\x04*\x85\x01\n" +
	"\rHealthyStatus\x12\x1e\n" +
	"\x1aHEALTHY_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16HEALTHY_STATUS_HEALTHY\x10\x01\x12\x1c\n" +
	"\x18HEALTHY_STATUS_UNHEALTHY\x10\x02\x12\x1a\n" +
	"\x16HEALTHY_STATUS_UNKNOWN\x10\x03*\xb6\x02\n" +
	"\x0fNamingEventType\x12\x1c\n" +
	"\x18NAMING_EVENT_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNAMING_EVENT_SERVICE_ADDED\x10\x01\x12 \n" +
	"\x1cNAMING_EVENT_SERVICE_UPDATED\x10\x02\x12 \n" +
	"\x1cNAMING_EVENT_SERVICE_DELETED\x10\x03\x12 \n" +
	"\x1cNAMING_EVENT_NODE_REGISTERED\x10\x04\x12\x1d\n" +
	"\x19NAMING_EVENT_NODE_UPDATED\x10\x05\x12\"\n" +
	"\x1eNAMING_EVENT_NODE_DEREGISTERED\x10\x06\x12\x1d\n" +
	"\x19NAMING_EVENT_NODE_EVICTED\x10\a\x12\x1d\n" +
	"\x19NAMING_EVENT_NODE_OFFLINE\x10\bB^\n" +
	"\x1fcom.flux.servicecenter.registryB\rRegistryProtoZ,gateway/internal/servicecenterv3/proto;protob\x06proto3"

var (
	file_scv3_registry_proto_rawDescOnce sync.Once
	file_scv3_registry_proto_rawDescData []byte
)

func file_scv3_registry_proto_rawDescGZIP() []byte {
	file_scv3_registry_proto_rawDescOnce.Do(func() {
		file_scv3_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scv3_registry_proto_rawDesc), len(file_scv3_registry_proto_rawDesc)))
	})
	return file_scv3_registry_proto_rawDescData
}

var file_scv3_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_scv3_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_scv3_registry_proto_goTypes = []any{
	(InstanceStatus)(0),               // 0: servicecenterv3.registry.InstanceStatus
	(HealthyStatus)(0),                // 1: servicecenterv3.registry.HealthyStatus
	(NamingEventType)(0),              // 2: servicecenterv3.registry.NamingEventType
	(*RegistryResponse)(nil),          // 3: servicecenterv3.registry.RegistryResponse
	(*Service)(nil),                   // 4: servicecenterv3.registry.Service
	(*Node)(nil),                      // 5: servicecenterv3.registry.Node
	(*ServiceKey)(nil),                // 6: servicecenterv3.registry.ServiceKey
	(*NodeKey)(nil),                   // 7: servicecenterv3.registry.NodeKey
	(*RegisterServiceResponse)(nil),   // 8: servicecenterv3.registry.RegisterServiceResponse
	(*GetServiceResponse)(nil),        // 9: servicecenterv3.registry.GetServiceResponse
	(*RegisterNodeResponse)(nil),      // 10: servicecenterv3.registry.RegisterNodeResponse
	(*DiscoverNodesResponse)(nil),     // 11: servicecenterv3.registry.DiscoverNodesResponse
	(*ListServicesRequest)(nil),       // 12: servicecenterv3.registry.ListServicesRequest
	(*ListServicesResponse)(nil),      // 13: servicecenterv3.registry.ListServicesResponse
	(*DiscoverNodesRequest)(nil),      // 14: servicecenterv3.registry.DiscoverNodesRequest
	(*SubscribeServicesRequest)(nil),  // 15: servicecenterv3.registry.SubscribeServicesRequest
	(*SubscribeNamespaceRequest)(nil), // 16: servicecenterv3.registry.SubscribeNamespaceRequest
	(*ServiceChangeEvent)(nil),        // 17: servicecenterv3.registry.ServiceChangeEvent
	(*HeartbeatRequest)(nil),          // 18: servicecenterv3.registry.HeartbeatRequest
	nil,                               // 19: servicecenterv3.registry.Service.MetadataEntry
	nil,                               // 20: servicecenterv3.registry.Service.TagsEntry
	nil,                               // 21: servicecenterv3.registry.Node.MetadataEntry
}
var file_scv3_registry_proto_depIdxs = []int32{
	19, // 0: servicecenterv3.registry.Service.metadata:type_name -> servicecenterv3.registry.Service.MetadataEntry
	20, // 1: servicecenterv3.registry.Service.tags:type_name -> servicecenterv3.registry.Service.TagsEntry
	5,  // 2: servicecenterv3.registry.Service.node:type_name -> servicecenterv3.registry.Node
	0,  // 3: servicecenterv3.registry.Node.instanceStatus:type_name -> servicecenterv3.registry.InstanceStatus
	1,  // 4: servicecenterv3.registry.Node.healthyStatus:type_name -> servicecenterv3.registry.HealthyStatus
	21, // 5: servicecenterv3.registry.Node.metadata:type_name -> servicecenterv3.registry.Node.MetadataEntry
	4,  // 6: servicecenterv3.registry.GetServiceResponse.service:type_name -> servicecenterv3.registry.Service
	5,  // 7: servicecenterv3.registry.GetServiceResponse.nodes:type_name -> servicecenterv3.registry.Node
	5,  // 8: servicecenterv3.registry.DiscoverNodesResponse.nodes:type_name -> servicecenterv3.registry.Node
	4,  // 9: servicecenterv3.registry.ListServicesResponse.services:type_name -> servicecenterv3.registry.Service
	2,  // 10: servicecenterv3.registry.ServiceChangeEvent.eventType:type_name -> servicecenterv3.registry.NamingEventType
	4,  // 11: servicecenterv3.registry.ServiceChangeEvent.service:type_name -> servicecenterv3.registry.Service
	5,  // 12: servicecenterv3.registry.ServiceChangeEvent.nodes:type_name -> servicecenterv3.registry.Node
	5,  // 13: servicecenterv3.registry.ServiceChangeEvent.changedNode:type_name -> servicecenterv3.registry.Node
	4,  // 14: servicecenterv3.registry.HeartbeatRequest.service:type_name -> servicecenterv3.registry.Service
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_scv3_registry_proto_init() }
func file_scv3_registry_proto_init() {
	if File_scv3_registry_proto != nil {
		return
	}
	file_scv3_registry_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scv3_registry_proto_rawDesc), len(file_scv3_registry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scv3_registry_proto_goTypes,
		DependencyIndexes: file_scv3_registry_proto_depIdxs,
		EnumInfos:         file_scv3_registry_proto_enumTypes,
		MessageInfos:      file_scv3_registry_proto_msgTypes,
	}.Build()
	File_scv3_registry_proto = out.File
	file_scv3_registry_proto_goTypes = nil
	file_scv3_registry_proto_depIdxs = nil
}
