CREATE TABLE `HUB_METRIC_PROCESS_LOG` (
  `metricProcessLogId` VARCHAR(32) NOT NULL COMMENT '进程信息日志ID',
  `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
  `metricServerId` VARCHAR(32) NOT NULL COMMENT '关联服务器ID',
  `processId` INT NOT NULL COMMENT '进程ID',
  `parentProcessId` INT DEFAULT NULL COMMENT '父进程ID',
  `processName` VARCHAR(200) NOT NULL COMMENT '进程名称',
  `processStatus` VARCHAR(50) NOT NULL COMMENT '进程状态',
  `createTime` DATETIME NOT NULL COMMENT '进程启动时间',
  `runTime` BIGINT NOT NULL DEFAULT 0 COMMENT '进程运行时间(秒)',
  `memoryUsage` BIGINT NOT NULL DEFAULT 0 COMMENT '内存使用(字节)',
  `memoryPercent` DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '内存使用率(0-100)',
  `cpuPercent` DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT 'CPU使用率(0-100)',
  `threadCount` INT NOT NULL DEFAULT 0 COMMENT '线程数',
  `fileDescriptorCount` INT NOT NULL DEFAULT 0 COMMENT '文件句柄数',
  `commandLine` TEXT DEFAULT NULL COMMENT '命令行参数，JSON格式',
  `executablePath` VARCHAR(500) DEFAULT NULL COMMENT '执行路径',
  `workingDirectory` VARCHAR(500) DEFAULT NULL COMMENT '工作目录',
  `collectTime` DATETIME NOT NULL COMMENT '采集时间',
  `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `addWho` VARCHAR(32) NOT NULL COMMENT '创建人ID',
  `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `editWho` VARCHAR(32) NOT NULL COMMENT '最后修改人ID',
  `oprSeqFlag` VARCHAR(32) NOT NULL COMMENT '操作序列标识',
  `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
  `noteText` VARCHAR(500) DEFAULT NULL COMMENT '备注信息',
  `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
  `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
  `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
  `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
  `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
  `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
  `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
  `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
  `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
  `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
  `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
  PRIMARY KEY (`tenantId`, `metricProcessLogId`),
  KEY `IDX_METRIC_PROCESS_SERVER` (`metricServerId`),
  KEY `IDX_METRIC_PROCESS_TIME` (`collectTime`),
  KEY `IDX_METRIC_PROCESS_PID` (`processId`),
  KEY `IDX_METRIC_PROCESS_NAME` (`processName`),
  KEY `IDX_METRIC_PROCESS_STATUS` (`processStatus`),
  KEY `IDX_METRIC_PROCESS_ACTIVE` (`activeFlag`),
  KEY `IDX_METRIC_PROCESS_SRV_TIME` (`metricServerId`, `collectTime`),
  KEY `IDX_METRIC_PROCESS_SRV_PID` (`metricServerId`, `processId`),
  KEY `IDX_METRIC_PROCESS_TNT_TIME` (`tenantId`, `collectTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='进程信息采集日志表';
