CREATE TABLE `HUB_TUNNEL_SERVER` (
                                     `tunnelServerId` VARCHAR(32) NOT NULL COMMENT '隧道服务器ID，主键',
                                     `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
                                     `serverName` VARCHAR(100) NOT NULL COMMENT '服务器名称',
                                     `serverDescription` VARCHAR(500) DEFAULT NULL COMMENT '服务器描述',
                                     `controlAddress` VARCHAR(50) NOT NULL DEFAULT '0.0.0.0' COMMENT '控制端口监听地址',
                                     `controlPort` INT NOT NULL DEFAULT 7000 COMMENT '控制端口（接受客户端连接）',
                                     `dashboardPort` INT DEFAULT 7500 COMMENT '管理面板端口',
                                     `vhostHttpPort` INT DEFAULT 80 COMMENT '虚拟主机HTTP端口',
                                     `vhostHttpsPort` INT DEFAULT 443 COMMENT '虚拟主机HTTPS端口',
                                     `maxClients` INT NOT NULL DEFAULT 1000 COMMENT '最大客户端连接数',
                                     `tokenAuth` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '启用Token认证(N禁用,Y启用)',
                                     `authToken` VARCHAR(100) DEFAULT NULL COMMENT '客户端认证Token',
                                     `tlsEnable` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT 'TLS启用状态(N禁用,Y启用)',
                                     `tlsCertFile` VARCHAR(255) DEFAULT NULL COMMENT 'TLS证书文件路径',
                                     `tlsKeyFile` VARCHAR(255) DEFAULT NULL COMMENT 'TLS私钥文件路径',
                                     `heartbeatInterval` INT NOT NULL DEFAULT 30 COMMENT '心跳间隔(秒)',
                                     `heartbeatTimeout` INT NOT NULL DEFAULT 90 COMMENT '心跳超时(秒)',
                                     `logLevel` VARCHAR(10) NOT NULL DEFAULT 'info' COMMENT '日志级别(debug,info,warn,error)',
                                     `maxPortsPerClient` INT DEFAULT 10 COMMENT '每个客户端最大端口数',
                                     `allowPorts` TEXT DEFAULT NULL COMMENT '允许的端口范围，JSON格式',
                                     `serverStatus` VARCHAR(20) NOT NULL DEFAULT 'stopped' COMMENT '服务器状态(running,stopped,error)',
                                     `startTime` DATETIME DEFAULT NULL COMMENT '服务启动时间',
                                     `configVersion` VARCHAR(32) DEFAULT NULL COMMENT '配置版本号',
                                     `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                     `addWho` VARCHAR(32) NOT NULL COMMENT '创建人ID',
                                     `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
                                     `editWho` VARCHAR(32) NOT NULL COMMENT '最后修改人ID',
                                     `oprSeqFlag` VARCHAR(32) NOT NULL COMMENT '操作序列标识',
                                     `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
                                     `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
                                     `noteText` VARCHAR(500) DEFAULT NULL COMMENT '备注信息',
                                     `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
                                     `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
                                     `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
                                     `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
                                     `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
                                     `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
                                     `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
                                     `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
                                     `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
                                     `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
                                     `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
                                     CONSTRAINT `PK_TUNNEL_SERVER` PRIMARY KEY (`tunnelServerId`),
                                     UNIQUE KEY `IDX_TUNNEL_SVR_NAME` (`serverName`),
                                     KEY `IDX_TUNNEL_SVR_TENANT` (`tenantId`),
                                     KEY `IDX_TUNNEL_SVR_CTRL` (`controlAddress`, `controlPort`),
                                     KEY `IDX_TUNNEL_SVR_STATUS` (`serverStatus`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='隧道服务器配置表，管理控制端口和核心配置';

