CREATE TABLE `HUB_TUNNEL_CLIENT` (
                                     `tunnelClientId` VARCHAR(32) NOT NULL COMMENT '隧道客户端ID，主键',
                                     `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
                                     `userId` VARCHAR(32) NOT NULL COMMENT '用户ID，关联外部用户系统',
                                     `clientName` VARCHAR(100) NOT NULL COMMENT '客户端名称',
                                     `clientDescription` VARCHAR(500) DEFAULT NULL COMMENT '客户端描述',
                                     `clientVersion` VARCHAR(20) DEFAULT NULL COMMENT '客户端版本',
                                     `operatingSystem` VARCHAR(50) DEFAULT NULL COMMENT '操作系统',
                                     `clientIpAddress` VARCHAR(50) DEFAULT NULL COMMENT '客户端IP地址',
                                     `clientMacAddress` VARCHAR(20) DEFAULT NULL COMMENT '客户端MAC地址',
                                     `serverAddress` VARCHAR(100) NOT NULL COMMENT '服务器地址',
                                     `serverPort` INT NOT NULL DEFAULT 7000 COMMENT '服务器控制端口',
                                     `authToken` VARCHAR(100) NOT NULL COMMENT '认证令牌',
                                     `tlsEnable` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '启用TLS(N禁用,Y启用)',
                                     `autoReconnect` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '自动重连(N禁用,Y启用)',
                                     `maxRetries` INT NOT NULL DEFAULT 5 COMMENT '最大重试次数',
                                     `retryInterval` INT NOT NULL DEFAULT 20 COMMENT '重试间隔(秒)',
                                     `heartbeatInterval` INT NOT NULL DEFAULT 30 COMMENT '心跳间隔(秒)',
                                     `heartbeatTimeout` INT NOT NULL DEFAULT 90 COMMENT '心跳超时(秒)',
                                     `connectionStatus` VARCHAR(20) NOT NULL DEFAULT 'disconnected' COMMENT '连接状态(connected,disconnected,connecting,error)',
                                     `lastConnectTime` DATETIME DEFAULT NULL COMMENT '最后连接时间',
                                     `lastDisconnectTime` DATETIME DEFAULT NULL COMMENT '最后断开时间',
                                     `totalConnectTime` BIGINT DEFAULT 0 COMMENT '总连接时长(秒)',
                                     `reconnectCount` INT DEFAULT 0 COMMENT '重连次数',
                                     `serviceCount` INT DEFAULT 0 COMMENT '注册的服务数量',
                                     `lastHeartbeat` DATETIME DEFAULT NULL COMMENT '最后心跳时间',
                                     `clientConfig` TEXT DEFAULT NULL COMMENT '客户端配置，JSON格式',
                                     `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                     `addWho` VARCHAR(32) NOT NULL COMMENT '创建人ID',
                                     `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
                                     `editWho` VARCHAR(32) NOT NULL COMMENT '最后修改人ID',
                                     `oprSeqFlag` VARCHAR(32) NOT NULL COMMENT '操作序列标识',
                                     `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
                                     `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
                                     `noteText` VARCHAR(500) DEFAULT NULL COMMENT '备注信息',
                                     `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
                                     `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
                                     `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
                                     `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
                                     `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
                                     `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
                                     `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
                                     `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
                                     `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
                                     `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
                                     `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
                                     CONSTRAINT `PK_TUNNEL_CLIENT` PRIMARY KEY (`tunnelClientId`),
                                     UNIQUE KEY `IDX_TUNNEL_CLIENT_NAME` (`clientName`),
                                     KEY `IDX_TUNNEL_CLIENT_TENANT` (`tenantId`),
                                     KEY `IDX_TUNNEL_CLIENT_USER` (`userId`),
                                     KEY `IDX_TUNNEL_CLIENT_STATUS` (`connectionStatus`),
                                     KEY `IDX_TUNNEL_CLIENT_IP` (`clientIpAddress`),
                                     KEY `IDX_TUNNEL_CLIENT_HB` (`lastHeartbeat`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='隧道客户端表，管理客户端连接认证和状态跟踪';

