CREATE TABLE `HUB_METRIC_NETWORK_LOG` (
  `metricNetworkLogId` VARCHAR(32) NOT NULL COMMENT '网络接口日志ID',
  `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
  `metricServerId` VARCHAR(32) NOT NULL COMMENT '关联服务器ID',
  `interfaceName` VARCHAR(100) NOT NULL COMMENT '接口名称',
  `hardwareAddr` VARCHAR(50) DEFAULT NULL COMMENT 'MAC地址',
  `ipAddresses` TEXT DEFAULT NULL COMMENT 'IP地址列表，JSON格式',
  `interfaceStatus` VARCHAR(20) NOT NULL COMMENT '接口状态',
  `interfaceType` VARCHAR(50) DEFAULT NULL COMMENT '接口类型',
  `bytesReceived` BIGINT NOT NULL DEFAULT 0 COMMENT '接收字节数',
  `bytesSent` BIGINT NOT NULL DEFAULT 0 COMMENT '发送字节数',
  `packetsReceived` BIGINT NOT NULL DEFAULT 0 COMMENT '接收包数',
  `packetsSent` BIGINT NOT NULL DEFAULT 0 COMMENT '发送包数',
  `errorsReceived` BIGINT NOT NULL DEFAULT 0 COMMENT '接收错误数',
  `errorsSent` BIGINT NOT NULL DEFAULT 0 COMMENT '发送错误数',
  `droppedReceived` BIGINT NOT NULL DEFAULT 0 COMMENT '接收丢包数',
  `droppedSent` BIGINT NOT NULL DEFAULT 0 COMMENT '发送丢包数',
  `receiveRate` DECIMAL(20,2) DEFAULT 0 COMMENT '接收速率(字节/秒)',
  `sendRate` DECIMAL(20,2) DEFAULT 0 COMMENT '发送速率(字节/秒)',
  `collectTime` DATETIME NOT NULL COMMENT '采集时间',
  `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `addWho` VARCHAR(32) NOT NULL COMMENT '创建人ID',
  `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `editWho` VARCHAR(32) NOT NULL COMMENT '最后修改人ID',
  `oprSeqFlag` VARCHAR(32) NOT NULL COMMENT '操作序列标识',
  `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
  `noteText` VARCHAR(500) DEFAULT NULL COMMENT '备注信息',
  `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
  `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
  `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
  `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
  `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
  `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
  `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
  `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
  `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
  `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
  `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
  PRIMARY KEY (`tenantId`, `metricNetworkLogId`),
  KEY `IDX_METRIC_NETWORK_SERVER` (`metricServerId`),
  KEY `IDX_METRIC_NETWORK_TIME` (`collectTime`),
  KEY `IDX_METRIC_NETWORK_INTERFACE` (`interfaceName`),
  KEY `IDX_METRIC_NETWORK_STATUS` (`interfaceStatus`),
  KEY `IDX_METRIC_NETWORK_ACTIVE` (`activeFlag`),
  KEY `IDX_METRIC_NETWORK_SRV_TIME` (`metricServerId`, `collectTime`),
  KEY `IDX_METRIC_NETWORK_SRV_INT` (`metricServerId`, `interfaceName`),
  KEY `IDX_METRIC_NETWORK_TNT_TIME` (`tenantId`, `collectTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网络接口采集日志表';
