CREATE TABLE `HUB_TUNNEL_SERVER_NODE` (
                                          `serverNodeId` VARCHAR(32) NOT NULL COMMENT '服务器节点ID，主键',
                                          `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
                                          `tunnelServerId` VARCHAR(32) NOT NULL COMMENT '隧道服务器ID，关联HUB_TUNNEL_SERVER',
                                          `nodeName` VARCHAR(100) NOT NULL COMMENT '节点名称',
                                          `nodeType` VARCHAR(20) NOT NULL DEFAULT 'static' COMMENT '节点类型(static,dynamic)',
                                          `proxyType` VARCHAR(20) NOT NULL COMMENT '代理类型(tcp,udp,http,https,stcp,sudp)',
                                          `listenAddress` VARCHAR(50) NOT NULL DEFAULT '0.0.0.0' COMMENT '监听地址',
                                          `listenPort` INT NOT NULL COMMENT '监听端口（公网端口）',
                                          `targetAddress` VARCHAR(50) NOT NULL COMMENT '目标地址（内网地址）',
                                          `targetPort` INT NOT NULL COMMENT '目标端口（内网端口）',
                                          `customDomains` TEXT DEFAULT NULL COMMENT '自定义域名列表，JSON格式',
                                          `subDomain` VARCHAR(100) DEFAULT NULL COMMENT '子域名',
                                          `httpUser` VARCHAR(50) DEFAULT NULL COMMENT 'HTTP基础认证用户名',
                                          `httpPassword` VARCHAR(100) DEFAULT NULL COMMENT 'HTTP基础认证密码',
                                          `hostHeaderRewrite` VARCHAR(255) DEFAULT NULL COMMENT '重写Host头',
                                          `headers` TEXT DEFAULT NULL COMMENT '自定义HTTP头，JSON格式',
                                          `locations` TEXT DEFAULT NULL COMMENT 'HTTP路径配置，JSON格式',
                                          `compression` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '启用压缩(N禁用,Y启用)',
                                          `encryption` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '启用加密(N禁用,Y启用)',
                                          `secretKey` VARCHAR(100) DEFAULT NULL COMMENT '加密密钥',
                                          `healthCheckType` VARCHAR(20) DEFAULT 'tcp' COMMENT '健康检查类型(tcp,http)',
                                          `healthCheckUrl` VARCHAR(255) DEFAULT NULL COMMENT '健康检查URL',
                                          `healthCheckInterval` INT DEFAULT 60 COMMENT '健康检查间隔(秒)',
                                          `maxConnections` INT DEFAULT 100 COMMENT '最大连接数',
                                          `nodeStatus` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '节点状态(active,inactive,error)',
                                          `lastHealthCheck` DATETIME DEFAULT NULL COMMENT '最后健康检查时间',
                                          `connectionCount` INT DEFAULT 0 COMMENT '当前连接数',
                                          `totalConnections` BIGINT DEFAULT 0 COMMENT '总连接数',
                                          `totalBytes` BIGINT DEFAULT 0 COMMENT '总传输字节数',
                                          `createdTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '节点创建时间',
                                          `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                          `addWho` VARCHAR(32) NOT NULL COMMENT '创建人ID',
                                          `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
                                          `editWho` VARCHAR(32) NOT NULL COMMENT '最后修改人ID',
                                          `oprSeqFlag` VARCHAR(32) NOT NULL COMMENT '操作序列标识',
                                          `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
                                          `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
                                          `noteText` VARCHAR(500) DEFAULT NULL COMMENT '备注信息',
                                          `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
                                          `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
                                          `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
                                          `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
                                          `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
                                          `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
                                          `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
                                          `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
                                          `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
                                          `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
                                          `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
                                          CONSTRAINT `PK_TUNNEL_SVR_NODE` PRIMARY KEY (`serverNodeId`),
                                          UNIQUE KEY `IDX_TUNNEL_NODE_NAME` (`nodeName`),
                                          UNIQUE KEY `IDX_TUNNEL_NODE_PORT` (`listenAddress`, `listenPort`, `proxyType`),
                                          KEY `IDX_TUNNEL_NODE_TENANT` (`tenantId`),
                                          KEY `IDX_TUNNEL_NODE_SERVER` (`tunnelServerId`),
                                          KEY `IDX_TUNNEL_NODE_TYPE` (`nodeType`, `proxyType`),
                                          KEY `IDX_TUNNEL_NODE_STATUS` (`nodeStatus`),
                                          KEY `IDX_TUNNEL_NODE_HEALTH` (`lastHealthCheck`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='隧道服务器节点表，管理静态端口映射和数据端口转发';

