CREATE TABLE `HUB_METRIC_DISK_PART_LOG` (
  `metricDiskPartitionLogId` VARCHAR(32) NOT NULL COMMENT '磁盘分区日志ID',
  `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
  `metricServerId` VARCHAR(32) NOT NULL COMMENT '关联服务器ID',
  `deviceName` VARCHAR(100) NOT NULL COMMENT '设备名称',
  `mountPoint` VARCHAR(200) NOT NULL COMMENT '挂载点',
  `fileSystem` VARCHAR(50) NOT NULL COMMENT '文件系统类型',
  `totalSpace` BIGINT NOT NULL DEFAULT 0 COMMENT '总大小(字节)',
  `usedSpace` BIGINT NOT NULL DEFAULT 0 COMMENT '已使用(字节)',
  `freeSpace` BIGINT NOT NULL DEFAULT 0 COMMENT '可用(字节)',
  `usagePercent` DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '使用率(0-100)',
  `inodesTotal` BIGINT NOT NULL DEFAULT 0 COMMENT 'inode总数',
  `inodesUsed` BIGINT NOT NULL DEFAULT 0 COMMENT 'inode已使用',
  `inodesFree` BIGINT NOT NULL DEFAULT 0 COMMENT 'inode空闲',
  `inodesUsagePercent` DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT 'inode使用率(0-100)',
  `collectTime` DATETIME NOT NULL COMMENT '采集时间',
  `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `addWho` VARCHAR(32) NOT NULL COMMENT '创建人ID',
  `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `editWho` VARCHAR(32) NOT NULL COMMENT '最后修改人ID',
  `oprSeqFlag` VARCHAR(32) NOT NULL COMMENT '操作序列标识',
  `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
  `noteText` VARCHAR(500) DEFAULT NULL COMMENT '备注信息',
  `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
  `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
  `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
  `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
  `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
  `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
  `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
  `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
  `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
  `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
  `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
  PRIMARY KEY (`tenantId`, `metricDiskPartitionLogId`),
  KEY `IDX_METRIC_DISK_PART_SERVER` (`metricServerId`),
  KEY `IDX_METRIC_DISK_PART_TIME` (`collectTime`),
  KEY `IDX_METRIC_DISK_PART_DEVICE` (`deviceName`),
  KEY `IDX_METRIC_DISK_PART_USAGE` (`usagePercent`),
  KEY `IDX_METRIC_DISK_PART_ACTIVE` (`activeFlag`),
  KEY `IDX_METRIC_DISK_PART_SRV_TIME` (`metricServerId`, `collectTime`),
  KEY `IDX_METRIC_DISK_PART_SRV_DEV` (`metricServerId`, `deviceName`),
  KEY `IDX_METRIC_DISK_PART_TNT_TIME` (`tenantId`, `collectTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='磁盘分区采集日志表';
