CREATE TABLE `HUB_METRIC_MEMORY_LOG` (
  `metricMemoryLogId` VARCHAR(32) NOT NULL COMMENT '内存采集日志ID',
  `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
  `metricServerId` VARCHAR(32) NOT NULL COMMENT '关联服务器ID',
  `totalMemory` BIGINT NOT NULL DEFAULT 0 COMMENT '总内存(字节)',
  `availableMemory` BIGINT NOT NULL DEFAULT 0 COMMENT '可用内存(字节)',
  `usedMemory` BIGINT NOT NULL DEFAULT 0 COMMENT '已使用内存(字节)',
  `usagePercent` DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '内存使用率(0-100)',
  `freeMemory` BIGINT NOT NULL DEFAULT 0 COMMENT '空闲内存(字节)',
  `cachedMemory` BIGINT NOT NULL DEFAULT 0 COMMENT '缓存内存(字节)',
  `buffersMemory` BIGINT NOT NULL DEFAULT 0 COMMENT '缓冲区内存(字节)',
  `sharedMemory` BIGINT NOT NULL DEFAULT 0 COMMENT '共享内存(字节)',
  `swapTotal` BIGINT NOT NULL DEFAULT 0 COMMENT '交换区总大小(字节)',
  `swapUsed` BIGINT NOT NULL DEFAULT 0 COMMENT '交换区已使用(字节)',
  `swapFree` BIGINT NOT NULL DEFAULT 0 COMMENT '交换区空闲(字节)',
  `swapUsagePercent` DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '交换区使用率(0-100)',
  `collectTime` DATETIME NOT NULL COMMENT '采集时间',
  `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `addWho` VARCHAR(32) NOT NULL COMMENT '创建人ID',
  `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `editWho` VARCHAR(32) NOT NULL COMMENT '最后修改人ID',
  `oprSeqFlag` VARCHAR(32) NOT NULL COMMENT '操作序列标识',
  `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
  `noteText` VARCHAR(500) DEFAULT NULL COMMENT '备注信息',
  `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
  `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
  `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
  `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
  `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
  `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
  `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
  `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
  `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
  `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
  `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
  PRIMARY KEY (`tenantId`, `metricMemoryLogId`),
  KEY `IDX_METRIC_MEMORY_SERVER` (`metricServerId`),
  KEY `IDX_METRIC_MEMORY_TIME` (`collectTime`),
  KEY `IDX_METRIC_MEMORY_USAGE` (`usagePercent`),
  KEY `IDX_METRIC_MEMORY_ACTIVE` (`activeFlag`),
  KEY `IDX_METRIC_MEMORY_SRV_TIME` (`metricServerId`, `collectTime`),
  KEY `IDX_METRIC_MEMORY_TNT_TIME` (`tenantId`, `collectTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内存采集日志表';
