CREATE TABLE `HUB_CLUSTER_NODE` (
  `nodeId` VARCHAR(64) NOT NULL COMMENT '节点ID，与 GetNodeId()、采集表 metricServerId 相同',
  `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
  `nodeIp` VARCHAR(100) DEFAULT NULL COMMENT '节点IP，供后续网络拓扑检查',
  `hostname` VARCHAR(255) DEFAULT NULL COMMENT '主机名',
  `startedTime` DATETIME NOT NULL COMMENT '本进程启动时间',
  `lastSeenTime` DATETIME NOT NULL COMMENT '最后心跳时间',
  `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `addWho` VARCHAR(64) NOT NULL COMMENT '创建人ID',
  `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `editWho` VARCHAR(64) NOT NULL COMMENT '最后修改人ID',
  `oprSeqFlag` VARCHAR(64) NOT NULL COMMENT '操作序列标识',
  `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
  `noteText` TEXT DEFAULT NULL COMMENT '备注信息',
  `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性(JSON格式)',
  `reserved1` VARCHAR(64) DEFAULT NULL COMMENT '预留字段1',
  `reserved2` VARCHAR(64) DEFAULT NULL COMMENT '预留字段2',
  `reserved3` VARCHAR(100) DEFAULT NULL COMMENT '预留字段3',
  `reserved4` VARCHAR(100) DEFAULT NULL COMMENT '预留字段4',
  `reserved5` VARCHAR(255) DEFAULT NULL COMMENT '预留字段5',
  PRIMARY KEY (`tenantId`, `nodeId`),
  KEY `IDX_CLS_NODE_SEEN` (`tenantId`, `lastSeenTime`)
) ENGINE=InnoDB COMMENT='集群节点表 - 进程登记自身，供成员名单与后续网络拓扑检查';
