CREATE TABLE `HUB_TUNNEL_SERVICE` (
                                      `tunnelServiceId` VARCHAR(32) NOT NULL COMMENT '隧道服务ID，主键',
                                      `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
                                      `tunnelClientId` VARCHAR(32) NOT NULL COMMENT '隧道客户端ID，关联HUB_TUNNEL_CLIENT',
                                      `userId` VARCHAR(32) NOT NULL COMMENT '用户ID，关联外部用户系统',
                                      `serviceName` VARCHAR(100) NOT NULL COMMENT '服务名称',
                                      `serviceDescription` VARCHAR(500) DEFAULT NULL COMMENT '服务描述',
                                      `serviceType` VARCHAR(20) NOT NULL COMMENT '服务类型(tcp,udp,http,https,stcp,sudp,xtcp)',
                                      `localAddress` VARCHAR(50) NOT NULL DEFAULT '127.0.0.1' COMMENT '本地地址',
                                      `localPort` INT NOT NULL COMMENT '本地端口',
                                      `remotePort` INT DEFAULT NULL COMMENT '远程端口（服务端分配）',
                                      `customDomains` TEXT DEFAULT NULL COMMENT '自定义域名列表，JSON格式',
                                      `subDomain` VARCHAR(100) DEFAULT NULL COMMENT '子域名前缀',
                                      `httpUser` VARCHAR(50) DEFAULT NULL COMMENT 'HTTP基础认证用户名',
                                      `httpPassword` VARCHAR(100) DEFAULT NULL COMMENT 'HTTP基础认证密码',
                                      `hostHeaderRewrite` VARCHAR(255) DEFAULT NULL COMMENT '重写Host头',
                                      `headers` TEXT DEFAULT NULL COMMENT '自定义HTTP头，JSON格式',
                                      `locations` TEXT DEFAULT NULL COMMENT 'HTTP路径配置，JSON格式',
                                      `useEncryption` VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '使用加密(N禁用,Y启用)',
                                      `useCompression` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '使用压缩(N禁用,Y启用)',
                                      `secretKey` VARCHAR(100) DEFAULT NULL COMMENT '加密密钥',
                                      `bandwidthLimit` VARCHAR(20) DEFAULT NULL COMMENT '带宽限制',
                                      `maxConnections` INT DEFAULT 100 COMMENT '最大连接数限制',
                                      `healthCheckType` VARCHAR(20) DEFAULT NULL COMMENT '健康检查类型(tcp,http)',
                                      `healthCheckUrl` VARCHAR(255) DEFAULT NULL COMMENT '健康检查URL',
                                      `serviceStatus` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '服务状态(active,inactive,error,offline)',
                                      `registeredTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '服务注册时间',
                                      `lastActiveTime` DATETIME DEFAULT NULL COMMENT '最后活跃时间',
                                      `connectionCount` INT DEFAULT 0 COMMENT '当前连接数',
                                      `totalConnections` BIGINT DEFAULT 0 COMMENT '总连接数',
                                      `totalTraffic` BIGINT DEFAULT 0 COMMENT '总流量(字节)',
                                      `serviceConfig` TEXT DEFAULT NULL COMMENT '服务配置，JSON格式',
                                      `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                      `addWho` VARCHAR(32) NOT NULL COMMENT '创建人ID',
                                      `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
                                      `editWho` VARCHAR(32) NOT NULL COMMENT '最后修改人ID',
                                      `oprSeqFlag` VARCHAR(32) NOT NULL COMMENT '操作序列标识',
                                      `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
                                      `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
                                      `noteText` VARCHAR(500) DEFAULT NULL COMMENT '备注信息',
                                      `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
                                      `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
                                      `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
                                      `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
                                      `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
                                      `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
                                      `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
                                      `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
                                      `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
                                      `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
                                      `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
                                      CONSTRAINT `PK_TUNNEL_SERVICE` PRIMARY KEY (`tunnelServiceId`),
                                      UNIQUE KEY `IDX_TUNNEL_SVC_NAME` (`serviceName`),
                                      KEY `IDX_TUNNEL_SVC_TENANT` (`tenantId`),
                                      KEY `IDX_TUNNEL_SVC_CLIENT` (`tunnelClientId`),
                                      KEY `IDX_TUNNEL_SVC_USER` (`userId`),
                                      KEY `IDX_TUNNEL_SVC_TYPE` (`serviceType`),
                                      KEY `IDX_TUNNEL_SVC_STATUS` (`serviceStatus`),
                                      KEY `IDX_TUNNEL_SVC_PORT` (`remotePort`),
                                      KEY `IDX_TUNNEL_SVC_DOMAIN` (`subDomain`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='隧道服务配置表，管理客户端动态注册的服务配置';
