CREATE TABLE `HUB_METRIC_SERVER_INFO` (
  `metricServerId` VARCHAR(64) NOT NULL COMMENT '服务器ID',
  `tenantId` VARCHAR(64) NOT NULL COMMENT '租户ID',
  `hostname` VARCHAR(255) NOT NULL COMMENT '主机名',
  `osType` VARCHAR(100) NOT NULL COMMENT '操作系统类型',
  `osVersion` VARCHAR(255) NOT NULL COMMENT '操作系统版本',
  `kernelVersion` VARCHAR(255) DEFAULT NULL COMMENT '内核版本',
  `architecture` VARCHAR(100) NOT NULL COMMENT '系统架构',
  `bootTime` DATETIME NOT NULL COMMENT '系统启动时间',
  `ipAddress` VARCHAR(45) DEFAULT NULL COMMENT '主IP地址',
  `macAddress` VARCHAR(50) DEFAULT NULL COMMENT '主MAC地址',
  `serverLocation` VARCHAR(255) DEFAULT NULL COMMENT '服务器位置',
  `serverType` VARCHAR(50) DEFAULT NULL COMMENT '服务器类型(physical/virtual/unknown)',
  `lastUpdateTime` DATETIME NOT NULL COMMENT '最后更新时间',
  -- 新增网络信息字段
  `networkInfo` TEXT DEFAULT NULL COMMENT '网络信息详情，JSON格式存储所有IP和MAC地址',
  `systemInfo` TEXT DEFAULT NULL COMMENT '系统详细信息，JSON格式存储温度、负载等扩展信息',
  `hardwareInfo` TEXT DEFAULT NULL COMMENT '硬件信息，JSON格式存储CPU、内存、磁盘等硬件详情',
  -- 通用字段
  `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `addWho` VARCHAR(64) NOT NULL COMMENT '创建人ID',
  `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `editWho` VARCHAR(64) NOT NULL COMMENT '最后修改人ID',
  `oprSeqFlag` VARCHAR(64) NOT NULL COMMENT '操作序列标识',
  `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
  `noteText` TEXT DEFAULT NULL COMMENT '备注信息',
  `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
  `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
  `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
  `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
  `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
  `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
  `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
  `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
  `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
  `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
  `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
  PRIMARY KEY (`tenantId`, `metricServerId`),
  UNIQUE KEY `IDX_METRIC_SERVER_HOST` (`hostname`),
  KEY `IDX_METRIC_SERVER_OS` (`osType`),
  KEY `IDX_METRIC_SERVER_IP` (`ipAddress`),
  KEY `IDX_METRIC_SERVER_TYPE` (`serverType`),
  KEY `IDX_METRIC_SERVER_ACTIVE` (`activeFlag`),
  KEY `IDX_METRIC_SERVER_UPDATE` (`lastUpdateTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务器信息主表';

-- 兼容历史项目：删除hostname唯一索引
ALTER TABLE HUB_METRIC_SERVER_INFO DROP INDEX IDX_METRIC_SERVER_HOST;
