CREATE TABLE `HUB_METRIC_TEMP_LOG` (
  `metricTemperatureLogId` VARCHAR(32) NOT NULL COMMENT '温度信息日志ID',
  `tenantId` VARCHAR(32) NOT NULL COMMENT '租户ID',
  `metricServerId` VARCHAR(32) NOT NULL COMMENT '关联服务器ID',
  `sensorName` VARCHAR(100) NOT NULL COMMENT '传感器名称',
  `temperatureValue` DECIMAL(6,2) NOT NULL DEFAULT 0.00 COMMENT '温度值(摄氏度)',
  `highThreshold` DECIMAL(6,2) DEFAULT NULL COMMENT '高温阈值',
  `criticalThreshold` DECIMAL(6,2) DEFAULT NULL COMMENT '严重高温阈值',
  `collectTime` DATETIME NOT NULL COMMENT '采集时间',
  `addTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `addWho` VARCHAR(32) NOT NULL COMMENT '创建人ID',
  `editTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `editWho` VARCHAR(32) NOT NULL COMMENT '最后修改人ID',
  `oprSeqFlag` VARCHAR(32) NOT NULL COMMENT '操作序列标识',
  `currentVersion` INT NOT NULL DEFAULT 1 COMMENT '当前版本号',
  `activeFlag` VARCHAR(1) NOT NULL DEFAULT 'Y' COMMENT '活动状态标记(N非活动,Y活动)',
  `noteText` VARCHAR(500) DEFAULT NULL COMMENT '备注信息',
  `extProperty` TEXT DEFAULT NULL COMMENT '扩展属性，JSON格式',
  `reserved1` VARCHAR(500) DEFAULT NULL COMMENT '预留字段1',
  `reserved2` VARCHAR(500) DEFAULT NULL COMMENT '预留字段2',
  `reserved3` VARCHAR(500) DEFAULT NULL COMMENT '预留字段3',
  `reserved4` VARCHAR(500) DEFAULT NULL COMMENT '预留字段4',
  `reserved5` VARCHAR(500) DEFAULT NULL COMMENT '预留字段5',
  `reserved6` VARCHAR(500) DEFAULT NULL COMMENT '预留字段6',
  `reserved7` VARCHAR(500) DEFAULT NULL COMMENT '预留字段7',
  `reserved8` VARCHAR(500) DEFAULT NULL COMMENT '预留字段8',
  `reserved9` VARCHAR(500) DEFAULT NULL COMMENT '预留字段9',
  `reserved10` VARCHAR(500) DEFAULT NULL COMMENT '预留字段10',
  PRIMARY KEY (`tenantId`, `metricTemperatureLogId`),
  KEY `IDX_METRIC_TEMP_SERVER` (`metricServerId`),
  KEY `IDX_METRIC_TEMP_TIME` (`collectTime`),
  KEY `IDX_METRIC_TEMP_SENSOR` (`sensorName`),
  KEY `IDX_METRIC_TEMP_ACTIVE` (`activeFlag`),
  KEY `IDX_METRIC_TEMP_SRV_TIME` (`metricServerId`, `collectTime`),
  KEY `IDX_METRIC_TEMP_SRV_SENSOR` (`metricServerId`, `sensorName`),
  KEY `IDX_METRIC_TEMP_TNT_TIME` (`tenantId`, `collectTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='温度信息采集日志表';

