CREATE TABLE HUB_LOGIN_LOG (
    logId           VARCHAR(32)   NOT NULL COMMENT '日志ID，主键',
    userId          VARCHAR(32)   NOT NULL COMMENT '用户ID',
    tenantId        VARCHAR(32)   NOT NULL COMMENT '租户ID',
    userName        VARCHAR(50)   NOT NULL COMMENT '用户名',
    loginTime       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
    loginIp         VARCHAR(128)  NOT NULL COMMENT '登录IP',
    loginLocation   VARCHAR(255)  NULL     COMMENT '登录地点',
    loginType       INT           NOT NULL DEFAULT 1 COMMENT '登录类型：1-用户名密码，2-验证码，3-第三方',
    deviceType      VARCHAR(50)   NULL     COMMENT '设备类型',
    deviceInfo      TEXT          NULL     COMMENT '设备信息',
    browserInfo     TEXT          NULL     COMMENT '浏览器信息',
    osInfo          VARCHAR(255)  NULL     COMMENT '操作系统信息',
    loginStatus     VARCHAR(1)    NOT NULL DEFAULT 'N' COMMENT '登录状态：Y-成功，N-失败',
    logoutTime      DATETIME      NULL     COMMENT '登出时间',
    sessionDuration INT           NULL     COMMENT '会话持续时长(秒)',
    failReason      TEXT          NULL     COMMENT '失败原因',
    addTime         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    addWho          VARCHAR(32)   NOT NULL COMMENT '创建人',
    editTime        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    editWho         VARCHAR(32)   NOT NULL COMMENT '修改人',
    oprSeqFlag      VARCHAR(32)   NOT NULL COMMENT '操作序列标识',
    currentVersion  INT           NOT NULL DEFAULT 1 COMMENT '当前版本号',
    activeFlag      VARCHAR(1)    NOT NULL DEFAULT 'Y' COMMENT '活动状态标记：Y-活动，N-非活动',
    PRIMARY KEY (logId),
    INDEX IDX_LOGIN_USER (userId),
    INDEX IDX_LOGIN_TIME (loginTime),
    INDEX IDX_LOGIN_TENANT (tenantId),
    INDEX IDX_LOGIN_STATUS (loginStatus),
    INDEX IDX_LOGIN_TYPE (loginType)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户登录日志表';
