CREATE TABLE HUB_TUNNEL_CLIENT (
  tunnelClientId VARCHAR2(32) NOT NULL,
  tenantId VARCHAR2(32) NOT NULL,
  userId VARCHAR2(32) NOT NULL,
  clientName VARCHAR2(100) NOT NULL,
  clientDescription VARCHAR2(500),
  clientVersion VARCHAR2(20),
  operatingSystem VARCHAR2(50),
  clientIpAddress VARCHAR2(50),
  clientMacAddress VARCHAR2(20),
  serverAddress VARCHAR2(100) NOT NULL,
  serverPort NUMBER(10) DEFAULT 7000 NOT NULL,
  authToken VARCHAR2(100) NOT NULL,
  tlsEnable VARCHAR2(1) DEFAULT 'N' NOT NULL,
  autoReconnect VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  maxRetries NUMBER(10) DEFAULT 5 NOT NULL,
  retryInterval NUMBER(10) DEFAULT 20 NOT NULL,
  heartbeatInterval NUMBER(10) DEFAULT 30 NOT NULL,
  heartbeatTimeout NUMBER(10) DEFAULT 90 NOT NULL,
  connectionStatus VARCHAR2(20) DEFAULT 'disconnected' NOT NULL,
  lastConnectTime TIMESTAMP,
  lastDisconnectTime TIMESTAMP,
  totalConnectTime NUMBER(19) DEFAULT 0,
  reconnectCount NUMBER(10) DEFAULT 0,
  serviceCount NUMBER(10) DEFAULT 0,
  lastHeartbeat TIMESTAMP,
  clientConfig CLOB,
  addTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  addWho VARCHAR2(32) NOT NULL,
  editTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  editWho VARCHAR2(32) NOT NULL,
  oprSeqFlag VARCHAR2(32) NOT NULL,
  currentVersion NUMBER(10) DEFAULT 1 NOT NULL,
  activeFlag VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  noteText VARCHAR2(500),
  extProperty CLOB,
  reserved1 VARCHAR2(500),
  reserved2 VARCHAR2(500),
  reserved3 VARCHAR2(500),
  reserved4 VARCHAR2(500),
  reserved5 VARCHAR2(500),
  reserved6 VARCHAR2(500),
  reserved7 VARCHAR2(500),
  reserved8 VARCHAR2(500),
  reserved9 VARCHAR2(500),
  reserved10 VARCHAR2(500),
  CONSTRAINT PK_TUNNEL_CLIENT PRIMARY KEY (tunnelClientId),
  CONSTRAINT UK_TUNNEL_CLIENT_NAME UNIQUE (clientName)
);

CREATE INDEX IDX_TUNNEL_CLIENT_TENANT ON HUB_TUNNEL_CLIENT(tenantId);
CREATE INDEX IDX_TUNNEL_CLIENT_USER ON HUB_TUNNEL_CLIENT(userId);
CREATE INDEX IDX_TUNNEL_CLIENT_STATUS ON HUB_TUNNEL_CLIENT(connectionStatus);
CREATE INDEX IDX_TUNNEL_CLIENT_IP ON HUB_TUNNEL_CLIENT(clientIpAddress);
CREATE INDEX IDX_TUNNEL_CLIENT_HB ON HUB_TUNNEL_CLIENT(lastHeartbeat);

COMMENT ON TABLE HUB_TUNNEL_CLIENT IS '隧道客户端表，管理客户端连接认证和状态跟踪';
