CREATE TABLE HUB_TUNNEL_SERVICE (
  tunnelServiceId VARCHAR2(32) NOT NULL,
  tenantId VARCHAR2(32) NOT NULL,
  tunnelClientId VARCHAR2(32) NOT NULL,
  userId VARCHAR2(32) NOT NULL,
  serviceName VARCHAR2(100) NOT NULL,
  serviceDescription VARCHAR2(500),
  serviceType VARCHAR2(20) NOT NULL,
  localAddress VARCHAR2(50) DEFAULT '127.0.0.1' NOT NULL,
  localPort NUMBER(10) NOT NULL,
  remotePort NUMBER(10),
  customDomains CLOB,
  subDomain VARCHAR2(100),
  httpUser VARCHAR2(50),
  httpPassword VARCHAR2(100),
  hostHeaderRewrite VARCHAR2(255),
  headers CLOB,
  locations CLOB,
  useEncryption VARCHAR2(1) DEFAULT 'N' NOT NULL,
  useCompression VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  secretKey VARCHAR2(100),
  bandwidthLimit VARCHAR2(20),
  maxConnections NUMBER(10) DEFAULT 100,
  healthCheckType VARCHAR2(20),
  healthCheckUrl VARCHAR2(255),
  serviceStatus VARCHAR2(20) DEFAULT 'active' NOT NULL,
  registeredTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  lastActiveTime TIMESTAMP,
  connectionCount NUMBER(10) DEFAULT 0,
  totalConnections NUMBER(19) DEFAULT 0,
  totalTraffic NUMBER(19) DEFAULT 0,
  serviceConfig CLOB,
  addTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  addWho VARCHAR2(32) NOT NULL,
  editTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  editWho VARCHAR2(32) NOT NULL,
  oprSeqFlag VARCHAR2(32) NOT NULL,
  currentVersion NUMBER(10) DEFAULT 1 NOT NULL,
  activeFlag VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  noteText VARCHAR2(500),
  extProperty CLOB,
  reserved1 VARCHAR2(500),
  reserved2 VARCHAR2(500),
  reserved3 VARCHAR2(500),
  reserved4 VARCHAR2(500),
  reserved5 VARCHAR2(500),
  reserved6 VARCHAR2(500),
  reserved7 VARCHAR2(500),
  reserved8 VARCHAR2(500),
  reserved9 VARCHAR2(500),
  reserved10 VARCHAR2(500),
  CONSTRAINT PK_TUNNEL_SERVICE PRIMARY KEY (tunnelServiceId),
  CONSTRAINT UK_TUNNEL_SVC_NAME UNIQUE (serviceName)
);

CREATE INDEX IDX_TUNNEL_SVC_TENANT ON HUB_TUNNEL_SERVICE(tenantId);
CREATE INDEX IDX_TUNNEL_SVC_CLIENT ON HUB_TUNNEL_SERVICE(tunnelClientId);
CREATE INDEX IDX_TUNNEL_SVC_USER ON HUB_TUNNEL_SERVICE(userId);
CREATE INDEX IDX_TUNNEL_SVC_TYPE ON HUB_TUNNEL_SERVICE(serviceType);
CREATE INDEX IDX_TUNNEL_SVC_STATUS ON HUB_TUNNEL_SERVICE(serviceStatus);
CREATE INDEX IDX_TUNNEL_SVC_PORT ON HUB_TUNNEL_SERVICE(remotePort);
CREATE INDEX IDX_TUNNEL_SVC_DOMAIN ON HUB_TUNNEL_SERVICE(subDomain);

COMMENT ON TABLE HUB_TUNNEL_SERVICE IS '隧道服务配置表，管理客户端动态注册的服务配置';

