-- 服务中心 API Token（Bearer 不透明令牌）
CREATE TABLE HUB_SERVICE_AUTH_TOKEN (
    tokenId VARCHAR2(64) NOT NULL,
    tenantId VARCHAR2(32) NOT NULL,
    tokenValue VARCHAR2(256) NOT NULL,
    userId VARCHAR2(64) NOT NULL,
    tokenName VARCHAR2(128),
    expireTime DATE,
    statusFlag CHAR(1) DEFAULT 'Y' NOT NULL,
    addTime DATE DEFAULT SYSDATE NOT NULL,
    addWho VARCHAR2(64) NOT NULL,
    editTime DATE DEFAULT SYSDATE NOT NULL,
    editWho VARCHAR2(64) NOT NULL,
    oprSeqFlag VARCHAR2(64) NOT NULL,
    currentVersion NUMBER(10) DEFAULT 1 NOT NULL,
    activeFlag CHAR(1) DEFAULT 'Y' NOT NULL,
    noteText VARCHAR2(512),
    extProperty CLOB,
    CONSTRAINT PK_HUB_SERVICE_AUTH_TOKEN PRIMARY KEY (tenantId, tokenId)
);

CREATE UNIQUE INDEX UK_SC_AUTH_TOKEN_VALUE ON HUB_SERVICE_AUTH_TOKEN(tokenValue);
CREATE INDEX IDX_SC_AUTH_TOKEN_USER ON HUB_SERVICE_AUTH_TOKEN(userId);
