CREATE TABLE HUB_RETENTION_LEASE (
    tenantId VARCHAR2(32) NOT NULL,
    leaseKey VARCHAR2(64) NOT NULL,
    owner VARCHAR2(128) NOT NULL,
    expireTime DATE NOT NULL,
    addTime DATE DEFAULT SYSDATE NOT NULL,
    addWho VARCHAR2(64) NOT NULL,
    editTime DATE DEFAULT SYSDATE NOT NULL,
    editWho VARCHAR2(64) NOT NULL,
    oprSeqFlag VARCHAR2(64) NOT NULL,
    currentVersion NUMBER(10) DEFAULT 1 NOT NULL,
    activeFlag VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    noteText CLOB,
    extProperty CLOB,
    CONSTRAINT PK_RETENTION_LEASE PRIMARY KEY (tenantId, leaseKey)
);
COMMENT ON TABLE HUB_RETENTION_LEASE IS '生命周期清理租约，保证集群内同一时刻只有一个节点执行清理';
COMMENT ON COLUMN HUB_RETENTION_LEASE.tenantId IS '租户ID，集群级租约固定 default';
COMMENT ON COLUMN HUB_RETENTION_LEASE.leaseKey IS '租约键，当前仅 cleanup';
COMMENT ON COLUMN HUB_RETENTION_LEASE.owner IS '持有节点ID';
COMMENT ON COLUMN HUB_RETENTION_LEASE.expireTime IS '租约过期时间';
