CREATE TABLE HUB_TUNNEL_SERVER (
  tunnelServerId VARCHAR2(32) NOT NULL,
  tenantId VARCHAR2(32) NOT NULL,
  serverName VARCHAR2(100) NOT NULL,
  serverDescription VARCHAR2(500),
  controlAddress VARCHAR2(50) DEFAULT '0.0.0.0' NOT NULL,
  controlPort NUMBER(10) DEFAULT 7000 NOT NULL,
  dashboardPort NUMBER(10) DEFAULT 7500,
  vhostHttpPort NUMBER(10) DEFAULT 80,
  vhostHttpsPort NUMBER(10) DEFAULT 443,
  maxClients NUMBER(10) DEFAULT 1000 NOT NULL,
  tokenAuth VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  authToken VARCHAR2(100),
  tlsEnable VARCHAR2(1) DEFAULT 'N' NOT NULL,
  tlsCertFile VARCHAR2(255),
  tlsKeyFile VARCHAR2(255),
  heartbeatInterval NUMBER(10) DEFAULT 30 NOT NULL,
  heartbeatTimeout NUMBER(10) DEFAULT 90 NOT NULL,
  logLevel VARCHAR2(10) DEFAULT 'info' NOT NULL,
  maxPortsPerClient NUMBER(10) DEFAULT 10,
  allowPorts CLOB,
  serverStatus VARCHAR2(20) DEFAULT 'stopped' NOT NULL,
  startTime TIMESTAMP,
  configVersion VARCHAR2(32),
  addTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  addWho VARCHAR2(32) NOT NULL,
  editTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  editWho VARCHAR2(32) NOT NULL,
  oprSeqFlag VARCHAR2(32) NOT NULL,
  currentVersion NUMBER(10) DEFAULT 1 NOT NULL,
  activeFlag VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  noteText VARCHAR2(500),
  extProperty CLOB,
  reserved1 VARCHAR2(500),
  reserved2 VARCHAR2(500),
  reserved3 VARCHAR2(500),
  reserved4 VARCHAR2(500),
  reserved5 VARCHAR2(500),
  reserved6 VARCHAR2(500),
  reserved7 VARCHAR2(500),
  reserved8 VARCHAR2(500),
  reserved9 VARCHAR2(500),
  reserved10 VARCHAR2(500),
  CONSTRAINT PK_TUNNEL_SERVER PRIMARY KEY (tunnelServerId),
  CONSTRAINT UK_TUNNEL_SVR_NAME UNIQUE (serverName)
);

CREATE INDEX IDX_TUNNEL_SVR_TENANT ON HUB_TUNNEL_SERVER(tenantId);
CREATE INDEX IDX_TUNNEL_SVR_CTRL ON HUB_TUNNEL_SERVER(controlAddress, controlPort);
CREATE INDEX IDX_TUNNEL_SVR_STATUS ON HUB_TUNNEL_SERVER(serverStatus);

COMMENT ON TABLE HUB_TUNNEL_SERVER IS '隧道服务器配置表，管理控制端口和核心配置';
