CREATE TABLE HUB_TUNNEL_SERVER_NODE (
  serverNodeId VARCHAR2(32) NOT NULL,
  tenantId VARCHAR2(32) NOT NULL,
  tunnelServerId VARCHAR2(32) NOT NULL,
  nodeName VARCHAR2(100) NOT NULL,
  nodeType VARCHAR2(20) DEFAULT 'static' NOT NULL,
  proxyType VARCHAR2(20) NOT NULL,
  listenAddress VARCHAR2(50) DEFAULT '0.0.0.0' NOT NULL,
  listenPort NUMBER(10) NOT NULL,
  targetAddress VARCHAR2(50) NOT NULL,
  targetPort NUMBER(10) NOT NULL,
  customDomains CLOB,
  subDomain VARCHAR2(100),
  httpUser VARCHAR2(50),
  httpPassword VARCHAR2(100),
  hostHeaderRewrite VARCHAR2(255),
  headers CLOB,
  locations CLOB,
  compression VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  encryption VARCHAR2(1) DEFAULT 'N' NOT NULL,
  secretKey VARCHAR2(100),
  healthCheckType VARCHAR2(20) DEFAULT 'tcp',
  healthCheckUrl VARCHAR2(255),
  healthCheckInterval NUMBER(10) DEFAULT 60,
  maxConnections NUMBER(10) DEFAULT 100,
  nodeStatus VARCHAR2(20) DEFAULT 'active' NOT NULL,
  lastHealthCheck TIMESTAMP,
  connectionCount NUMBER(10) DEFAULT 0,
  totalConnections NUMBER(19) DEFAULT 0,
  totalBytes NUMBER(19) DEFAULT 0,
  createdTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  addTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  addWho VARCHAR2(32) NOT NULL,
  editTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  editWho VARCHAR2(32) NOT NULL,
  oprSeqFlag VARCHAR2(32) NOT NULL,
  currentVersion NUMBER(10) DEFAULT 1 NOT NULL,
  activeFlag VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  noteText VARCHAR2(500),
  extProperty CLOB,
  reserved1 VARCHAR2(500),
  reserved2 VARCHAR2(500),
  reserved3 VARCHAR2(500),
  reserved4 VARCHAR2(500),
  reserved5 VARCHAR2(500),
  reserved6 VARCHAR2(500),
  reserved7 VARCHAR2(500),
  reserved8 VARCHAR2(500),
  reserved9 VARCHAR2(500),
  reserved10 VARCHAR2(500),
  CONSTRAINT PK_TUNNEL_SVR_NODE PRIMARY KEY (serverNodeId),
  CONSTRAINT UK_TUNNEL_NODE_NAME UNIQUE (nodeName),
  CONSTRAINT UK_TUNNEL_NODE_PORT UNIQUE (listenAddress, listenPort, proxyType)
);

CREATE INDEX IDX_TUNNEL_NODE_TENANT ON HUB_TUNNEL_SERVER_NODE(tenantId);
CREATE INDEX IDX_TUNNEL_NODE_SERVER ON HUB_TUNNEL_SERVER_NODE(tunnelServerId);
CREATE INDEX IDX_TUNNEL_NODE_TYPE ON HUB_TUNNEL_SERVER_NODE(nodeType, proxyType);
CREATE INDEX IDX_TUNNEL_NODE_STATUS ON HUB_TUNNEL_SERVER_NODE(nodeStatus);
CREATE INDEX IDX_TUNNEL_NODE_HEALTH ON HUB_TUNNEL_SERVER_NODE(lastHealthCheck);

COMMENT ON TABLE HUB_TUNNEL_SERVER_NODE IS '隧道服务器节点表，管理静态端口映射和数据端口转发';
