CREATE TABLE HUB_TUNNEL_STATIC_NODE (
  tunnelStaticNodeId VARCHAR2(32) NOT NULL,
  tenantId VARCHAR2(32) NOT NULL,
  tunnelStaticServerId VARCHAR2(32) NOT NULL,
  nodeName VARCHAR2(100) NOT NULL,
  nodeDescription VARCHAR2(500),
  targetAddress VARCHAR2(50) NOT NULL,
  targetPort NUMBER(10) NOT NULL,
  proxyType VARCHAR2(20) DEFAULT 'tcp' NOT NULL,
  maxConnections NUMBER(10) DEFAULT 100,
  connectionTimeout NUMBER(10) DEFAULT 30,
  readTimeout NUMBER(10) DEFAULT 30,
  writeTimeout NUMBER(10) DEFAULT 30,
  retryCount NUMBER(10) DEFAULT 3,
  retryInterval NUMBER(10) DEFAULT 5,
  compression VARCHAR2(1) DEFAULT 'N' NOT NULL,
  encryption VARCHAR2(1) DEFAULT 'N' NOT NULL,
  secretKey VARCHAR2(100),
  customHeaders CLOB,
  nodeStatus VARCHAR2(20) DEFAULT 'active' NOT NULL,
  lastHealthCheck TIMESTAMP,
  healthCheckStatus VARCHAR2(20) DEFAULT 'unknown',
  currentConnectionCount NUMBER(10) DEFAULT 0,
  totalConnectionCount NUMBER(19) DEFAULT 0,
  totalBytesReceived NUMBER(19) DEFAULT 0,
  totalBytesSent NUMBER(19) DEFAULT 0,
  failureCount NUMBER(10) DEFAULT 0,
  lastFailureTime TIMESTAMP,
  nodeConfig CLOB,
  addTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  addWho VARCHAR2(32) NOT NULL,
  editTime TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  editWho VARCHAR2(32) NOT NULL,
  oprSeqFlag VARCHAR2(32) NOT NULL,
  currentVersion NUMBER(10) DEFAULT 1 NOT NULL,
  activeFlag VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  noteText VARCHAR2(500),
  extProperty CLOB,
  reserved1 VARCHAR2(500),
  reserved2 VARCHAR2(500),
  reserved3 VARCHAR2(500),
  reserved4 VARCHAR2(500),
  reserved5 VARCHAR2(500),
  reserved6 VARCHAR2(500),
  reserved7 VARCHAR2(500),
  reserved8 VARCHAR2(500),
  reserved9 VARCHAR2(500),
  reserved10 VARCHAR2(500),
  CONSTRAINT PK_TUNNEL_STATIC_NODE PRIMARY KEY (tunnelStaticNodeId),
  CONSTRAINT UK_TUNNEL_STATIC_NODE_NAME UNIQUE (nodeName),
  CONSTRAINT UK_TUNNEL_STATIC_NODE_TARGET UNIQUE (tunnelStaticServerId, targetAddress, targetPort)
);

CREATE INDEX IDX_TUNNEL_STATIC_NODE_TENANT ON HUB_TUNNEL_STATIC_NODE(tenantId);
CREATE INDEX IDX_TUNNEL_STATIC_NODE_SERVER ON HUB_TUNNEL_STATIC_NODE(tunnelStaticServerId);
CREATE INDEX IDX_TUNNEL_STATIC_NODE_TYPE ON HUB_TUNNEL_STATIC_NODE(proxyType);
CREATE INDEX IDX_TUNNEL_STATIC_NODE_STATUS ON HUB_TUNNEL_STATIC_NODE(nodeStatus);
CREATE INDEX IDX_TUNNEL_STATIC_NODE_HEALTH ON HUB_TUNNEL_STATIC_NODE(healthCheckStatus, lastHealthCheck);

COMMENT ON TABLE HUB_TUNNEL_STATIC_NODE IS '静态隧道节点表，管理静态隧道转发后端节点配置';

