-- 配置历史表 - 记录配置的变更历史，支持配置回滚和审计
CREATE TABLE HUB_SERVICE_CONFIG_HISTORY (
  -- 主键和租户信息
  configHistoryId VARCHAR2(32) NOT NULL,
  tenantId VARCHAR2(32) NOT NULL,
  
  -- 关联配置数据
  configDataId VARCHAR2(100) NOT NULL,
  namespaceId VARCHAR2(32) NOT NULL,
  groupName VARCHAR2(64) NOT NULL,
  
  -- 变更信息
  changeType VARCHAR2(20) NOT NULL,
  oldContent CLOB,
  newContent CLOB NOT NULL,
  oldVersion NUMBER(19),
  newVersion NUMBER(19) NOT NULL,
  oldMd5Value VARCHAR2(32),
  newMd5Value VARCHAR2(32) NOT NULL,
  
  -- 变更原因和操作人
  changeReason VARCHAR2(500),
  changedBy VARCHAR2(32) NOT NULL,
  changedAt DATE DEFAULT SYSDATE NOT NULL,
  
  -- 通用字段
  addTime DATE DEFAULT SYSDATE NOT NULL,
  addWho VARCHAR2(32) NOT NULL,
  editTime DATE DEFAULT SYSDATE NOT NULL,
  editWho VARCHAR2(32) NOT NULL,
  oprSeqFlag VARCHAR2(32) NOT NULL,
  currentVersion NUMBER(10) DEFAULT 1 NOT NULL,
  activeFlag VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  noteText VARCHAR2(500),
  extProperty CLOB,
  
  CONSTRAINT PK_SVC_CFG_HIST PRIMARY KEY (tenantId, configHistoryId)
);

CREATE INDEX IDX_SVC_CFG_HIST_DATA_ID ON HUB_SERVICE_CONFIG_HISTORY(tenantId, configDataId);
CREATE INDEX IDX_SVC_CFG_HIST_NS_ID ON HUB_SERVICE_CONFIG_HISTORY(tenantId, namespaceId);
CREATE INDEX IDX_SVC_CFG_HIST_GROUP_NAME ON HUB_SERVICE_CONFIG_HISTORY(tenantId, namespaceId, groupName);
CREATE INDEX IDX_SVC_CFG_HIST_TYPE ON HUB_SERVICE_CONFIG_HISTORY(changeType);
CREATE INDEX IDX_SVC_CFG_HIST_TIME ON HUB_SERVICE_CONFIG_HISTORY(changedAt);
CREATE INDEX IDX_SVC_CFG_HIST_BY ON HUB_SERVICE_CONFIG_HISTORY(changedBy);
CREATE INDEX IDX_SVC_CFG_HIST_VERSION ON HUB_SERVICE_CONFIG_HISTORY(newVersion);

COMMENT ON TABLE HUB_SERVICE_CONFIG_HISTORY IS '配置历史表 - 记录配置的变更历史，支持配置回滚和审计';

