-- 权限审计表 - 记录谁在哪个模块对哪条数据做了何种操作
-- =====================================================
-- 已建库补列：
-- ALTER TABLE HUB_AUTH_AUDIT_LOG ADD (moduleCode VARCHAR2(64), targetName VARCHAR2(255));
CREATE TABLE HUB_AUTH_AUDIT_LOG (
  auditId VARCHAR2(32) NOT NULL,
  tenantId VARCHAR2(32) NOT NULL,
  userId VARCHAR2(32) NOT NULL,
  userName VARCHAR2(100),

  action VARCHAR2(32) NOT NULL,
  moduleCode VARCHAR2(64),
  targetType VARCHAR2(32),
  targetId VARCHAR2(128),
  targetName VARCHAR2(255),
  resourceCode VARCHAR2(128),
  requestPath VARCHAR2(255),
  requestMethod VARCHAR2(16),
  clientIP VARCHAR2(128),
  result CHAR(1) DEFAULT 'Y' NOT NULL,
  detail CLOB,

  addTime DATE DEFAULT SYSDATE NOT NULL,
  addWho VARCHAR2(32) NOT NULL,
  editTime DATE DEFAULT SYSDATE NOT NULL,
  editWho VARCHAR2(32) NOT NULL,
  oprSeqFlag VARCHAR2(32) NOT NULL,
  currentVersion NUMBER(10) DEFAULT 1 NOT NULL,
  activeFlag CHAR(1) DEFAULT 'Y' NOT NULL,

  CONSTRAINT PK_AUTH_AUDIT_LOG PRIMARY KEY (auditId)
);

CREATE INDEX IDX_AUTH_AUDIT_TENANT ON HUB_AUTH_AUDIT_LOG(tenantId, addTime);
CREATE INDEX IDX_AUTH_AUDIT_USER ON HUB_AUTH_AUDIT_LOG(userId, addTime);
CREATE INDEX IDX_AUTH_AUDIT_ACTION ON HUB_AUTH_AUDIT_LOG(action);
CREATE INDEX IDX_AUTH_AUDIT_MODULE ON HUB_AUTH_AUDIT_LOG(tenantId, moduleCode, addTime);
COMMENT ON TABLE HUB_AUTH_AUDIT_LOG IS '权限审计表 - 记录谁在哪个模块对哪条数据做了何种操作';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.auditId IS '审计ID，主键';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.tenantId IS '租户ID';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.userId IS '操作人用户ID';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.userName IS '操作人用户名';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.action IS '动作细码：CREATE/UPDATE/DELETE/ROLLBACK/GRANT';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.moduleCode IS '模块编码，如 hub0021';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.targetType IS '目标类型(ROLE/USER/ROUTE/INSTANCE/API)';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.targetId IS '目标业务主键';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.targetName IS '目标显示名';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.resourceCode IS '权限资源编码';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.requestPath IS '请求路径';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.requestMethod IS 'HTTP方法';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.clientIP IS '客户端IP';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.result IS '结果：Y成功 N失败';
COMMENT ON COLUMN HUB_AUTH_AUDIT_LOG.detail IS '补充说明，JSON或摘要';
