// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"` // 业务错误码（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConfigData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,3,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=contentType,proto3" json:"contentType,omitempty"`      // JSON, YAML, PROPERTIES, XML, TEXT
	ConfigContent string                 `protobuf:"bytes,5,opt,name=configContent,proto3" json:"configContent,omitempty"`  // 配置内容
	ContentMd5    string                 `protobuf:"bytes,6,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`        // MD5校验（保存时可选，服务端自动计算；响应时返回）
	ConfigDesc    string                 `protobuf:"bytes,7,opt,name=configDesc,proto3" json:"configDesc,omitempty"`        // 配置描述
	ConfigVersion int64                  `protobuf:"varint,8,opt,name=configVersion,proto3" json:"configVersion,omitempty"` // 配置版本（保存时不传，服务端自动生成；响应时返回）
	ChangeType    string                 `protobuf:"bytes,9,opt,name=changeType,proto3" json:"changeType,omitempty"`        // ADD, UPDATE, DELETE
	ChangeReason  string                 `protobuf:"bytes,10,opt,name=changeReason,proto3" json:"changeReason,omitempty"`   // 变更原因
	ChangedBy     string                 `protobuf:"bytes,11,opt,name=changedBy,proto3" json:"changedBy,omitempty"`         // 变更人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigData) Reset() {
	*x = ConfigData{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigData) ProtoMessage() {}

func (x *ConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigData.ProtoReflect.Descriptor instead.
func (*ConfigData) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigData) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigData) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigData) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *ConfigData) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfigData) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *ConfigData) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

func (x *ConfigData) GetConfigDesc() string {
	if x != nil {
		return x.ConfigDesc
	}
	return ""
}

func (x *ConfigData) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ConfigData) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ConfigData) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

func (x *ConfigData) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

type ConfigHistory struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigHistoryId int64                  `protobuf:"varint,1,opt,name=configHistoryId,proto3" json:"configHistoryId,omitempty"`
	NamespaceId     string                 `protobuf:"bytes,2,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName       string                 `protobuf:"bytes,3,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId    string                 `protobuf:"bytes,4,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	ContentType     string                 `protobuf:"bytes,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	ConfigContent   string                 `protobuf:"bytes,6,opt,name=configContent,proto3" json:"configContent,omitempty"`
	ContentMd5      string                 `protobuf:"bytes,7,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`
	ConfigVersion   int64                  `protobuf:"varint,8,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	ChangeType      string                 `protobuf:"bytes,9,opt,name=changeType,proto3" json:"changeType,omitempty"`
	ChangeReason    string                 `protobuf:"bytes,10,opt,name=changeReason,proto3" json:"changeReason,omitempty"`
	ChangedBy       string                 `protobuf:"bytes,11,opt,name=changedBy,proto3" json:"changedBy,omitempty"`
	ChangeTime      string                 `protobuf:"bytes,12,opt,name=changeTime,proto3" json:"changeTime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigHistory) Reset() {
	*x = ConfigHistory{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigHistory) ProtoMessage() {}

func (x *ConfigHistory) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigHistory.ProtoReflect.Descriptor instead.
func (*ConfigHistory) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigHistory) GetConfigHistoryId() int64 {
	if x != nil {
		return x.ConfigHistoryId
	}
	return 0
}

func (x *ConfigHistory) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigHistory) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigHistory) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *ConfigHistory) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfigHistory) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *ConfigHistory) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

func (x *ConfigHistory) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ConfigHistory) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ConfigHistory) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

func (x *ConfigHistory) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *ConfigHistory) GetChangeTime() string {
	if x != nil {
		return x.ChangeTime
	}
	return ""
}

// 配置标识（用于查询、删除、监听）
type ConfigKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,3,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigKey) Reset() {
	*x = ConfigKey{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigKey) ProtoMessage() {}

func (x *ConfigKey) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigKey.ProtoReflect.Descriptor instead.
func (*ConfigKey) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigKey) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigKey) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigKey) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

// 获取配置响应
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Config        *ConfigData            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConfigResponse) GetConfig() *ConfigData {
	if x != nil {
		return x.Config
	}
	return nil
}

// 保存配置响应
type SaveConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`             // 业务错误码（可选）
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`      // 新版本号
	ContentMd5    string                 `protobuf:"bytes,5,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"` // 服务端计算的 MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfigResponse) Reset() {
	*x = SaveConfigResponse{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigResponse) ProtoMessage() {}

func (x *SaveConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigResponse.ProtoReflect.Descriptor instead.
func (*SaveConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *SaveConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveConfigResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SaveConfigResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SaveConfigResponse) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

// 列出配置响应
type ListConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Configs       []*ConfigData          `protobuf:"bytes,3,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsResponse) Reset() {
	*x = ListConfigsResponse{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsResponse) ProtoMessage() {}

func (x *ListConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigsResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *ListConfigsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListConfigsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListConfigsResponse) GetConfigs() []*ConfigData {
	if x != nil {
		return x.Configs
	}
	return nil
}

// 获取配置历史响应
type GetConfigHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	History       []*ConfigHistory       `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigHistoryResponse) Reset() {
	*x = GetConfigHistoryResponse{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigHistoryResponse) ProtoMessage() {}

func (x *GetConfigHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetConfigHistoryResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConfigHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConfigHistoryResponse) GetHistory() []*ConfigHistory {
	if x != nil {
		return x.History
	}
	return nil
}

// 回滚配置响应
type RollbackConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`              // 业务错误码（可选）
	NewVersion    int64                  `protobuf:"varint,4,opt,name=newVersion,proto3" json:"newVersion,omitempty"` // 回滚后的新版本号
	ContentMd5    string                 `protobuf:"bytes,5,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`  // 回滚后的 MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackConfigResponse) Reset() {
	*x = RollbackConfigResponse{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackConfigResponse) ProtoMessage() {}

func (x *RollbackConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackConfigResponse.ProtoReflect.Descriptor instead.
func (*RollbackConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *RollbackConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RollbackConfigResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RollbackConfigResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

func (x *RollbackConfigResponse) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

// 列出配置请求
type ListConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *ListConfigsRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ListConfigsRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

// 监听配置请求（统一接口，支持监听单个或多个配置）
// 用于数据库变动主动推送，只需要配置标识即可
type WatchConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataIds []string               `protobuf:"bytes,3,rep,name=configDataIds,proto3" json:"configDataIds,omitempty"` // 要监听的配置标识列表（支持单个或多个）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigRequest) Reset() {
	*x = WatchConfigRequest{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigRequest) ProtoMessage() {}

func (x *WatchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *WatchConfigRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *WatchConfigRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *WatchConfigRequest) GetConfigDataIds() []string {
	if x != nil {
		return x.ConfigDataIds
	}
	return nil
}

// 获取配置历史请求
type GetConfigHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,3,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // 限制返回数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigHistoryRequest) Reset() {
	*x = GetConfigHistoryRequest{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigHistoryRequest) ProtoMessage() {}

func (x *GetConfigHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetConfigHistoryRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfigHistoryRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *GetConfigHistoryRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GetConfigHistoryRequest) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *GetConfigHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 回滚配置请求
type RollbackConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string                 `protobuf:"bytes,3,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	TargetVersion int64                  `protobuf:"varint,4,opt,name=targetVersion,proto3" json:"targetVersion,omitempty"` // 目标版本
	ChangedBy     string                 `protobuf:"bytes,5,opt,name=changedBy,proto3" json:"changedBy,omitempty"`          // 操作人
	ChangeReason  string                 `protobuf:"bytes,6,opt,name=changeReason,proto3" json:"changeReason,omitempty"`    // 回滚原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackConfigRequest) Reset() {
	*x = RollbackConfigRequest{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackConfigRequest) ProtoMessage() {}

func (x *RollbackConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackConfigRequest.ProtoReflect.Descriptor instead.
func (*RollbackConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{12}
}

func (x *RollbackConfigRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *RollbackConfigRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *RollbackConfigRequest) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *RollbackConfigRequest) GetTargetVersion() int64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

func (x *RollbackConfigRequest) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *RollbackConfigRequest) GetChangeReason() string {
	if x != nil {
		return x.ChangeReason
	}
	return ""
}

// 配置变更事件（Server-Side Streaming）
type ConfigChangeEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType string                 `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"` // CONFIG_UPDATED, CONFIG_DELETED
	Timestamp string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 事件时间戳
	// 配置标识
	NamespaceId   string      `protobuf:"bytes,3,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string      `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ConfigDataId  string      `protobuf:"bytes,5,opt,name=configDataId,proto3" json:"configDataId,omitempty"`
	Config        *ConfigData `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`         // 配置数据（删除事件时为空）
	ContentMd5    string      `protobuf:"bytes,7,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"` // 新的MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangeEvent) Reset() {
	*x = ConfigChangeEvent{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeEvent) ProtoMessage() {}

func (x *ConfigChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeEvent.ProtoReflect.Descriptor instead.
func (*ConfigChangeEvent) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigChangeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ConfigChangeEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ConfigChangeEvent) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ConfigChangeEvent) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConfigChangeEvent) GetConfigDataId() string {
	if x != nil {
		return x.ConfigDataId
	}
	return ""
}

func (x *ConfigChangeEvent) GetConfig() *ConfigData {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigChangeEvent) GetContentMd5() string {
	if x != nil {
		return x.ContentMd5
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x06config\"X\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x80\x03\n" +
	"\n" +
	"ConfigData\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x03 \x01(\tR\fconfigDataId\x12 \n" +
	"\vcontentType\x18\x04 \x01(\tR\vcontentType\x12$\n" +
	"\rconfigContent\x18\x05 \x01(\tR\rconfigContent\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\x06 \x01(\tR\n" +
	"contentMd5\x12\x1e\n" +
	"\n" +
	"configDesc\x18\a \x01(\tR\n" +
	"configDesc\x12$\n" +
	"\rconfigVersion\x18\b \x01(\x03R\rconfigVersion\x12\x1e\n" +
	"\n" +
	"changeType\x18\t \x01(\tR\n" +
	"changeType\x12\"\n" +
	"\fchangeReason\x18\n" +
	" \x01(\tR\fchangeReason\x12\x1c\n" +
	"\tchangedBy\x18\v \x01(\tR\tchangedBy\"\xad\x03\n" +
	"\rConfigHistory\x12(\n" +
	"\x0fconfigHistoryId\x18\x01 \x01(\x03R\x0fconfigHistoryId\x12 \n" +
	"\vnamespaceId\x18\x02 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x03 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x04 \x01(\tR\fconfigDataId\x12 \n" +
	"\vcontentType\x18\x05 \x01(\tR\vcontentType\x12$\n" +
	"\rconfigContent\x18\x06 \x01(\tR\rconfigContent\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\a \x01(\tR\n" +
	"contentMd5\x12$\n" +
	"\rconfigVersion\x18\b \x01(\x03R\rconfigVersion\x12\x1e\n" +
	"\n" +
	"changeType\x18\t \x01(\tR\n" +
	"changeType\x12\"\n" +
	"\fchangeReason\x18\n" +
	" \x01(\tR\fchangeReason\x12\x1c\n" +
	"\tchangedBy\x18\v \x01(\tR\tchangedBy\x12\x1e\n" +
	"\n" +
	"changeTime\x18\f \x01(\tR\n" +
	"changeTime\"o\n" +
	"\tConfigKey\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x03 \x01(\tR\fconfigDataId\"s\n" +
	"\x11GetConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x06config\x18\x03 \x01(\v2\x12.config.ConfigDataR\x06config\"\x96\x01\n" +
	"\x12SaveConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\x05 \x01(\tR\n" +
	"contentMd5\"w\n" +
	"\x13ListConfigsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\aconfigs\x18\x03 \x03(\v2\x12.config.ConfigDataR\aconfigs\"\x7f\n" +
	"\x18GetConfigHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\ahistory\x18\x03 \x03(\v2\x15.config.ConfigHistoryR\ahistory\"\xa0\x01\n" +
	"\x16RollbackConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"newVersion\x18\x04 \x01(\x03R\n" +
	"newVersion\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\x05 \x01(\tR\n" +
	"contentMd5\"T\n" +
	"\x12ListConfigsRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\"z\n" +
	"\x12WatchConfigRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12$\n" +
	"\rconfigDataIds\x18\x03 \x03(\tR\rconfigDataIds\"\x93\x01\n" +
	"\x17GetConfigHistoryRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x03 \x01(\tR\fconfigDataId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xe3\x01\n" +
	"\x15RollbackConfigRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x03 \x01(\tR\fconfigDataId\x12$\n" +
	"\rtargetVersion\x18\x04 \x01(\x03R\rtargetVersion\x12\x1c\n" +
	"\tchangedBy\x18\x05 \x01(\tR\tchangedBy\x12\"\n" +
	"\fchangeReason\x18\x06 \x01(\tR\fchangeReason\"\xff\x01\n" +
	"\x11ConfigChangeEvent\x12\x1c\n" +
	"\teventType\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12 \n" +
	"\vnamespaceId\x18\x03 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x04 \x01(\tR\tgroupName\x12\"\n" +
	"\fconfigDataId\x18\x05 \x01(\tR\fconfigDataId\x12*\n" +
	"\x06config\x18\x06 \x01(\v2\x12.config.ConfigDataR\x06config\x12\x1e\n" +
	"\n" +
	"contentMd5\x18\a \x01(\tR\n" +
	"contentMd52\xfa\x03\n" +
	"\fConfigCenter\x129\n" +
	"\tGetConfig\x12\x11.config.ConfigKey\x1a\x19.config.GetConfigResponse\x12<\n" +
	"\n" +
	"SaveConfig\x12\x12.config.ConfigData\x1a\x1a.config.SaveConfigResponse\x129\n" +
	"\fDeleteConfig\x12\x11.config.ConfigKey\x1a\x16.config.ConfigResponse\x12F\n" +
	"\vListConfigs\x12\x1a.config.ListConfigsRequest\x1a\x1b.config.ListConfigsResponse\x12F\n" +
	"\vWatchConfig\x12\x1a.config.WatchConfigRequest\x1a\x19.config.ConfigChangeEvent0\x01\x12U\n" +
	"\x10GetConfigHistory\x12\x1f.config.GetConfigHistoryRequest\x1a .config.GetConfigHistoryResponse\x12O\n" +
	"\x0eRollbackConfig\x12\x1d.config.RollbackConfigRequest\x1a\x1e.config.RollbackConfigResponseB3Z1gateway/internal/servicecenter/server/proto;protob\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_config_proto_goTypes = []any{
	(*ConfigResponse)(nil),           // 0: config.ConfigResponse
	(*ConfigData)(nil),               // 1: config.ConfigData
	(*ConfigHistory)(nil),            // 2: config.ConfigHistory
	(*ConfigKey)(nil),                // 3: config.ConfigKey
	(*GetConfigResponse)(nil),        // 4: config.GetConfigResponse
	(*SaveConfigResponse)(nil),       // 5: config.SaveConfigResponse
	(*ListConfigsResponse)(nil),      // 6: config.ListConfigsResponse
	(*GetConfigHistoryResponse)(nil), // 7: config.GetConfigHistoryResponse
	(*RollbackConfigResponse)(nil),   // 8: config.RollbackConfigResponse
	(*ListConfigsRequest)(nil),       // 9: config.ListConfigsRequest
	(*WatchConfigRequest)(nil),       // 10: config.WatchConfigRequest
	(*GetConfigHistoryRequest)(nil),  // 11: config.GetConfigHistoryRequest
	(*RollbackConfigRequest)(nil),    // 12: config.RollbackConfigRequest
	(*ConfigChangeEvent)(nil),        // 13: config.ConfigChangeEvent
}
var file_config_proto_depIdxs = []int32{
	1,  // 0: config.GetConfigResponse.config:type_name -> config.ConfigData
	1,  // 1: config.ListConfigsResponse.configs:type_name -> config.ConfigData
	2,  // 2: config.GetConfigHistoryResponse.history:type_name -> config.ConfigHistory
	1,  // 3: config.ConfigChangeEvent.config:type_name -> config.ConfigData
	3,  // 4: config.ConfigCenter.GetConfig:input_type -> config.ConfigKey
	1,  // 5: config.ConfigCenter.SaveConfig:input_type -> config.ConfigData
	3,  // 6: config.ConfigCenter.DeleteConfig:input_type -> config.ConfigKey
	9,  // 7: config.ConfigCenter.ListConfigs:input_type -> config.ListConfigsRequest
	10, // 8: config.ConfigCenter.WatchConfig:input_type -> config.WatchConfigRequest
	11, // 9: config.ConfigCenter.GetConfigHistory:input_type -> config.GetConfigHistoryRequest
	12, // 10: config.ConfigCenter.RollbackConfig:input_type -> config.RollbackConfigRequest
	4,  // 11: config.ConfigCenter.GetConfig:output_type -> config.GetConfigResponse
	5,  // 12: config.ConfigCenter.SaveConfig:output_type -> config.SaveConfigResponse
	0,  // 13: config.ConfigCenter.DeleteConfig:output_type -> config.ConfigResponse
	6,  // 14: config.ConfigCenter.ListConfigs:output_type -> config.ListConfigsResponse
	13, // 15: config.ConfigCenter.WatchConfig:output_type -> config.ConfigChangeEvent
	7,  // 16: config.ConfigCenter.GetConfigHistory:output_type -> config.GetConfigHistoryResponse
	8,  // 17: config.ConfigCenter.RollbackConfig:output_type -> config.RollbackConfigResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
