// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: config.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigCenter_GetConfig_FullMethodName        = "/config.ConfigCenter/GetConfig"
	ConfigCenter_SaveConfig_FullMethodName       = "/config.ConfigCenter/SaveConfig"
	ConfigCenter_DeleteConfig_FullMethodName     = "/config.ConfigCenter/DeleteConfig"
	ConfigCenter_ListConfigs_FullMethodName      = "/config.ConfigCenter/ListConfigs"
	ConfigCenter_WatchConfig_FullMethodName      = "/config.ConfigCenter/WatchConfig"
	ConfigCenter_GetConfigHistory_FullMethodName = "/config.ConfigCenter/GetConfigHistory"
	ConfigCenter_RollbackConfig_FullMethodName   = "/config.ConfigCenter/RollbackConfig"
)

// ConfigCenterClient is the client API for ConfigCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigCenter 配置中心
type ConfigCenterClient interface {
	// 获取配置
	GetConfig(ctx context.Context, in *ConfigKey, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// 保存配置（ConfigData 中包含所有必要信息）
	SaveConfig(ctx context.Context, in *ConfigData, opts ...grpc.CallOption) (*SaveConfigResponse, error)
	// 删除配置
	DeleteConfig(ctx context.Context, in *ConfigKey, opts ...grpc.CallOption) (*ConfigResponse, error)
	// 列出配置列表
	ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error)
	// 监听配置变更（统一接口，支持监听单个或多个配置）- Server-Side Streaming
	// 单个配置监听：configDataIds 数组只包含一个配置标识
	// 多个配置监听：configDataIds 数组包含多个配置标识，所有配置共用同一个 channel
	// 用于数据库变动主动推送，只需要配置标识即可
	WatchConfig(ctx context.Context, in *WatchConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigChangeEvent], error)
	// 获取配置历史
	GetConfigHistory(ctx context.Context, in *GetConfigHistoryRequest, opts ...grpc.CallOption) (*GetConfigHistoryResponse, error)
	// 回滚配置
	RollbackConfig(ctx context.Context, in *RollbackConfigRequest, opts ...grpc.CallOption) (*RollbackConfigResponse, error)
}

type configCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigCenterClient(cc grpc.ClientConnInterface) ConfigCenterClient {
	return &configCenterClient{cc}
}

func (c *configCenterClient) GetConfig(ctx context.Context, in *ConfigKey, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ConfigCenter_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) SaveConfig(ctx context.Context, in *ConfigData, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConfigResponse)
	err := c.cc.Invoke(ctx, ConfigCenter_SaveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) DeleteConfig(ctx context.Context, in *ConfigKey, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, ConfigCenter_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigsResponse)
	err := c.cc.Invoke(ctx, ConfigCenter_ListConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) WatchConfig(ctx context.Context, in *WatchConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigCenter_ServiceDesc.Streams[0], ConfigCenter_WatchConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchConfigRequest, ConfigChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigCenter_WatchConfigClient = grpc.ServerStreamingClient[ConfigChangeEvent]

func (c *configCenterClient) GetConfigHistory(ctx context.Context, in *GetConfigHistoryRequest, opts ...grpc.CallOption) (*GetConfigHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigHistoryResponse)
	err := c.cc.Invoke(ctx, ConfigCenter_GetConfigHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCenterClient) RollbackConfig(ctx context.Context, in *RollbackConfigRequest, opts ...grpc.CallOption) (*RollbackConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackConfigResponse)
	err := c.cc.Invoke(ctx, ConfigCenter_RollbackConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigCenterServer is the server API for ConfigCenter service.
// All implementations must embed UnimplementedConfigCenterServer
// for forward compatibility.
//
// ConfigCenter 配置中心
type ConfigCenterServer interface {
	// 获取配置
	GetConfig(context.Context, *ConfigKey) (*GetConfigResponse, error)
	// 保存配置（ConfigData 中包含所有必要信息）
	SaveConfig(context.Context, *ConfigData) (*SaveConfigResponse, error)
	// 删除配置
	DeleteConfig(context.Context, *ConfigKey) (*ConfigResponse, error)
	// 列出配置列表
	ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error)
	// 监听配置变更（统一接口，支持监听单个或多个配置）- Server-Side Streaming
	// 单个配置监听：configDataIds 数组只包含一个配置标识
	// 多个配置监听：configDataIds 数组包含多个配置标识，所有配置共用同一个 channel
	// 用于数据库变动主动推送，只需要配置标识即可
	WatchConfig(*WatchConfigRequest, grpc.ServerStreamingServer[ConfigChangeEvent]) error
	// 获取配置历史
	GetConfigHistory(context.Context, *GetConfigHistoryRequest) (*GetConfigHistoryResponse, error)
	// 回滚配置
	RollbackConfig(context.Context, *RollbackConfigRequest) (*RollbackConfigResponse, error)
	mustEmbedUnimplementedConfigCenterServer()
}

// UnimplementedConfigCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigCenterServer struct{}

func (UnimplementedConfigCenterServer) GetConfig(context.Context, *ConfigKey) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedConfigCenterServer) SaveConfig(context.Context, *ConfigData) (*SaveConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveConfig not implemented")
}
func (UnimplementedConfigCenterServer) DeleteConfig(context.Context, *ConfigKey) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedConfigCenterServer) ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfigs not implemented")
}
func (UnimplementedConfigCenterServer) WatchConfig(*WatchConfigRequest, grpc.ServerStreamingServer[ConfigChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchConfig not implemented")
}
func (UnimplementedConfigCenterServer) GetConfigHistory(context.Context, *GetConfigHistoryRequest) (*GetConfigHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigHistory not implemented")
}
func (UnimplementedConfigCenterServer) RollbackConfig(context.Context, *RollbackConfigRequest) (*RollbackConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackConfig not implemented")
}
func (UnimplementedConfigCenterServer) mustEmbedUnimplementedConfigCenterServer() {}
func (UnimplementedConfigCenterServer) testEmbeddedByValue()                      {}

// UnsafeConfigCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigCenterServer will
// result in compilation errors.
type UnsafeConfigCenterServer interface {
	mustEmbedUnimplementedConfigCenterServer()
}

func RegisterConfigCenterServer(s grpc.ServiceRegistrar, srv ConfigCenterServer) {
	// If the following call panics, it indicates UnimplementedConfigCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigCenter_ServiceDesc, srv)
}

func _ConfigCenter_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).GetConfig(ctx, req.(*ConfigKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_SaveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).SaveConfig(ctx, req.(*ConfigData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).DeleteConfig(ctx, req.(*ConfigKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_ListConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).ListConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_ListConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).ListConfigs(ctx, req.(*ListConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_WatchConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigCenterServer).WatchConfig(m, &grpc.GenericServerStream[WatchConfigRequest, ConfigChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigCenter_WatchConfigServer = grpc.ServerStreamingServer[ConfigChangeEvent]

func _ConfigCenter_GetConfigHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).GetConfigHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_GetConfigHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).GetConfigHistory(ctx, req.(*GetConfigHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCenter_RollbackConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCenterServer).RollbackConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCenter_RollbackConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCenterServer).RollbackConfig(ctx, req.(*RollbackConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigCenter_ServiceDesc is the grpc.ServiceDesc for ConfigCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config.ConfigCenter",
	HandlerType: (*ConfigCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _ConfigCenter_GetConfig_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _ConfigCenter_SaveConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _ConfigCenter_DeleteConfig_Handler,
		},
		{
			MethodName: "ListConfigs",
			Handler:    _ConfigCenter_ListConfigs_Handler,
		},
		{
			MethodName: "GetConfigHistory",
			Handler:    _ConfigCenter_GetConfigHistory_Handler,
		},
		{
			MethodName: "RollbackConfig",
			Handler:    _ConfigCenter_RollbackConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConfig",
			Handler:       _ConfigCenter_WatchConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "config.proto",
}
