// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: registry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceRegistry_RegisterService_FullMethodName    = "/registry.ServiceRegistry/RegisterService"
	ServiceRegistry_UnregisterService_FullMethodName  = "/registry.ServiceRegistry/UnregisterService"
	ServiceRegistry_GetService_FullMethodName         = "/registry.ServiceRegistry/GetService"
	ServiceRegistry_RegisterNode_FullMethodName       = "/registry.ServiceRegistry/RegisterNode"
	ServiceRegistry_UnregisterNode_FullMethodName     = "/registry.ServiceRegistry/UnregisterNode"
	ServiceRegistry_DiscoverNodes_FullMethodName      = "/registry.ServiceRegistry/DiscoverNodes"
	ServiceRegistry_SubscribeServices_FullMethodName  = "/registry.ServiceRegistry/SubscribeServices"
	ServiceRegistry_SubscribeNamespace_FullMethodName = "/registry.ServiceRegistry/SubscribeNamespace"
	ServiceRegistry_Heartbeat_FullMethodName          = "/registry.ServiceRegistry/Heartbeat"
)

// ServiceRegistryClient is the client API for ServiceRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServiceRegistry 服务注册发现
type ServiceRegistryClient interface {
	// 注册服务（Service 中可包含一个 node，同时注册服务和节点）
	RegisterService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	// 注销服务（只需标识信息）
	UnregisterService(ctx context.Context, in *ServiceKey, opts ...grpc.CallOption) (*RegistryResponse, error)
	// 获取服务信息（包含服务基本信息和节点列表）
	GetService(ctx context.Context, in *ServiceKey, opts ...grpc.CallOption) (*GetServiceResponse, error)
	// 注册服务节点（nodeId 由服务端自动生成）
	RegisterNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// 注销服务节点
	UnregisterNode(ctx context.Context, in *NodeKey, opts ...grpc.CallOption) (*RegistryResponse, error)
	// 发现服务节点（一次性查询）
	DiscoverNodes(ctx context.Context, in *DiscoverNodesRequest, opts ...grpc.CallOption) (*DiscoverNodesResponse, error)
	// 订阅服务节点变更（统一接口，支持订阅单个或多个服务）- Server-Side Streaming
	// 单个服务订阅：serviceNames 数组只包含一个服务名
	// 多个服务订阅：serviceNames 数组包含多个服务名，所有服务共用同一个 channel
	SubscribeServices(ctx context.Context, in *SubscribeServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceChangeEvent], error)
	// 订阅整个命名空间/分组下的所有服务变更 - Server-Side Streaming
	SubscribeNamespace(ctx context.Context, in *SubscribeNamespaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceChangeEvent], error)
	// 心跳上报
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*RegistryResponse, error)
}

type serviceRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceRegistryClient(cc grpc.ClientConnInterface) ServiceRegistryClient {
	return &serviceRegistryClient{cc}
}

func (c *serviceRegistryClient) RegisterService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterServiceResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_RegisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) UnregisterService(ctx context.Context, in *ServiceKey, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_UnregisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) GetService(ctx context.Context, in *ServiceKey, opts ...grpc.CallOption) (*GetServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) RegisterNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) UnregisterNode(ctx context.Context, in *NodeKey, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_UnregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) DiscoverNodes(ctx context.Context, in *DiscoverNodesRequest, opts ...grpc.CallOption) (*DiscoverNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverNodesResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_DiscoverNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceRegistryClient) SubscribeServices(ctx context.Context, in *SubscribeServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServiceRegistry_ServiceDesc.Streams[0], ServiceRegistry_SubscribeServices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeServicesRequest, ServiceChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceRegistry_SubscribeServicesClient = grpc.ServerStreamingClient[ServiceChangeEvent]

func (c *serviceRegistryClient) SubscribeNamespace(ctx context.Context, in *SubscribeNamespaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServiceRegistry_ServiceDesc.Streams[1], ServiceRegistry_SubscribeNamespace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeNamespaceRequest, ServiceChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceRegistry_SubscribeNamespaceClient = grpc.ServerStreamingClient[ServiceChangeEvent]

func (c *serviceRegistryClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, ServiceRegistry_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceRegistryServer is the server API for ServiceRegistry service.
// All implementations must embed UnimplementedServiceRegistryServer
// for forward compatibility.
//
// ServiceRegistry 服务注册发现
type ServiceRegistryServer interface {
	// 注册服务（Service 中可包含一个 node，同时注册服务和节点）
	RegisterService(context.Context, *Service) (*RegisterServiceResponse, error)
	// 注销服务（只需标识信息）
	UnregisterService(context.Context, *ServiceKey) (*RegistryResponse, error)
	// 获取服务信息（包含服务基本信息和节点列表）
	GetService(context.Context, *ServiceKey) (*GetServiceResponse, error)
	// 注册服务节点（nodeId 由服务端自动生成）
	RegisterNode(context.Context, *Node) (*RegisterNodeResponse, error)
	// 注销服务节点
	UnregisterNode(context.Context, *NodeKey) (*RegistryResponse, error)
	// 发现服务节点（一次性查询）
	DiscoverNodes(context.Context, *DiscoverNodesRequest) (*DiscoverNodesResponse, error)
	// 订阅服务节点变更（统一接口，支持订阅单个或多个服务）- Server-Side Streaming
	// 单个服务订阅：serviceNames 数组只包含一个服务名
	// 多个服务订阅：serviceNames 数组包含多个服务名，所有服务共用同一个 channel
	SubscribeServices(*SubscribeServicesRequest, grpc.ServerStreamingServer[ServiceChangeEvent]) error
	// 订阅整个命名空间/分组下的所有服务变更 - Server-Side Streaming
	SubscribeNamespace(*SubscribeNamespaceRequest, grpc.ServerStreamingServer[ServiceChangeEvent]) error
	// 心跳上报
	Heartbeat(context.Context, *HeartbeatRequest) (*RegistryResponse, error)
	mustEmbedUnimplementedServiceRegistryServer()
}

// UnimplementedServiceRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceRegistryServer struct{}

func (UnimplementedServiceRegistryServer) RegisterService(context.Context, *Service) (*RegisterServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedServiceRegistryServer) UnregisterService(context.Context, *ServiceKey) (*RegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterService not implemented")
}
func (UnimplementedServiceRegistryServer) GetService(context.Context, *ServiceKey) (*GetServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedServiceRegistryServer) RegisterNode(context.Context, *Node) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedServiceRegistryServer) UnregisterNode(context.Context, *NodeKey) (*RegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (UnimplementedServiceRegistryServer) DiscoverNodes(context.Context, *DiscoverNodesRequest) (*DiscoverNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverNodes not implemented")
}
func (UnimplementedServiceRegistryServer) SubscribeServices(*SubscribeServicesRequest, grpc.ServerStreamingServer[ServiceChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeServices not implemented")
}
func (UnimplementedServiceRegistryServer) SubscribeNamespace(*SubscribeNamespaceRequest, grpc.ServerStreamingServer[ServiceChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeNamespace not implemented")
}
func (UnimplementedServiceRegistryServer) Heartbeat(context.Context, *HeartbeatRequest) (*RegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedServiceRegistryServer) mustEmbedUnimplementedServiceRegistryServer() {}
func (UnimplementedServiceRegistryServer) testEmbeddedByValue()                         {}

// UnsafeServiceRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceRegistryServer will
// result in compilation errors.
type UnsafeServiceRegistryServer interface {
	mustEmbedUnimplementedServiceRegistryServer()
}

func RegisterServiceRegistryServer(s grpc.ServiceRegistrar, srv ServiceRegistryServer) {
	// If the following call panics, it indicates UnimplementedServiceRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceRegistry_ServiceDesc, srv)
}

func _ServiceRegistry_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).RegisterService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_UnregisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).UnregisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_UnregisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).UnregisterService(ctx, req.(*ServiceKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).GetService(ctx, req.(*ServiceKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).RegisterNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_UnregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).UnregisterNode(ctx, req.(*NodeKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_DiscoverNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).DiscoverNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_DiscoverNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).DiscoverNodes(ctx, req.(*DiscoverNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceRegistry_SubscribeServices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeServicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceRegistryServer).SubscribeServices(m, &grpc.GenericServerStream[SubscribeServicesRequest, ServiceChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceRegistry_SubscribeServicesServer = grpc.ServerStreamingServer[ServiceChangeEvent]

func _ServiceRegistry_SubscribeNamespace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeNamespaceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceRegistryServer).SubscribeNamespace(m, &grpc.GenericServerStream[SubscribeNamespaceRequest, ServiceChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceRegistry_SubscribeNamespaceServer = grpc.ServerStreamingServer[ServiceChangeEvent]

func _ServiceRegistry_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceRegistryServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceRegistry_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceRegistryServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceRegistry_ServiceDesc is the grpc.ServiceDesc for ServiceRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.ServiceRegistry",
	HandlerType: (*ServiceRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _ServiceRegistry_RegisterService_Handler,
		},
		{
			MethodName: "UnregisterService",
			Handler:    _ServiceRegistry_UnregisterService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _ServiceRegistry_GetService_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _ServiceRegistry_RegisterNode_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _ServiceRegistry_UnregisterNode_Handler,
		},
		{
			MethodName: "DiscoverNodes",
			Handler:    _ServiceRegistry_DiscoverNodes_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ServiceRegistry_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeServices",
			Handler:       _ServiceRegistry_SubscribeServices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeNamespace",
			Handler:       _ServiceRegistry_SubscribeNamespace_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "registry.proto",
}
