// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: registry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"` // 业务错误码（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryResponse) Reset() {
	*x = RegistryResponse{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryResponse) ProtoMessage() {}

func (x *RegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryResponse.ProtoReflect.Descriptor instead.
func (*RegistryResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegistryResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Service struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId        string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName          string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName        string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceType        string                 `protobuf:"bytes,4,opt,name=serviceType,proto3" json:"serviceType,omitempty"`                                                                     // INTERNAL, NACOS, CONSUL等
	ServiceVersion     string                 `protobuf:"bytes,5,opt,name=serviceVersion,proto3" json:"serviceVersion,omitempty"`                                                               // 服务版本号
	ServiceDescription string                 `protobuf:"bytes,6,opt,name=serviceDescription,proto3" json:"serviceDescription,omitempty"`                                                       // 服务描述
	ProtectThreshold   float64                `protobuf:"fixed64,7,opt,name=protectThreshold,proto3" json:"protectThreshold,omitempty"`                                                         // 保护阈值（0.0-1.0）
	Metadata           map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	Tags               map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`         // 服务标签
	Node               *Node                  `protobuf:"bytes,10,opt,name=node,proto3" json:"node,omitempty"`                                                                                  // 服务节点（注册时可选，同时注册一个节点）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Service) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Service) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Service) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *Service) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *Service) GetServiceDescription() string {
	if x != nil {
		return x.ServiceDescription
	}
	return ""
}

func (x *Service) GetProtectThreshold() float64 {
	if x != nil {
		return x.ProtectThreshold
	}
	return 0
}

func (x *Service) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Service) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type Node struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"` // 节点ID（注册时不传，服务端自动生成；查询时返回）
	NamespaceId    string                 `protobuf:"bytes,2,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName      string                 `protobuf:"bytes,3,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName    string                 `protobuf:"bytes,4,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	IpAddress      string                 `protobuf:"bytes,5,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	PortNumber     int32                  `protobuf:"varint,6,opt,name=portNumber,proto3" json:"portNumber,omitempty"`
	Weight         float64                `protobuf:"fixed64,7,opt,name=weight,proto3" json:"weight,omitempty"`                                                                              // 权重值（0.01-10000.00）
	Ephemeral      string                 `protobuf:"bytes,8,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`                                                                          // Y/N（是否临时节点）
	InstanceStatus string                 `protobuf:"bytes,9,opt,name=instanceStatus,proto3" json:"instanceStatus,omitempty"`                                                                // UP, DOWN, STARTING, OUT_OF_SERVICE
	HealthyStatus  string                 `protobuf:"bytes,10,opt,name=healthyStatus,proto3" json:"healthyStatus,omitempty"`                                                                 // HEALTHY, UNHEALTHY, UNKNOWN
	Metadata       map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Node) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Node) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Node) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Node) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Node) GetPortNumber() int32 {
	if x != nil {
		return x.PortNumber
	}
	return 0
}

func (x *Node) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Node) GetEphemeral() string {
	if x != nil {
		return x.Ephemeral
	}
	return ""
}

func (x *Node) GetInstanceStatus() string {
	if x != nil {
		return x.InstanceStatus
	}
	return ""
}

func (x *Node) GetHealthyStatus() string {
	if x != nil {
		return x.HealthyStatus
	}
	return ""
}

func (x *Node) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 服务标识（用于查询、删除、订阅）
type ServiceKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=nodeId,proto3" json:"nodeId,omitempty"` // 可选的节点ID（UnregisterService时：如果指定则只删除该节点，否则删除整个服务）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceKey) Reset() {
	*x = ServiceKey{}
	mi := &file_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceKey) ProtoMessage() {}

func (x *ServiceKey) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceKey.ProtoReflect.Descriptor instead.
func (*ServiceKey) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceKey) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ServiceKey) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ServiceKey) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceKey) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// 节点标识（用于删除、心跳）
type NodeKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeKey) Reset() {
	*x = NodeKey{}
	mi := &file_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeKey) ProtoMessage() {}

func (x *NodeKey) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeKey.ProtoReflect.Descriptor instead.
func (*NodeKey) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{4}
}

func (x *NodeKey) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// 注册服务响应（返回服务端生成的 nodeId，如果注册时携带了节点）
type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`     // 业务错误码（可选）
	NodeId        string                 `protobuf:"bytes,4,opt,name=nodeId,proto3" json:"nodeId,omitempty"` // 服务端生成的节点ID（如果注册时携带了 node，则返回生成的 nodeId；否则为空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterServiceResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterServiceResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// 获取服务响应（包含服务信息和节点列表）
type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Service       *Service               `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"` // 服务基本信息（service.node 字段在响应中不使用）
	Nodes         []*Node                `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`     // 该服务已注册的所有节点列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{6}
}

func (x *GetServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *GetServiceResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// 注册节点响应（返回服务端生成的 nodeId）
type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=nodeId,proto3" json:"nodeId,omitempty"` // 服务端生成的节点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// 发现节点响应
type DiscoverNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverNodesResponse) Reset() {
	*x = DiscoverNodesResponse{}
	mi := &file_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverNodesResponse) ProtoMessage() {}

func (x *DiscoverNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverNodesResponse.ProtoReflect.Descriptor instead.
func (*DiscoverNodesResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoverNodesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DiscoverNodesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DiscoverNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type DiscoverNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	HealthyOnly   bool                   `protobuf:"varint,4,opt,name=healthyOnly,proto3" json:"healthyOnly,omitempty"` // 是否只返回健康节点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverNodesRequest) Reset() {
	*x = DiscoverNodesRequest{}
	mi := &file_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverNodesRequest) ProtoMessage() {}

func (x *DiscoverNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverNodesRequest.ProtoReflect.Descriptor instead.
func (*DiscoverNodesRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoverNodesRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *DiscoverNodesRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *DiscoverNodesRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DiscoverNodesRequest) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

// 订阅服务（统一接口，支持订阅单个或多个服务）
// serviceNames 是数组：
//   - 单个服务订阅：serviceNames = ["user-service"]
//   - 多个服务订阅：serviceNames = ["order-service", "user-service", "pay-service"]
//
// 所有订阅的服务共用同一个 channel，减少 Stream 连接数
type SubscribeServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceNames  []string               `protobuf:"bytes,3,rep,name=serviceNames,proto3" json:"serviceNames,omitempty"` // repeated = 数组/列表，支持订阅单个或多个服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServicesRequest) Reset() {
	*x = SubscribeServicesRequest{}
	mi := &file_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServicesRequest) ProtoMessage() {}

func (x *SubscribeServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServicesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeServicesRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeServicesRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *SubscribeServicesRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *SubscribeServicesRequest) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

// 订阅整个命名空间/分组（订阅所有服务）
type SubscribeNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceId   string                 `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"` // 可选：如果为空则订阅整个命名空间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeNamespaceRequest) Reset() {
	*x = SubscribeNamespaceRequest{}
	mi := &file_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeNamespaceRequest) ProtoMessage() {}

func (x *SubscribeNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeNamespaceRequest.ProtoReflect.Descriptor instead.
func (*SubscribeNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeNamespaceRequest) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *SubscribeNamespaceRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

// 服务变更事件（Server-Side Streaming）
type ServiceChangeEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType string                 `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"` // NODE_ADDED, NODE_UPDATED, NODE_REMOVED, SERVICE_UPDATED
	Timestamp string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 事件时间戳
	// 服务标识（用于批量订阅时区分是哪个服务的变更）
	NamespaceId   string   `protobuf:"bytes,3,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
	GroupName     string   `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	ServiceName   string   `protobuf:"bytes,5,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Service       *Service `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`         // 服务信息
	Nodes         []*Node  `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`             // 当前所有节点列表
	ChangedNode   *Node    `protobuf:"bytes,8,opt,name=changedNode,proto3" json:"changedNode,omitempty"` // 变更的节点（用于增量更新）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceChangeEvent) Reset() {
	*x = ServiceChangeEvent{}
	mi := &file_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChangeEvent) ProtoMessage() {}

func (x *ServiceChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChangeEvent.ProtoReflect.Descriptor instead.
func (*ServiceChangeEvent) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceChangeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ServiceChangeEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ServiceChangeEvent) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ServiceChangeEvent) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ServiceChangeEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceChangeEvent) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceChangeEvent) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ServiceChangeEvent) GetChangedNode() *Node {
	if x != nil {
		return x.ChangedNode
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`   // 节点ID（必需）
	Service       *Service               `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"` // 完整的服务信息（可选，但强烈建议传入）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\bregistry\"Z\n" +
	"\x10RegistryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x99\x04\n" +
	"\aService\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceName\x12 \n" +
	"\vserviceType\x18\x04 \x01(\tR\vserviceType\x12&\n" +
	"\x0eserviceVersion\x18\x05 \x01(\tR\x0eserviceVersion\x12.\n" +
	"\x12serviceDescription\x18\x06 \x01(\tR\x12serviceDescription\x12*\n" +
	"\x10protectThreshold\x18\a \x01(\x01R\x10protectThreshold\x12;\n" +
	"\bmetadata\x18\b \x03(\v2\x1f.registry.Service.MetadataEntryR\bmetadata\x12/\n" +
	"\x04tags\x18\t \x03(\v2\x1b.registry.Service.TagsEntryR\x04tags\x12\"\n" +
	"\x04node\x18\n" +
	" \x01(\v2\x0e.registry.NodeR\x04node\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x03\n" +
	"\x04Node\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12 \n" +
	"\vnamespaceId\x18\x02 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x03 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x04 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tipAddress\x18\x05 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"portNumber\x18\x06 \x01(\x05R\n" +
	"portNumber\x12\x16\n" +
	"\x06weight\x18\a \x01(\x01R\x06weight\x12\x1c\n" +
	"\tephemeral\x18\b \x01(\tR\tephemeral\x12&\n" +
	"\x0einstanceStatus\x18\t \x01(\tR\x0einstanceStatus\x12$\n" +
	"\rhealthyStatus\x18\n" +
	" \x01(\tR\rhealthyStatus\x128\n" +
	"\bmetadata\x18\v \x03(\v2\x1c.registry.Node.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\n" +
	"ServiceKey\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06nodeId\x18\x04 \x01(\tR\x06nodeId\"!\n" +
	"\aNodeKey\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\"y\n" +
	"\x17RegisterServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06nodeId\x18\x04 \x01(\tR\x06nodeId\"\x9b\x01\n" +
	"\x12GetServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\aservice\x18\x03 \x01(\v2\x11.registry.ServiceR\aservice\x12$\n" +
	"\x05nodes\x18\x04 \x03(\v2\x0e.registry.NodeR\x05nodes\"b\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06nodeId\x18\x03 \x01(\tR\x06nodeId\"q\n" +
	"\x15DiscoverNodesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x05nodes\x18\x03 \x03(\v2\x0e.registry.NodeR\x05nodes\"\x9a\x01\n" +
	"\x14DiscoverNodesRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceName\x12 \n" +
	"\vhealthyOnly\x18\x04 \x01(\bR\vhealthyOnly\"~\n" +
	"\x18SubscribeServicesRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12\"\n" +
	"\fserviceNames\x18\x03 \x03(\tR\fserviceNames\"[\n" +
	"\x19SubscribeNamespaceRequest\x12 \n" +
	"\vnamespaceId\x18\x01 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\"\xb7\x02\n" +
	"\x12ServiceChangeEvent\x12\x1c\n" +
	"\teventType\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12 \n" +
	"\vnamespaceId\x18\x03 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tgroupName\x18\x04 \x01(\tR\tgroupName\x12 \n" +
	"\vserviceName\x18\x05 \x01(\tR\vserviceName\x12+\n" +
	"\aservice\x18\x06 \x01(\v2\x11.registry.ServiceR\aservice\x12$\n" +
	"\x05nodes\x18\a \x03(\v2\x0e.registry.NodeR\x05nodes\x120\n" +
	"\vchangedNode\x18\b \x01(\v2\x0e.registry.NodeR\vchangedNode\"W\n" +
	"\x10HeartbeatRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12+\n" +
	"\aservice\x18\x02 \x01(\v2\x11.registry.ServiceR\aservice2\xaf\x05\n" +
	"\x0fServiceRegistry\x12G\n" +
	"\x0fRegisterService\x12\x11.registry.Service\x1a!.registry.RegisterServiceResponse\x12E\n" +
	"\x11UnregisterService\x12\x14.registry.ServiceKey\x1a\x1a.registry.RegistryResponse\x12@\n" +
	"\n" +
	"GetService\x12\x14.registry.ServiceKey\x1a\x1c.registry.GetServiceResponse\x12>\n" +
	"\fRegisterNode\x12\x0e.registry.Node\x1a\x1e.registry.RegisterNodeResponse\x12?\n" +
	"\x0eUnregisterNode\x12\x11.registry.NodeKey\x1a\x1a.registry.RegistryResponse\x12P\n" +
	"\rDiscoverNodes\x12\x1e.registry.DiscoverNodesRequest\x1a\x1f.registry.DiscoverNodesResponse\x12W\n" +
	"\x11SubscribeServices\x12\".registry.SubscribeServicesRequest\x1a\x1c.registry.ServiceChangeEvent0\x01\x12Y\n" +
	"\x12SubscribeNamespace\x12#.registry.SubscribeNamespaceRequest\x1a\x1c.registry.ServiceChangeEvent0\x01\x12C\n" +
	"\tHeartbeat\x12\x1a.registry.HeartbeatRequest\x1a\x1a.registry.RegistryResponseB3Z1gateway/internal/servicecenter/server/proto;protob\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_registry_proto_goTypes = []any{
	(*RegistryResponse)(nil),          // 0: registry.RegistryResponse
	(*Service)(nil),                   // 1: registry.Service
	(*Node)(nil),                      // 2: registry.Node
	(*ServiceKey)(nil),                // 3: registry.ServiceKey
	(*NodeKey)(nil),                   // 4: registry.NodeKey
	(*RegisterServiceResponse)(nil),   // 5: registry.RegisterServiceResponse
	(*GetServiceResponse)(nil),        // 6: registry.GetServiceResponse
	(*RegisterNodeResponse)(nil),      // 7: registry.RegisterNodeResponse
	(*DiscoverNodesResponse)(nil),     // 8: registry.DiscoverNodesResponse
	(*DiscoverNodesRequest)(nil),      // 9: registry.DiscoverNodesRequest
	(*SubscribeServicesRequest)(nil),  // 10: registry.SubscribeServicesRequest
	(*SubscribeNamespaceRequest)(nil), // 11: registry.SubscribeNamespaceRequest
	(*ServiceChangeEvent)(nil),        // 12: registry.ServiceChangeEvent
	(*HeartbeatRequest)(nil),          // 13: registry.HeartbeatRequest
	nil,                               // 14: registry.Service.MetadataEntry
	nil,                               // 15: registry.Service.TagsEntry
	nil,                               // 16: registry.Node.MetadataEntry
}
var file_registry_proto_depIdxs = []int32{
	14, // 0: registry.Service.metadata:type_name -> registry.Service.MetadataEntry
	15, // 1: registry.Service.tags:type_name -> registry.Service.TagsEntry
	2,  // 2: registry.Service.node:type_name -> registry.Node
	16, // 3: registry.Node.metadata:type_name -> registry.Node.MetadataEntry
	1,  // 4: registry.GetServiceResponse.service:type_name -> registry.Service
	2,  // 5: registry.GetServiceResponse.nodes:type_name -> registry.Node
	2,  // 6: registry.DiscoverNodesResponse.nodes:type_name -> registry.Node
	1,  // 7: registry.ServiceChangeEvent.service:type_name -> registry.Service
	2,  // 8: registry.ServiceChangeEvent.nodes:type_name -> registry.Node
	2,  // 9: registry.ServiceChangeEvent.changedNode:type_name -> registry.Node
	1,  // 10: registry.HeartbeatRequest.service:type_name -> registry.Service
	1,  // 11: registry.ServiceRegistry.RegisterService:input_type -> registry.Service
	3,  // 12: registry.ServiceRegistry.UnregisterService:input_type -> registry.ServiceKey
	3,  // 13: registry.ServiceRegistry.GetService:input_type -> registry.ServiceKey
	2,  // 14: registry.ServiceRegistry.RegisterNode:input_type -> registry.Node
	4,  // 15: registry.ServiceRegistry.UnregisterNode:input_type -> registry.NodeKey
	9,  // 16: registry.ServiceRegistry.DiscoverNodes:input_type -> registry.DiscoverNodesRequest
	10, // 17: registry.ServiceRegistry.SubscribeServices:input_type -> registry.SubscribeServicesRequest
	11, // 18: registry.ServiceRegistry.SubscribeNamespace:input_type -> registry.SubscribeNamespaceRequest
	13, // 19: registry.ServiceRegistry.Heartbeat:input_type -> registry.HeartbeatRequest
	5,  // 20: registry.ServiceRegistry.RegisterService:output_type -> registry.RegisterServiceResponse
	0,  // 21: registry.ServiceRegistry.UnregisterService:output_type -> registry.RegistryResponse
	6,  // 22: registry.ServiceRegistry.GetService:output_type -> registry.GetServiceResponse
	7,  // 23: registry.ServiceRegistry.RegisterNode:output_type -> registry.RegisterNodeResponse
	0,  // 24: registry.ServiceRegistry.UnregisterNode:output_type -> registry.RegistryResponse
	8,  // 25: registry.ServiceRegistry.DiscoverNodes:output_type -> registry.DiscoverNodesResponse
	12, // 26: registry.ServiceRegistry.SubscribeServices:output_type -> registry.ServiceChangeEvent
	12, // 27: registry.ServiceRegistry.SubscribeNamespace:output_type -> registry.ServiceChangeEvent
	0,  // 28: registry.ServiceRegistry.Heartbeat:output_type -> registry.RegistryResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
