// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceCenterStream_Connect_FullMethodName = "/stream.ServiceCenterStream/Connect"
)

// ServiceCenterStreamClient is the client API for ServiceCenterStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # ServiceCenterStream 服务中心统一双向流
//
// 【核心优势】
// 1. 实时感知客户端宕机：stream 断开时服务端立即知道（< 1秒 vs 30秒）
// 2. 统一连接：服务注册、配置中心共用一个双向流，减少连接数
// 3. 双向通信：服务端可主动推送变更事件（服务变更、配置变更）
// 4. 多路复用：一个连接承载所有操作（注册、心跳、配置、订阅等）
//
// 【使用流程】
// 1. 客户端连接后立即发送 ClientHandshake（握手）
// 2. 服务端返回 ServerHandshake（分配 connectionId）
// 3. 客户端定期发送 ClientPing（轻量级心跳，5-10秒）
// 4. 客户端发送业务请求（注册、配置等）
// 5. 服务端主动推送变更事件（ServiceChangeEvent, ConfigChangeEvent）
// 6. 连接断开时服务端自动清理所有资源
type ServiceCenterStreamClient interface {
	// 统一双向流（Bidirectional Streaming）
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type serviceCenterStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceCenterStreamClient(cc grpc.ClientConnInterface) ServiceCenterStreamClient {
	return &serviceCenterStreamClient{cc}
}

func (c *serviceCenterStreamClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServiceCenterStream_ServiceDesc.Streams[0], ServiceCenterStream_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceCenterStream_ConnectClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// ServiceCenterStreamServer is the server API for ServiceCenterStream service.
// All implementations must embed UnimplementedServiceCenterStreamServer
// for forward compatibility.
//
// # ServiceCenterStream 服务中心统一双向流
//
// 【核心优势】
// 1. 实时感知客户端宕机：stream 断开时服务端立即知道（< 1秒 vs 30秒）
// 2. 统一连接：服务注册、配置中心共用一个双向流，减少连接数
// 3. 双向通信：服务端可主动推送变更事件（服务变更、配置变更）
// 4. 多路复用：一个连接承载所有操作（注册、心跳、配置、订阅等）
//
// 【使用流程】
// 1. 客户端连接后立即发送 ClientHandshake（握手）
// 2. 服务端返回 ServerHandshake（分配 connectionId）
// 3. 客户端定期发送 ClientPing（轻量级心跳，5-10秒）
// 4. 客户端发送业务请求（注册、配置等）
// 5. 服务端主动推送变更事件（ServiceChangeEvent, ConfigChangeEvent）
// 6. 连接断开时服务端自动清理所有资源
type ServiceCenterStreamServer interface {
	// 统一双向流（Bidirectional Streaming）
	Connect(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedServiceCenterStreamServer()
}

// UnimplementedServiceCenterStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceCenterStreamServer struct{}

func (UnimplementedServiceCenterStreamServer) Connect(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedServiceCenterStreamServer) mustEmbedUnimplementedServiceCenterStreamServer() {}
func (UnimplementedServiceCenterStreamServer) testEmbeddedByValue()                             {}

// UnsafeServiceCenterStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceCenterStreamServer will
// result in compilation errors.
type UnsafeServiceCenterStreamServer interface {
	mustEmbedUnimplementedServiceCenterStreamServer()
}

func RegisterServiceCenterStreamServer(s grpc.ServiceRegistrar, srv ServiceCenterStreamServer) {
	// If the following call panics, it indicates UnimplementedServiceCenterStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceCenterStream_ServiceDesc, srv)
}

func _ServiceCenterStream_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceCenterStreamServer).Connect(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceCenterStream_ConnectServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// ServiceCenterStream_ServiceDesc is the grpc.ServiceDesc for ServiceCenterStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceCenterStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.ServiceCenterStream",
	HandlerType: (*ServiceCenterStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ServiceCenterStream_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stream.proto",
}
