// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端消息类型
type ClientMessageType int32

const (
	ClientMessageType_CLIENT_UNKNOWN             ClientMessageType = 0  // 未知类型
	ClientMessageType_CLIENT_HANDSHAKE           ClientMessageType = 1  // 握手
	ClientMessageType_CLIENT_PING                ClientMessageType = 2  // 心跳
	ClientMessageType_CLIENT_HEARTBEAT           ClientMessageType = 3  // 业务心跳
	ClientMessageType_CLIENT_REGISTER_SERVICE    ClientMessageType = 4  // 注册服务
	ClientMessageType_CLIENT_UNREGISTER_SERVICE  ClientMessageType = 5  // 注销服务
	ClientMessageType_CLIENT_REGISTER_NODE       ClientMessageType = 6  // 注册节点
	ClientMessageType_CLIENT_UNREGISTER_NODE     ClientMessageType = 7  // 注销节点
	ClientMessageType_CLIENT_DISCOVER_NODES      ClientMessageType = 8  // 发现节点
	ClientMessageType_CLIENT_SUBSCRIBE_SERVICES  ClientMessageType = 9  // 订阅服务
	ClientMessageType_CLIENT_SUBSCRIBE_NAMESPACE ClientMessageType = 10 // 订阅命名空间
	ClientMessageType_CLIENT_GET_CONFIG          ClientMessageType = 11 // 获取配置
	ClientMessageType_CLIENT_SAVE_CONFIG         ClientMessageType = 12 // 保存配置
	ClientMessageType_CLIENT_DELETE_CONFIG       ClientMessageType = 13 // 删除配置
	ClientMessageType_CLIENT_LIST_CONFIGS        ClientMessageType = 14 // 列出配置
	ClientMessageType_CLIENT_WATCH_CONFIG        ClientMessageType = 15 // 监听配置
	ClientMessageType_CLIENT_GET_CONFIG_HISTORY  ClientMessageType = 16 // 获取配置历史
	ClientMessageType_CLIENT_ROLLBACK_CONFIG     ClientMessageType = 17 // 回滚配置
)

// Enum value maps for ClientMessageType.
var (
	ClientMessageType_name = map[int32]string{
		0:  "CLIENT_UNKNOWN",
		1:  "CLIENT_HANDSHAKE",
		2:  "CLIENT_PING",
		3:  "CLIENT_HEARTBEAT",
		4:  "CLIENT_REGISTER_SERVICE",
		5:  "CLIENT_UNREGISTER_SERVICE",
		6:  "CLIENT_REGISTER_NODE",
		7:  "CLIENT_UNREGISTER_NODE",
		8:  "CLIENT_DISCOVER_NODES",
		9:  "CLIENT_SUBSCRIBE_SERVICES",
		10: "CLIENT_SUBSCRIBE_NAMESPACE",
		11: "CLIENT_GET_CONFIG",
		12: "CLIENT_SAVE_CONFIG",
		13: "CLIENT_DELETE_CONFIG",
		14: "CLIENT_LIST_CONFIGS",
		15: "CLIENT_WATCH_CONFIG",
		16: "CLIENT_GET_CONFIG_HISTORY",
		17: "CLIENT_ROLLBACK_CONFIG",
	}
	ClientMessageType_value = map[string]int32{
		"CLIENT_UNKNOWN":             0,
		"CLIENT_HANDSHAKE":           1,
		"CLIENT_PING":                2,
		"CLIENT_HEARTBEAT":           3,
		"CLIENT_REGISTER_SERVICE":    4,
		"CLIENT_UNREGISTER_SERVICE":  5,
		"CLIENT_REGISTER_NODE":       6,
		"CLIENT_UNREGISTER_NODE":     7,
		"CLIENT_DISCOVER_NODES":      8,
		"CLIENT_SUBSCRIBE_SERVICES":  9,
		"CLIENT_SUBSCRIBE_NAMESPACE": 10,
		"CLIENT_GET_CONFIG":          11,
		"CLIENT_SAVE_CONFIG":         12,
		"CLIENT_DELETE_CONFIG":       13,
		"CLIENT_LIST_CONFIGS":        14,
		"CLIENT_WATCH_CONFIG":        15,
		"CLIENT_GET_CONFIG_HISTORY":  16,
		"CLIENT_ROLLBACK_CONFIG":     17,
	}
)

func (x ClientMessageType) Enum() *ClientMessageType {
	p := new(ClientMessageType)
	*p = x
	return p
}

func (x ClientMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_proto_enumTypes[0].Descriptor()
}

func (ClientMessageType) Type() protoreflect.EnumType {
	return &file_stream_proto_enumTypes[0]
}

func (x ClientMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientMessageType.Descriptor instead.
func (ClientMessageType) EnumDescriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{0}
}

// 服务端消息类型
type ServerMessageType int32

const (
	ServerMessageType_SERVER_UNKNOWN            ServerMessageType = 0  // 未知类型
	ServerMessageType_SERVER_HANDSHAKE          ServerMessageType = 1  // 握手响应
	ServerMessageType_SERVER_PONG               ServerMessageType = 2  // Pong 响应
	ServerMessageType_SERVER_CLOSE              ServerMessageType = 3  // 关闭通知
	ServerMessageType_SERVER_ERROR              ServerMessageType = 4  // 错误响应
	ServerMessageType_SERVER_HEARTBEAT          ServerMessageType = 5  // 心跳响应
	ServerMessageType_SERVER_REGISTER_SERVICE   ServerMessageType = 6  // 注册服务响应
	ServerMessageType_SERVER_UNREGISTER_SERVICE ServerMessageType = 7  // 注销服务响应
	ServerMessageType_SERVER_REGISTER_NODE      ServerMessageType = 8  // 注册节点响应
	ServerMessageType_SERVER_UNREGISTER_NODE    ServerMessageType = 9  // 注销节点响应
	ServerMessageType_SERVER_DISCOVER_NODES     ServerMessageType = 10 // 发现节点响应
	ServerMessageType_SERVER_SERVICE_CHANGE     ServerMessageType = 11 // 服务变更事件（主动推送）
	ServerMessageType_SERVER_GET_CONFIG         ServerMessageType = 12 // 获取配置响应
	ServerMessageType_SERVER_SAVE_CONFIG        ServerMessageType = 13 // 保存配置响应
	ServerMessageType_SERVER_DELETE_CONFIG      ServerMessageType = 14 // 删除配置响应
	ServerMessageType_SERVER_LIST_CONFIGS       ServerMessageType = 15 // 列出配置响应
	ServerMessageType_SERVER_GET_CONFIG_HISTORY ServerMessageType = 16 // 获取配置历史响应
	ServerMessageType_SERVER_ROLLBACK_CONFIG    ServerMessageType = 17 // 回滚配置响应
	ServerMessageType_SERVER_CONFIG_CHANGE      ServerMessageType = 18 // 配置变更事件（主动推送）
)

// Enum value maps for ServerMessageType.
var (
	ServerMessageType_name = map[int32]string{
		0:  "SERVER_UNKNOWN",
		1:  "SERVER_HANDSHAKE",
		2:  "SERVER_PONG",
		3:  "SERVER_CLOSE",
		4:  "SERVER_ERROR",
		5:  "SERVER_HEARTBEAT",
		6:  "SERVER_REGISTER_SERVICE",
		7:  "SERVER_UNREGISTER_SERVICE",
		8:  "SERVER_REGISTER_NODE",
		9:  "SERVER_UNREGISTER_NODE",
		10: "SERVER_DISCOVER_NODES",
		11: "SERVER_SERVICE_CHANGE",
		12: "SERVER_GET_CONFIG",
		13: "SERVER_SAVE_CONFIG",
		14: "SERVER_DELETE_CONFIG",
		15: "SERVER_LIST_CONFIGS",
		16: "SERVER_GET_CONFIG_HISTORY",
		17: "SERVER_ROLLBACK_CONFIG",
		18: "SERVER_CONFIG_CHANGE",
	}
	ServerMessageType_value = map[string]int32{
		"SERVER_UNKNOWN":            0,
		"SERVER_HANDSHAKE":          1,
		"SERVER_PONG":               2,
		"SERVER_CLOSE":              3,
		"SERVER_ERROR":              4,
		"SERVER_HEARTBEAT":          5,
		"SERVER_REGISTER_SERVICE":   6,
		"SERVER_UNREGISTER_SERVICE": 7,
		"SERVER_REGISTER_NODE":      8,
		"SERVER_UNREGISTER_NODE":    9,
		"SERVER_DISCOVER_NODES":     10,
		"SERVER_SERVICE_CHANGE":     11,
		"SERVER_GET_CONFIG":         12,
		"SERVER_SAVE_CONFIG":        13,
		"SERVER_DELETE_CONFIG":      14,
		"SERVER_LIST_CONFIGS":       15,
		"SERVER_GET_CONFIG_HISTORY": 16,
		"SERVER_ROLLBACK_CONFIG":    17,
		"SERVER_CONFIG_CHANGE":      18,
	}
)

func (x ServerMessageType) Enum() *ServerMessageType {
	p := new(ServerMessageType)
	*p = x
	return p
}

func (x ServerMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_stream_proto_enumTypes[1].Descriptor()
}

func (ServerMessageType) Type() protoreflect.EnumType {
	return &file_stream_proto_enumTypes[1]
}

func (x ServerMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerMessageType.Descriptor instead.
func (ServerMessageType) EnumDescriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{1}
}

// 客户端元数据（连接握手时使用）
type ClientMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`                                                                       // 客户端唯一标识（UUID，客户端生成）
	ClientVersion string                 `protobuf:"bytes,2,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`                                                             // 客户端版本（如 "1.0.0"）
	SdkVersion    string                 `protobuf:"bytes,3,opt,name=sdkVersion,proto3" json:"sdkVersion,omitempty"`                                                                   // SDK 版本
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`                                                                       // 编程语言（Java, Go, Python 等）
	StartTime     int64                  `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`                                                                    // 客户端启动时间戳（毫秒，用于判断客户端重启）
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 客户端标签（用于分组、灰度、环境标识等）
	Capabilities  []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                                               // 客户端能力列表（如 "compression", "encryption", "batch"）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMetadata) Reset() {
	*x = ClientMetadata{}
	mi := &file_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMetadata) ProtoMessage() {}

func (x *ClientMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMetadata.ProtoReflect.Descriptor instead.
func (*ClientMetadata) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMetadata) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientMetadata) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ClientMetadata) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ClientMetadata) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ClientMetadata) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ClientMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ClientMetadata) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// 连接握手请求（客户端建立连接后的第一条消息）
type ClientHandshake struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Metadata          *ClientMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`                    // 客户端元数据
	NamespaceId       string                 `protobuf:"bytes,2,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`              // 默认命名空间ID（可选）
	KeepAlive         bool                   `protobuf:"varint,3,opt,name=keepAlive,proto3" json:"keepAlive,omitempty"`                 // 是否启用保活（默认 true）
	KeepAliveInterval int32                  `protobuf:"varint,4,opt,name=keepAliveInterval,proto3" json:"keepAliveInterval,omitempty"` // 保活间隔（秒，默认 5）
	SubscribeTypes    []string               `protobuf:"bytes,5,rep,name=subscribeTypes,proto3" json:"subscribeTypes,omitempty"`        // 订阅类型列表：["registry", "config"]
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientHandshake) Reset() {
	*x = ClientHandshake{}
	mi := &file_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHandshake) ProtoMessage() {}

func (x *ClientHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHandshake.ProtoReflect.Descriptor instead.
func (*ClientHandshake) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHandshake) GetMetadata() *ClientMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClientHandshake) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ClientHandshake) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

func (x *ClientHandshake) GetKeepAliveInterval() int32 {
	if x != nil {
		return x.KeepAliveInterval
	}
	return 0
}

func (x *ClientHandshake) GetSubscribeTypes() []string {
	if x != nil {
		return x.SubscribeTypes
	}
	return nil
}

// 连接握手响应（服务端返回连接信息）
type ServerHandshake struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConnectionId      string                 `protobuf:"bytes,3,opt,name=connectionId,proto3" json:"connectionId,omitempty"`                                                                       // 服务端分配的连接ID（UUID）
	ServerTime        int64                  `protobuf:"varint,4,opt,name=serverTime,proto3" json:"serverTime,omitempty"`                                                                          // 服务端时间戳（毫秒，用于时间同步）
	HeartbeatInterval int32                  `protobuf:"varint,5,opt,name=heartbeatInterval,proto3" json:"heartbeatInterval,omitempty"`                                                            // 建议的心跳间隔（秒）
	ServerInfo        map[string]string      `protobuf:"bytes,6,rep,name=serverInfo,proto3" json:"serverInfo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 服务端信息（版本、能力等）
	TenantId          string                 `protobuf:"bytes,7,opt,name=tenantId,proto3" json:"tenantId,omitempty"`                                                                               // 服务端分配的租户ID（从认证信息中获取）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerHandshake) Reset() {
	*x = ServerHandshake{}
	mi := &file_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHandshake) ProtoMessage() {}

func (x *ServerHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHandshake.ProtoReflect.Descriptor instead.
func (*ServerHandshake) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{2}
}

func (x *ServerHandshake) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerHandshake) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerHandshake) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ServerHandshake) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ServerHandshake) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *ServerHandshake) GetServerInfo() map[string]string {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

func (x *ServerHandshake) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// Ping 消息（轻量级心跳，无业务数据）
type ClientPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`      // 客户端发送时间戳（毫秒）
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connectionId,proto3" json:"connectionId,omitempty"` // 连接ID（可选，用于验证）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPing) Reset() {
	*x = ClientPing{}
	mi := &file_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPing) ProtoMessage() {}

func (x *ClientPing) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPing.ProtoReflect.Descriptor instead.
func (*ClientPing) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{3}
}

func (x *ClientPing) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientPing) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// Pong 消息（Ping 响应）
type ServerPong struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`             // 服务端响应时间戳（毫秒）
	ClientTimestamp int64                  `protobuf:"varint,2,opt,name=clientTimestamp,proto3" json:"clientTimestamp,omitempty"` // 回显客户端时间戳（用于计算 RTT）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerPong) Reset() {
	*x = ServerPong{}
	mi := &file_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPong) ProtoMessage() {}

func (x *ServerPong) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPong.ProtoReflect.Descriptor instead.
func (*ServerPong) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{4}
}

func (x *ServerPong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ServerPong) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

// 服务端主动关闭连接通知
type ServerCloseNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`            // 关闭原因（如 "server_shutdown", "client_timeout", "auth_failed"）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`          // 详细消息
	GracePeriod   int32                  `protobuf:"varint,3,opt,name=gracePeriod,proto3" json:"gracePeriod,omitempty"` // 宽限期（秒，客户端应在此时间内完成清理）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCloseNotification) Reset() {
	*x = ServerCloseNotification{}
	mi := &file_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCloseNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCloseNotification) ProtoMessage() {}

func (x *ServerCloseNotification) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCloseNotification.ProtoReflect.Descriptor instead.
func (*ServerCloseNotification) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{5}
}

func (x *ServerCloseNotification) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ServerCloseNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerCloseNotification) GetGracePeriod() int32 {
	if x != nil {
		return x.GracePeriod
	}
	return 0
}

// 通用错误响应
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                                                                 // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                           // 错误消息
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 错误详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ClientMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RequestId   string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`                                    // 请求ID（UUID，用于请求响应匹配）
	MessageType ClientMessageType      `protobuf:"varint,2,opt,name=messageType,proto3,enum=stream.ClientMessageType" json:"messageType,omitempty"` // 消息类型（便于路由、日志、监控）
	// Types that are valid to be assigned to Message:
	//
	//	*ClientMessage_Handshake
	//	*ClientMessage_Ping
	//	*ClientMessage_Heartbeat
	//	*ClientMessage_RegisterService
	//	*ClientMessage_UnregisterService
	//	*ClientMessage_RegisterNode
	//	*ClientMessage_UnregisterNode
	//	*ClientMessage_DiscoverNodes
	//	*ClientMessage_SubscribeServices
	//	*ClientMessage_SubscribeNamespace
	//	*ClientMessage_GetConfig
	//	*ClientMessage_SaveConfig
	//	*ClientMessage_DeleteConfig
	//	*ClientMessage_ListConfigs
	//	*ClientMessage_WatchConfig
	//	*ClientMessage_GetConfigHistory
	//	*ClientMessage_RollbackConfig
	Message       isClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{7}
}

func (x *ClientMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientMessage) GetMessageType() ClientMessageType {
	if x != nil {
		return x.MessageType
	}
	return ClientMessageType_CLIENT_UNKNOWN
}

func (x *ClientMessage) GetMessage() isClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientMessage) GetHandshake() *ClientHandshake {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *ClientPing {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientMessage) GetRegisterService() *Service {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_RegisterService); ok {
			return x.RegisterService
		}
	}
	return nil
}

func (x *ClientMessage) GetUnregisterService() *ServiceKey {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_UnregisterService); ok {
			return x.UnregisterService
		}
	}
	return nil
}

func (x *ClientMessage) GetRegisterNode() *Node {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_RegisterNode); ok {
			return x.RegisterNode
		}
	}
	return nil
}

func (x *ClientMessage) GetUnregisterNode() *NodeKey {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_UnregisterNode); ok {
			return x.UnregisterNode
		}
	}
	return nil
}

func (x *ClientMessage) GetDiscoverNodes() *DiscoverNodesRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_DiscoverNodes); ok {
			return x.DiscoverNodes
		}
	}
	return nil
}

func (x *ClientMessage) GetSubscribeServices() *SubscribeServicesRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_SubscribeServices); ok {
			return x.SubscribeServices
		}
	}
	return nil
}

func (x *ClientMessage) GetSubscribeNamespace() *SubscribeNamespaceRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_SubscribeNamespace); ok {
			return x.SubscribeNamespace
		}
	}
	return nil
}

func (x *ClientMessage) GetGetConfig() *ConfigKey {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_GetConfig); ok {
			return x.GetConfig
		}
	}
	return nil
}

func (x *ClientMessage) GetSaveConfig() *ConfigData {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_SaveConfig); ok {
			return x.SaveConfig
		}
	}
	return nil
}

func (x *ClientMessage) GetDeleteConfig() *ConfigKey {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_DeleteConfig); ok {
			return x.DeleteConfig
		}
	}
	return nil
}

func (x *ClientMessage) GetListConfigs() *ListConfigsRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_ListConfigs); ok {
			return x.ListConfigs
		}
	}
	return nil
}

func (x *ClientMessage) GetWatchConfig() *WatchConfigRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_WatchConfig); ok {
			return x.WatchConfig
		}
	}
	return nil
}

func (x *ClientMessage) GetGetConfigHistory() *GetConfigHistoryRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_GetConfigHistory); ok {
			return x.GetConfigHistory
		}
	}
	return nil
}

func (x *ClientMessage) GetRollbackConfig() *RollbackConfigRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_RollbackConfig); ok {
			return x.RollbackConfig
		}
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_Handshake struct {
	// ===== 连接管理 (messageType: 1-2) =====
	Handshake *ClientHandshake `protobuf:"bytes,3,opt,name=handshake,proto3,oneof"` // CLIENT_HANDSHAKE: 连接握手（建立连接后的第一条消息）
}

type ClientMessage_Ping struct {
	Ping *ClientPing `protobuf:"bytes,4,opt,name=ping,proto3,oneof"` // CLIENT_PING: Ping 心跳（轻量级，无业务数据）
}

type ClientMessage_Heartbeat struct {
	// ===== 服务注册发现 (messageType: 3-10，来自 registry.proto) =====
	Heartbeat *HeartbeatRequest `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"` // CLIENT_HEARTBEAT: 业务心跳（携带完整服务信息）
}

type ClientMessage_RegisterService struct {
	RegisterService *Service `protobuf:"bytes,11,opt,name=registerService,proto3,oneof"` // CLIENT_REGISTER_SERVICE: 注册服务
}

type ClientMessage_UnregisterService struct {
	UnregisterService *ServiceKey `protobuf:"bytes,12,opt,name=unregisterService,proto3,oneof"` // CLIENT_UNREGISTER_SERVICE: 注销服务
}

type ClientMessage_RegisterNode struct {
	RegisterNode *Node `protobuf:"bytes,13,opt,name=registerNode,proto3,oneof"` // CLIENT_REGISTER_NODE: 注册节点
}

type ClientMessage_UnregisterNode struct {
	UnregisterNode *NodeKey `protobuf:"bytes,14,opt,name=unregisterNode,proto3,oneof"` // CLIENT_UNREGISTER_NODE: 注销节点
}

type ClientMessage_DiscoverNodes struct {
	DiscoverNodes *DiscoverNodesRequest `protobuf:"bytes,15,opt,name=discoverNodes,proto3,oneof"` // CLIENT_DISCOVER_NODES: 发现服务节点
}

type ClientMessage_SubscribeServices struct {
	SubscribeServices *SubscribeServicesRequest `protobuf:"bytes,16,opt,name=subscribeServices,proto3,oneof"` // CLIENT_SUBSCRIBE_SERVICES: 订阅服务（指定服务名）
}

type ClientMessage_SubscribeNamespace struct {
	SubscribeNamespace *SubscribeNamespaceRequest `protobuf:"bytes,17,opt,name=subscribeNamespace,proto3,oneof"` // CLIENT_SUBSCRIBE_NAMESPACE: 订阅命名空间（所有服务）
}

type ClientMessage_GetConfig struct {
	// ===== 配置中心 (messageType: 11-17，来自 config.proto) =====
	GetConfig *ConfigKey `protobuf:"bytes,20,opt,name=getConfig,proto3,oneof"` // CLIENT_GET_CONFIG: 获取配置
}

type ClientMessage_SaveConfig struct {
	SaveConfig *ConfigData `protobuf:"bytes,21,opt,name=saveConfig,proto3,oneof"` // CLIENT_SAVE_CONFIG: 保存配置
}

type ClientMessage_DeleteConfig struct {
	DeleteConfig *ConfigKey `protobuf:"bytes,22,opt,name=deleteConfig,proto3,oneof"` // CLIENT_DELETE_CONFIG: 删除配置
}

type ClientMessage_ListConfigs struct {
	ListConfigs *ListConfigsRequest `protobuf:"bytes,23,opt,name=listConfigs,proto3,oneof"` // CLIENT_LIST_CONFIGS: 列出配置列表
}

type ClientMessage_WatchConfig struct {
	WatchConfig *WatchConfigRequest `protobuf:"bytes,24,opt,name=watchConfig,proto3,oneof"` // CLIENT_WATCH_CONFIG: 监听配置变更
}

type ClientMessage_GetConfigHistory struct {
	GetConfigHistory *GetConfigHistoryRequest `protobuf:"bytes,25,opt,name=getConfigHistory,proto3,oneof"` // CLIENT_GET_CONFIG_HISTORY: 获取配置历史
}

type ClientMessage_RollbackConfig struct {
	RollbackConfig *RollbackConfigRequest `protobuf:"bytes,26,opt,name=rollbackConfig,proto3,oneof"` // CLIENT_ROLLBACK_CONFIG: 回滚配置
}

func (*ClientMessage_Handshake) isClientMessage_Message() {}

func (*ClientMessage_Ping) isClientMessage_Message() {}

func (*ClientMessage_Heartbeat) isClientMessage_Message() {}

func (*ClientMessage_RegisterService) isClientMessage_Message() {}

func (*ClientMessage_UnregisterService) isClientMessage_Message() {}

func (*ClientMessage_RegisterNode) isClientMessage_Message() {}

func (*ClientMessage_UnregisterNode) isClientMessage_Message() {}

func (*ClientMessage_DiscoverNodes) isClientMessage_Message() {}

func (*ClientMessage_SubscribeServices) isClientMessage_Message() {}

func (*ClientMessage_SubscribeNamespace) isClientMessage_Message() {}

func (*ClientMessage_GetConfig) isClientMessage_Message() {}

func (*ClientMessage_SaveConfig) isClientMessage_Message() {}

func (*ClientMessage_DeleteConfig) isClientMessage_Message() {}

func (*ClientMessage_ListConfigs) isClientMessage_Message() {}

func (*ClientMessage_WatchConfig) isClientMessage_Message() {}

func (*ClientMessage_GetConfigHistory) isClientMessage_Message() {}

func (*ClientMessage_RollbackConfig) isClientMessage_Message() {}

type ServerMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RequestId   string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`                                    // 对应的请求ID（如果是服务端主动推送则为空）
	MessageType ServerMessageType      `protobuf:"varint,2,opt,name=messageType,proto3,enum=stream.ServerMessageType" json:"messageType,omitempty"` // 消息类型（便于路由、日志、监控）
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Handshake
	//	*ServerMessage_Pong
	//	*ServerMessage_Close
	//	*ServerMessage_Error
	//	*ServerMessage_Heartbeat
	//	*ServerMessage_RegisterService
	//	*ServerMessage_UnregisterService
	//	*ServerMessage_RegisterNode
	//	*ServerMessage_UnregisterNode
	//	*ServerMessage_DiscoverNodes
	//	*ServerMessage_ServiceChange
	//	*ServerMessage_GetConfig
	//	*ServerMessage_SaveConfig
	//	*ServerMessage_DeleteConfig
	//	*ServerMessage_ListConfigs
	//	*ServerMessage_GetConfigHistory
	//	*ServerMessage_RollbackConfig
	//	*ServerMessage_ConfigChange
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_stream_proto_rawDescGZIP(), []int{8}
}

func (x *ServerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerMessage) GetMessageType() ServerMessageType {
	if x != nil {
		return x.MessageType
	}
	return ServerMessageType_SERVER_UNKNOWN
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetHandshake() *ServerHandshake {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *ServerPong {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMessage) GetClose() *ServerCloseNotification {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetHeartbeat() *RegistryResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ServerMessage) GetRegisterService() *RegisterServiceResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_RegisterService); ok {
			return x.RegisterService
		}
	}
	return nil
}

func (x *ServerMessage) GetUnregisterService() *RegistryResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_UnregisterService); ok {
			return x.UnregisterService
		}
	}
	return nil
}

func (x *ServerMessage) GetRegisterNode() *RegisterNodeResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_RegisterNode); ok {
			return x.RegisterNode
		}
	}
	return nil
}

func (x *ServerMessage) GetUnregisterNode() *RegistryResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_UnregisterNode); ok {
			return x.UnregisterNode
		}
	}
	return nil
}

func (x *ServerMessage) GetDiscoverNodes() *DiscoverNodesResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_DiscoverNodes); ok {
			return x.DiscoverNodes
		}
	}
	return nil
}

func (x *ServerMessage) GetServiceChange() *ServiceChangeEvent {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ServiceChange); ok {
			return x.ServiceChange
		}
	}
	return nil
}

func (x *ServerMessage) GetGetConfig() *GetConfigResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_GetConfig); ok {
			return x.GetConfig
		}
	}
	return nil
}

func (x *ServerMessage) GetSaveConfig() *SaveConfigResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_SaveConfig); ok {
			return x.SaveConfig
		}
	}
	return nil
}

func (x *ServerMessage) GetDeleteConfig() *ConfigResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_DeleteConfig); ok {
			return x.DeleteConfig
		}
	}
	return nil
}

func (x *ServerMessage) GetListConfigs() *ListConfigsResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ListConfigs); ok {
			return x.ListConfigs
		}
	}
	return nil
}

func (x *ServerMessage) GetGetConfigHistory() *GetConfigHistoryResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_GetConfigHistory); ok {
			return x.GetConfigHistory
		}
	}
	return nil
}

func (x *ServerMessage) GetRollbackConfig() *RollbackConfigResponse {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_RollbackConfig); ok {
			return x.RollbackConfig
		}
	}
	return nil
}

func (x *ServerMessage) GetConfigChange() *ConfigChangeEvent {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ConfigChange); ok {
			return x.ConfigChange
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Handshake struct {
	// ===== 连接管理 (messageType: 1-4) =====
	Handshake *ServerHandshake `protobuf:"bytes,3,opt,name=handshake,proto3,oneof"` // SERVER_HANDSHAKE: 连接握手响应
}

type ServerMessage_Pong struct {
	Pong *ServerPong `protobuf:"bytes,4,opt,name=pong,proto3,oneof"` // SERVER_PONG: Pong 响应
}

type ServerMessage_Close struct {
	Close *ServerCloseNotification `protobuf:"bytes,5,opt,name=close,proto3,oneof"` // SERVER_CLOSE: 服务端主动关闭连接通知
}

type ServerMessage_Error struct {
	Error *ErrorResponse `protobuf:"bytes,6,opt,name=error,proto3,oneof"` // SERVER_ERROR: 通用错误响应
}

type ServerMessage_Heartbeat struct {
	// ===== 服务注册发现响应 (messageType: 5-11，来自 registry.proto) =====
	Heartbeat *RegistryResponse `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"` // SERVER_HEARTBEAT: 心跳响应
}

type ServerMessage_RegisterService struct {
	RegisterService *RegisterServiceResponse `protobuf:"bytes,11,opt,name=registerService,proto3,oneof"` // SERVER_REGISTER_SERVICE: 注册服务响应
}

type ServerMessage_UnregisterService struct {
	UnregisterService *RegistryResponse `protobuf:"bytes,12,opt,name=unregisterService,proto3,oneof"` // SERVER_UNREGISTER_SERVICE: 注销服务响应
}

type ServerMessage_RegisterNode struct {
	RegisterNode *RegisterNodeResponse `protobuf:"bytes,13,opt,name=registerNode,proto3,oneof"` // SERVER_REGISTER_NODE: 注册节点响应
}

type ServerMessage_UnregisterNode struct {
	UnregisterNode *RegistryResponse `protobuf:"bytes,14,opt,name=unregisterNode,proto3,oneof"` // SERVER_UNREGISTER_NODE: 注销节点响应
}

type ServerMessage_DiscoverNodes struct {
	DiscoverNodes *DiscoverNodesResponse `protobuf:"bytes,15,opt,name=discoverNodes,proto3,oneof"` // SERVER_DISCOVER_NODES: 发现服务节点响应
}

type ServerMessage_ServiceChange struct {
	ServiceChange *ServiceChangeEvent `protobuf:"bytes,16,opt,name=serviceChange,proto3,oneof"` // SERVER_SERVICE_CHANGE: 服务变更事件（服务端主动推送）
}

type ServerMessage_GetConfig struct {
	// ===== 配置中心响应 (messageType: 12-18，来自 config.proto) =====
	GetConfig *GetConfigResponse `protobuf:"bytes,20,opt,name=getConfig,proto3,oneof"` // SERVER_GET_CONFIG: 获取配置响应
}

type ServerMessage_SaveConfig struct {
	SaveConfig *SaveConfigResponse `protobuf:"bytes,21,opt,name=saveConfig,proto3,oneof"` // SERVER_SAVE_CONFIG: 保存配置响应
}

type ServerMessage_DeleteConfig struct {
	DeleteConfig *ConfigResponse `protobuf:"bytes,22,opt,name=deleteConfig,proto3,oneof"` // SERVER_DELETE_CONFIG: 删除配置响应
}

type ServerMessage_ListConfigs struct {
	ListConfigs *ListConfigsResponse `protobuf:"bytes,23,opt,name=listConfigs,proto3,oneof"` // SERVER_LIST_CONFIGS: 列出配置列表响应
}

type ServerMessage_GetConfigHistory struct {
	GetConfigHistory *GetConfigHistoryResponse `protobuf:"bytes,24,opt,name=getConfigHistory,proto3,oneof"` // SERVER_GET_CONFIG_HISTORY: 获取配置历史响应
}

type ServerMessage_RollbackConfig struct {
	RollbackConfig *RollbackConfigResponse `protobuf:"bytes,25,opt,name=rollbackConfig,proto3,oneof"` // SERVER_ROLLBACK_CONFIG: 回滚配置响应
}

type ServerMessage_ConfigChange struct {
	ConfigChange *ConfigChangeEvent `protobuf:"bytes,26,opt,name=configChange,proto3,oneof"` // SERVER_CONFIG_CHANGE: 配置变更事件（服务端主动推送）
}

func (*ServerMessage_Handshake) isServerMessage_Message() {}

func (*ServerMessage_Pong) isServerMessage_Message() {}

func (*ServerMessage_Close) isServerMessage_Message() {}

func (*ServerMessage_Error) isServerMessage_Message() {}

func (*ServerMessage_Heartbeat) isServerMessage_Message() {}

func (*ServerMessage_RegisterService) isServerMessage_Message() {}

func (*ServerMessage_UnregisterService) isServerMessage_Message() {}

func (*ServerMessage_RegisterNode) isServerMessage_Message() {}

func (*ServerMessage_UnregisterNode) isServerMessage_Message() {}

func (*ServerMessage_DiscoverNodes) isServerMessage_Message() {}

func (*ServerMessage_ServiceChange) isServerMessage_Message() {}

func (*ServerMessage_GetConfig) isServerMessage_Message() {}

func (*ServerMessage_SaveConfig) isServerMessage_Message() {}

func (*ServerMessage_DeleteConfig) isServerMessage_Message() {}

func (*ServerMessage_ListConfigs) isServerMessage_Message() {}

func (*ServerMessage_GetConfigHistory) isServerMessage_Message() {}

func (*ServerMessage_RollbackConfig) isServerMessage_Message() {}

func (*ServerMessage_ConfigChange) isServerMessage_Message() {}

var File_stream_proto protoreflect.FileDescriptor

const file_stream_proto_rawDesc = "" +
	"\n" +
	"\fstream.proto\x12\x06stream\x1a\x0eregistry.proto\x1a\fconfig.proto\"\xc7\x02\n" +
	"\x0eClientMetadata\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12$\n" +
	"\rclientVersion\x18\x02 \x01(\tR\rclientVersion\x12\x1e\n" +
	"\n" +
	"sdkVersion\x18\x03 \x01(\tR\n" +
	"sdkVersion\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\x03R\tstartTime\x12:\n" +
	"\x06labels\x18\x06 \x03(\v2\".stream.ClientMetadata.LabelsEntryR\x06labels\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x0fClientHandshake\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.stream.ClientMetadataR\bmetadata\x12 \n" +
	"\vnamespaceId\x18\x02 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tkeepAlive\x18\x03 \x01(\bR\tkeepAlive\x12,\n" +
	"\x11keepAliveInterval\x18\x04 \x01(\x05R\x11keepAliveInterval\x12&\n" +
	"\x0esubscribeTypes\x18\x05 \x03(\tR\x0esubscribeTypes\"\xdb\x02\n" +
	"\x0fServerHandshake\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\fconnectionId\x18\x03 \x01(\tR\fconnectionId\x12\x1e\n" +
	"\n" +
	"serverTime\x18\x04 \x01(\x03R\n" +
	"serverTime\x12,\n" +
	"\x11heartbeatInterval\x18\x05 \x01(\x05R\x11heartbeatInterval\x12G\n" +
	"\n" +
	"serverInfo\x18\x06 \x03(\v2'.stream.ServerHandshake.ServerInfoEntryR\n" +
	"serverInfo\x12\x1a\n" +
	"\btenantId\x18\a \x01(\tR\btenantId\x1a=\n" +
	"\x0fServerInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\n" +
	"ClientPing\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\"\n" +
	"\fconnectionId\x18\x02 \x01(\tR\fconnectionId\"T\n" +
	"\n" +
	"ServerPong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12(\n" +
	"\x0fclientTimestamp\x18\x02 \x01(\x03R\x0fclientTimestamp\"m\n" +
	"\x17ServerCloseNotification\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vgracePeriod\x18\x03 \x01(\x05R\vgracePeriod\"\xb7\x01\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\adetails\x18\x03 \x03(\v2\".stream.ErrorResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\t\n" +
	"\rClientMessage\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12;\n" +
	"\vmessageType\x18\x02 \x01(\x0e2\x19.stream.ClientMessageTypeR\vmessageType\x127\n" +
	"\thandshake\x18\x03 \x01(\v2\x17.stream.ClientHandshakeH\x00R\thandshake\x12(\n" +
	"\x04ping\x18\x04 \x01(\v2\x12.stream.ClientPingH\x00R\x04ping\x12:\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2\x1a.registry.HeartbeatRequestH\x00R\theartbeat\x12=\n" +
	"\x0fregisterService\x18\v \x01(\v2\x11.registry.ServiceH\x00R\x0fregisterService\x12D\n" +
	"\x11unregisterService\x18\f \x01(\v2\x14.registry.ServiceKeyH\x00R\x11unregisterService\x124\n" +
	"\fregisterNode\x18\r \x01(\v2\x0e.registry.NodeH\x00R\fregisterNode\x12;\n" +
	"\x0eunregisterNode\x18\x0e \x01(\v2\x11.registry.NodeKeyH\x00R\x0eunregisterNode\x12F\n" +
	"\rdiscoverNodes\x18\x0f \x01(\v2\x1e.registry.DiscoverNodesRequestH\x00R\rdiscoverNodes\x12R\n" +
	"\x11subscribeServices\x18\x10 \x01(\v2\".registry.SubscribeServicesRequestH\x00R\x11subscribeServices\x12U\n" +
	"\x12subscribeNamespace\x18\x11 \x01(\v2#.registry.SubscribeNamespaceRequestH\x00R\x12subscribeNamespace\x121\n" +
	"\tgetConfig\x18\x14 \x01(\v2\x11.config.ConfigKeyH\x00R\tgetConfig\x124\n" +
	"\n" +
	"saveConfig\x18\x15 \x01(\v2\x12.config.ConfigDataH\x00R\n" +
	"saveConfig\x127\n" +
	"\fdeleteConfig\x18\x16 \x01(\v2\x11.config.ConfigKeyH\x00R\fdeleteConfig\x12>\n" +
	"\vlistConfigs\x18\x17 \x01(\v2\x1a.config.ListConfigsRequestH\x00R\vlistConfigs\x12>\n" +
	"\vwatchConfig\x18\x18 \x01(\v2\x1a.config.WatchConfigRequestH\x00R\vwatchConfig\x12M\n" +
	"\x10getConfigHistory\x18\x19 \x01(\v2\x1f.config.GetConfigHistoryRequestH\x00R\x10getConfigHistory\x12G\n" +
	"\x0erollbackConfig\x18\x1a \x01(\v2\x1d.config.RollbackConfigRequestH\x00R\x0erollbackConfigB\t\n" +
	"\amessage\"\x85\n" +
	"\n" +
	"\rServerMessage\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12;\n" +
	"\vmessageType\x18\x02 \x01(\x0e2\x19.stream.ServerMessageTypeR\vmessageType\x127\n" +
	"\thandshake\x18\x03 \x01(\v2\x17.stream.ServerHandshakeH\x00R\thandshake\x12(\n" +
	"\x04pong\x18\x04 \x01(\v2\x12.stream.ServerPongH\x00R\x04pong\x127\n" +
	"\x05close\x18\x05 \x01(\v2\x1f.stream.ServerCloseNotificationH\x00R\x05close\x12-\n" +
	"\x05error\x18\x06 \x01(\v2\x15.stream.ErrorResponseH\x00R\x05error\x12:\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2\x1a.registry.RegistryResponseH\x00R\theartbeat\x12M\n" +
	"\x0fregisterService\x18\v \x01(\v2!.registry.RegisterServiceResponseH\x00R\x0fregisterService\x12J\n" +
	"\x11unregisterService\x18\f \x01(\v2\x1a.registry.RegistryResponseH\x00R\x11unregisterService\x12D\n" +
	"\fregisterNode\x18\r \x01(\v2\x1e.registry.RegisterNodeResponseH\x00R\fregisterNode\x12D\n" +
	"\x0eunregisterNode\x18\x0e \x01(\v2\x1a.registry.RegistryResponseH\x00R\x0eunregisterNode\x12G\n" +
	"\rdiscoverNodes\x18\x0f \x01(\v2\x1f.registry.DiscoverNodesResponseH\x00R\rdiscoverNodes\x12D\n" +
	"\rserviceChange\x18\x10 \x01(\v2\x1c.registry.ServiceChangeEventH\x00R\rserviceChange\x129\n" +
	"\tgetConfig\x18\x14 \x01(\v2\x19.config.GetConfigResponseH\x00R\tgetConfig\x12<\n" +
	"\n" +
	"saveConfig\x18\x15 \x01(\v2\x1a.config.SaveConfigResponseH\x00R\n" +
	"saveConfig\x12<\n" +
	"\fdeleteConfig\x18\x16 \x01(\v2\x16.config.ConfigResponseH\x00R\fdeleteConfig\x12?\n" +
	"\vlistConfigs\x18\x17 \x01(\v2\x1b.config.ListConfigsResponseH\x00R\vlistConfigs\x12N\n" +
	"\x10getConfigHistory\x18\x18 \x01(\v2 .config.GetConfigHistoryResponseH\x00R\x10getConfigHistory\x12H\n" +
	"\x0erollbackConfig\x18\x19 \x01(\v2\x1e.config.RollbackConfigResponseH\x00R\x0erollbackConfig\x12?\n" +
	"\fconfigChange\x18\x1a \x01(\v2\x19.config.ConfigChangeEventH\x00R\fconfigChangeB\t\n" +
	"\amessage*\xe6\x03\n" +
	"\x11ClientMessageType\x12\x12\n" +
	"\x0eCLIENT_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10CLIENT_HANDSHAKE\x10\x01\x12\x0f\n" +
	"\vCLIENT_PING\x10\x02\x12\x14\n" +
	"\x10CLIENT_HEARTBEAT\x10\x03\x12\x1b\n" +
	"\x17CLIENT_REGISTER_SERVICE\x10\x04\x12\x1d\n" +
	"\x19CLIENT_UNREGISTER_SERVICE\x10\x05\x12\x18\n" +
	"\x14CLIENT_REGISTER_NODE\x10\x06\x12\x1a\n" +
	"\x16CLIENT_UNREGISTER_NODE\x10\a\x12\x19\n" +
	"\x15CLIENT_DISCOVER_NODES\x10\b\x12\x1d\n" +
	"\x19CLIENT_SUBSCRIBE_SERVICES\x10\t\x12\x1e\n" +
	"\x1aCLIENT_SUBSCRIBE_NAMESPACE\x10\n" +
	"\x12\x15\n" +
	"\x11CLIENT_GET_CONFIG\x10\v\x12\x16\n" +
	"\x12CLIENT_SAVE_CONFIG\x10\f\x12\x18\n" +
	"\x14CLIENT_DELETE_CONFIG\x10\r\x12\x17\n" +
	"\x13CLIENT_LIST_CONFIGS\x10\x0e\x12\x17\n" +
	"\x13CLIENT_WATCH_CONFIG\x10\x0f\x12\x1d\n" +
	"\x19CLIENT_GET_CONFIG_HISTORY\x10\x10\x12\x1a\n" +
	"\x16CLIENT_ROLLBACK_CONFIG\x10\x11*\xe7\x03\n" +
	"\x11ServerMessageType\x12\x12\n" +
	"\x0eSERVER_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10SERVER_HANDSHAKE\x10\x01\x12\x0f\n" +
	"\vSERVER_PONG\x10\x02\x12\x10\n" +
	"\fSERVER_CLOSE\x10\x03\x12\x10\n" +
	"\fSERVER_ERROR\x10\x04\x12\x14\n" +
	"\x10SERVER_HEARTBEAT\x10\x05\x12\x1b\n" +
	"\x17SERVER_REGISTER_SERVICE\x10\x06\x12\x1d\n" +
	"\x19SERVER_UNREGISTER_SERVICE\x10\a\x12\x18\n" +
	"\x14SERVER_REGISTER_NODE\x10\b\x12\x1a\n" +
	"\x16SERVER_UNREGISTER_NODE\x10\t\x12\x19\n" +
	"\x15SERVER_DISCOVER_NODES\x10\n" +
	"\x12\x19\n" +
	"\x15SERVER_SERVICE_CHANGE\x10\v\x12\x15\n" +
	"\x11SERVER_GET_CONFIG\x10\f\x12\x16\n" +
	"\x12SERVER_SAVE_CONFIG\x10\r\x12\x18\n" +
	"\x14SERVER_DELETE_CONFIG\x10\x0e\x12\x17\n" +
	"\x13SERVER_LIST_CONFIGS\x10\x0f\x12\x1d\n" +
	"\x19SERVER_GET_CONFIG_HISTORY\x10\x10\x12\x1a\n" +
	"\x16SERVER_ROLLBACK_CONFIG\x10\x11\x12\x18\n" +
	"\x14SERVER_CONFIG_CHANGE\x10\x122R\n" +
	"\x13ServiceCenterStream\x12;\n" +
	"\aConnect\x12\x15.stream.ClientMessage\x1a\x15.stream.ServerMessage(\x010\x01B3Z1gateway/internal/servicecenter/server/proto;protob\x06proto3"

var (
	file_stream_proto_rawDescOnce sync.Once
	file_stream_proto_rawDescData []byte
)

func file_stream_proto_rawDescGZIP() []byte {
	file_stream_proto_rawDescOnce.Do(func() {
		file_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_proto_rawDesc), len(file_stream_proto_rawDesc)))
	})
	return file_stream_proto_rawDescData
}

var file_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_stream_proto_goTypes = []any{
	(ClientMessageType)(0),            // 0: stream.ClientMessageType
	(ServerMessageType)(0),            // 1: stream.ServerMessageType
	(*ClientMetadata)(nil),            // 2: stream.ClientMetadata
	(*ClientHandshake)(nil),           // 3: stream.ClientHandshake
	(*ServerHandshake)(nil),           // 4: stream.ServerHandshake
	(*ClientPing)(nil),                // 5: stream.ClientPing
	(*ServerPong)(nil),                // 6: stream.ServerPong
	(*ServerCloseNotification)(nil),   // 7: stream.ServerCloseNotification
	(*ErrorResponse)(nil),             // 8: stream.ErrorResponse
	(*ClientMessage)(nil),             // 9: stream.ClientMessage
	(*ServerMessage)(nil),             // 10: stream.ServerMessage
	nil,                               // 11: stream.ClientMetadata.LabelsEntry
	nil,                               // 12: stream.ServerHandshake.ServerInfoEntry
	nil,                               // 13: stream.ErrorResponse.DetailsEntry
	(*HeartbeatRequest)(nil),          // 14: registry.HeartbeatRequest
	(*Service)(nil),                   // 15: registry.Service
	(*ServiceKey)(nil),                // 16: registry.ServiceKey
	(*Node)(nil),                      // 17: registry.Node
	(*NodeKey)(nil),                   // 18: registry.NodeKey
	(*DiscoverNodesRequest)(nil),      // 19: registry.DiscoverNodesRequest
	(*SubscribeServicesRequest)(nil),  // 20: registry.SubscribeServicesRequest
	(*SubscribeNamespaceRequest)(nil), // 21: registry.SubscribeNamespaceRequest
	(*ConfigKey)(nil),                 // 22: config.ConfigKey
	(*ConfigData)(nil),                // 23: config.ConfigData
	(*ListConfigsRequest)(nil),        // 24: config.ListConfigsRequest
	(*WatchConfigRequest)(nil),        // 25: config.WatchConfigRequest
	(*GetConfigHistoryRequest)(nil),   // 26: config.GetConfigHistoryRequest
	(*RollbackConfigRequest)(nil),     // 27: config.RollbackConfigRequest
	(*RegistryResponse)(nil),          // 28: registry.RegistryResponse
	(*RegisterServiceResponse)(nil),   // 29: registry.RegisterServiceResponse
	(*RegisterNodeResponse)(nil),      // 30: registry.RegisterNodeResponse
	(*DiscoverNodesResponse)(nil),     // 31: registry.DiscoverNodesResponse
	(*ServiceChangeEvent)(nil),        // 32: registry.ServiceChangeEvent
	(*GetConfigResponse)(nil),         // 33: config.GetConfigResponse
	(*SaveConfigResponse)(nil),        // 34: config.SaveConfigResponse
	(*ConfigResponse)(nil),            // 35: config.ConfigResponse
	(*ListConfigsResponse)(nil),       // 36: config.ListConfigsResponse
	(*GetConfigHistoryResponse)(nil),  // 37: config.GetConfigHistoryResponse
	(*RollbackConfigResponse)(nil),    // 38: config.RollbackConfigResponse
	(*ConfigChangeEvent)(nil),         // 39: config.ConfigChangeEvent
}
var file_stream_proto_depIdxs = []int32{
	11, // 0: stream.ClientMetadata.labels:type_name -> stream.ClientMetadata.LabelsEntry
	2,  // 1: stream.ClientHandshake.metadata:type_name -> stream.ClientMetadata
	12, // 2: stream.ServerHandshake.serverInfo:type_name -> stream.ServerHandshake.ServerInfoEntry
	13, // 3: stream.ErrorResponse.details:type_name -> stream.ErrorResponse.DetailsEntry
	0,  // 4: stream.ClientMessage.messageType:type_name -> stream.ClientMessageType
	3,  // 5: stream.ClientMessage.handshake:type_name -> stream.ClientHandshake
	5,  // 6: stream.ClientMessage.ping:type_name -> stream.ClientPing
	14, // 7: stream.ClientMessage.heartbeat:type_name -> registry.HeartbeatRequest
	15, // 8: stream.ClientMessage.registerService:type_name -> registry.Service
	16, // 9: stream.ClientMessage.unregisterService:type_name -> registry.ServiceKey
	17, // 10: stream.ClientMessage.registerNode:type_name -> registry.Node
	18, // 11: stream.ClientMessage.unregisterNode:type_name -> registry.NodeKey
	19, // 12: stream.ClientMessage.discoverNodes:type_name -> registry.DiscoverNodesRequest
	20, // 13: stream.ClientMessage.subscribeServices:type_name -> registry.SubscribeServicesRequest
	21, // 14: stream.ClientMessage.subscribeNamespace:type_name -> registry.SubscribeNamespaceRequest
	22, // 15: stream.ClientMessage.getConfig:type_name -> config.ConfigKey
	23, // 16: stream.ClientMessage.saveConfig:type_name -> config.ConfigData
	22, // 17: stream.ClientMessage.deleteConfig:type_name -> config.ConfigKey
	24, // 18: stream.ClientMessage.listConfigs:type_name -> config.ListConfigsRequest
	25, // 19: stream.ClientMessage.watchConfig:type_name -> config.WatchConfigRequest
	26, // 20: stream.ClientMessage.getConfigHistory:type_name -> config.GetConfigHistoryRequest
	27, // 21: stream.ClientMessage.rollbackConfig:type_name -> config.RollbackConfigRequest
	1,  // 22: stream.ServerMessage.messageType:type_name -> stream.ServerMessageType
	4,  // 23: stream.ServerMessage.handshake:type_name -> stream.ServerHandshake
	6,  // 24: stream.ServerMessage.pong:type_name -> stream.ServerPong
	7,  // 25: stream.ServerMessage.close:type_name -> stream.ServerCloseNotification
	8,  // 26: stream.ServerMessage.error:type_name -> stream.ErrorResponse
	28, // 27: stream.ServerMessage.heartbeat:type_name -> registry.RegistryResponse
	29, // 28: stream.ServerMessage.registerService:type_name -> registry.RegisterServiceResponse
	28, // 29: stream.ServerMessage.unregisterService:type_name -> registry.RegistryResponse
	30, // 30: stream.ServerMessage.registerNode:type_name -> registry.RegisterNodeResponse
	28, // 31: stream.ServerMessage.unregisterNode:type_name -> registry.RegistryResponse
	31, // 32: stream.ServerMessage.discoverNodes:type_name -> registry.DiscoverNodesResponse
	32, // 33: stream.ServerMessage.serviceChange:type_name -> registry.ServiceChangeEvent
	33, // 34: stream.ServerMessage.getConfig:type_name -> config.GetConfigResponse
	34, // 35: stream.ServerMessage.saveConfig:type_name -> config.SaveConfigResponse
	35, // 36: stream.ServerMessage.deleteConfig:type_name -> config.ConfigResponse
	36, // 37: stream.ServerMessage.listConfigs:type_name -> config.ListConfigsResponse
	37, // 38: stream.ServerMessage.getConfigHistory:type_name -> config.GetConfigHistoryResponse
	38, // 39: stream.ServerMessage.rollbackConfig:type_name -> config.RollbackConfigResponse
	39, // 40: stream.ServerMessage.configChange:type_name -> config.ConfigChangeEvent
	9,  // 41: stream.ServiceCenterStream.Connect:input_type -> stream.ClientMessage
	10, // 42: stream.ServiceCenterStream.Connect:output_type -> stream.ServerMessage
	42, // [42:43] is the sub-list for method output_type
	41, // [41:42] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_stream_proto_init() }
func file_stream_proto_init() {
	if File_stream_proto != nil {
		return
	}
	file_registry_proto_init()
	file_config_proto_init()
	file_stream_proto_msgTypes[7].OneofWrappers = []any{
		(*ClientMessage_Handshake)(nil),
		(*ClientMessage_Ping)(nil),
		(*ClientMessage_Heartbeat)(nil),
		(*ClientMessage_RegisterService)(nil),
		(*ClientMessage_UnregisterService)(nil),
		(*ClientMessage_RegisterNode)(nil),
		(*ClientMessage_UnregisterNode)(nil),
		(*ClientMessage_DiscoverNodes)(nil),
		(*ClientMessage_SubscribeServices)(nil),
		(*ClientMessage_SubscribeNamespace)(nil),
		(*ClientMessage_GetConfig)(nil),
		(*ClientMessage_SaveConfig)(nil),
		(*ClientMessage_DeleteConfig)(nil),
		(*ClientMessage_ListConfigs)(nil),
		(*ClientMessage_WatchConfig)(nil),
		(*ClientMessage_GetConfigHistory)(nil),
		(*ClientMessage_RollbackConfig)(nil),
	}
	file_stream_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerMessage_Handshake)(nil),
		(*ServerMessage_Pong)(nil),
		(*ServerMessage_Close)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_Heartbeat)(nil),
		(*ServerMessage_RegisterService)(nil),
		(*ServerMessage_UnregisterService)(nil),
		(*ServerMessage_RegisterNode)(nil),
		(*ServerMessage_UnregisterNode)(nil),
		(*ServerMessage_DiscoverNodes)(nil),
		(*ServerMessage_ServiceChange)(nil),
		(*ServerMessage_GetConfig)(nil),
		(*ServerMessage_SaveConfig)(nil),
		(*ServerMessage_DeleteConfig)(nil),
		(*ServerMessage_ListConfigs)(nil),
		(*ServerMessage_GetConfigHistory)(nil),
		(*ServerMessage_RollbackConfig)(nil),
		(*ServerMessage_ConfigChange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_proto_rawDesc), len(file_stream_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_proto_goTypes,
		DependencyIndexes: file_stream_proto_depIdxs,
		EnumInfos:         file_stream_proto_enumTypes,
		MessageInfos:      file_stream_proto_msgTypes,
	}.Build()
	File_stream_proto = out.File
	file_stream_proto_goTypes = nil
	file_stream_proto_depIdxs = nil
}
