# Registry Server Configuration

# 服务器配置
server:
  # HTTP服务器配置
  http:
    host: "0.0.0.0"
    port: 8080
    readTimeout: 30s
    writeTimeout: 30s
    idleTimeout: 60s
    maxHeaderBytes: 1048576  # 1MB
    enableCORS: true
    cors:
      allowedOrigins: ["*"]
      allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowedHeaders: ["*"]
      exposedHeaders: []
      allowCredentials: false
      maxAge: 12h
    enableGzip: true
    enableRequestLog: true
  
  # gRPC服务器配置
  grpc:
    enabled: false
    host: "0.0.0.0"
    port: 9090
    connectionTimeout: 30s
    maxRecvMsgSize: 4194304  # 4MB
    maxSendMsgSize: 4194304  # 4MB
    enableTLS: false
    tls:
      certFile: ""
      keyFile: ""
      caFile: ""
      clientAuth: "NoClientCert"
  
  # WebSocket配置
  websocket:
    enabled: true
    path: "/ws"
    readBufferSize: 1024
    writeBufferSize: 1024
    handshakeTimeout: 10s
    pingInterval: 30s
    pongTimeout: 60s
    maxConnections: 1000
  
  # 优雅关闭配置
  gracefulShutdown:
    timeout: 30s
    waitForConnections: true

# 数据库配置
database:
  type: "mysql"
  dsn: "root:password@tcp(localhost:3306)/registry?charset=utf8mb4&parseTime=True&loc=Local"
  maxOpenConns: 100
  maxIdleConns: 10
  connMaxLifetime: 1h
  connMaxIdleTime: 10m
  enableLog: true
  logLevel: "warn"
  slowThreshold: 200ms

# 健康检查配置
healthCheck:
  enabled: true
  interval: 30s
  timeout: 5s
  maxRetries: 3
  retryInterval: 5s
  concurrentChecks: 10
  failureThreshold: 3
  successThreshold: 1
  defaultPath: "/health"
  enableTCPCheck: true
  enableHTTPCheck: true

# 事件系统配置
event:
  enabled: true
  bufferSize: 1000
  workerCount: 5
  batchSize: 100
  batchTimeout: 1s
  maxSubscribers: 100
  subscriberTimeout: 30s
  enablePersistence: true
  retentionPeriod: 168h  # 7 days
  cleanupInterval: 1h

# 外部注册中心配置
external:
  enabled: false
  refreshInterval: 30s
  poolSize: 10
  connectTimeout: 10s
  readTimeout: 30s
  writeTimeout: 30s
  maxRetries: 3
  retryInterval: 5s
  enableFailover: true
  failoverCheckInterval: 30s
  enableSync: false
  syncInterval: 5m
  syncBatchSize: 100
  conflictResolution: "primary_wins"

# 日志配置
logging:
  level: "info"
  format: "json"
  output: ["stdout"]
  file:
    filename: "logs/registry.log"
    maxSize: 100  # MB
    maxBackups: 10
    maxAge: 30  # days
    compress: true
    localTime: true
  enableStructured: true
  enableCaller: true
  enableStacktrace: false

# 监控配置
monitoring:
  enabled: true
  prometheus:
    enabled: true
    host: "0.0.0.0"
    port: 9091
    path: "/metrics"
    namespace: "registry"
    subsystem: "server"
  metricsInterval: 15s
  enableProfiling: false
  profilingPort: 6060

# 安全配置
security:
  enableAuth: false
  jwt:
    enabled: false
    secret: "your-secret-key-here"
    expirationTime: 24h
    refreshTime: 168h  # 7 days
    algorithm: "HS256"
    issuer: "registry-server"
  apiKey:
    enabled: false
    headerName: "X-API-Key"
    queryName: "api_key"
    validKeys: []
  rateLimit:
    enabled: false
    requestsPerSecond: 100
    burst: 200
    strategy: "fixed_window"
    storage: "memory"
    redis:
      addr: "localhost:6379"
      password: ""
      db: 0
      poolSize: 10
      minIdleConns: 5
      dialTimeout: 5s
      readTimeout: 3s
      writeTimeout: 3s
  ipWhitelist: []
  ipBlacklist: []
