/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GExport: typeof import('./../components/gexport-import/GExport.vue')['default']
    GFieldset: typeof import('./../components/gfieldset/GFieldset.vue')['default']
    GIcon: typeof import('./../components/gicon/GIcon.vue')['default']
    GImport: typeof import('./../components/gexport-import/GImport.vue')['default']
    GRestfulApi: typeof import('./../components/grestful-api/GRestfulApi.vue')['default']
    GRichText: typeof import('./../components/grichtext/GRichText.vue')['default']
    GToolbar: typeof import('./../components/toolbar/GToolbar.vue')['default']
    KeyValueEditor: typeof import('./../components/grestful-api/KeyValueEditor.vue')['default']
    LanguageSwitcher: typeof import('./../components/common/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteViewLoadingMask: typeof import('./../components/RouteViewLoadingMask.vue')['default']
    RsDataForm: typeof import('./../components/form/rs-data/RsDataForm.vue')['default']
    RsDataFormFields: typeof import('./../components/form/rs-data/RsDataFormFields.vue')['default']
    RsDataFormModal: typeof import('./../components/form/rs-data/RsDataFormModal.vue')['default']
    RsGrid: typeof import('./../components/rs-grid/RsGrid.vue')['default']
    RsSearchForm: typeof import('./../components/form/rs-search/RsSearchForm.vue')['default']
    RsTableAnalyticsPanel: typeof import('./../components/rs-table-analytics/RsTableAnalyticsPanel.vue')['default']
    ThemeSwitcher: typeof import('./../components/common/ThemeSwitcher.vue')['default']
    ToolbarBtnFace: typeof import('./../components/toolbar/ToolbarBtnFace.vue')['default']
    ToolbarButton: typeof import('./../components/toolbar/ToolbarButton.vue')['default']
  }
}
