/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GCard: typeof import('./../components/gcard/GCard.vue')['default']
    GCodeMirror: typeof import('./../components/gcodemirror/GCodeMirror.vue')['default']
    GContext: typeof import('./../components/gcontext/GContext.vue')['default']
    GDataForm: typeof import('./../components/form/data/GDataForm.vue')['default']
    GDataFormModal: typeof import('./../components/form/data/GDataFormModal.vue')['default']
    GDialog: typeof import('./../components/gdialog/GDialog.vue')['default']
    GDrawer: typeof import('./../components/gdrawer/GDrawer.vue')['default']
    GDropdown: typeof import('./../components/gdropdown/GDropdown.vue')['default']
    GEllipsis: typeof import('./../components/gellipsis/GEllipsis.vue')['default']
    GExport: typeof import('./../components/gexport-import/GExport.vue')['default']
    GFieldset: typeof import('./../components/gfieldset/GFieldset.vue')['default']
    GFileUpload: typeof import('./../components/gfile/GFileUpload.vue')['default']
    GGrid: typeof import('./../components/grid/GGrid.vue')['default']
    'GGrid.fromTranscript': typeof import('./../components/rs-grid/GGrid.from-transcript.vue')['default']
    GIcon: typeof import('./../components/gicon/GIcon.vue')['default']
    GImport: typeof import('./../components/gexport-import/GImport.vue')['default']
    GlobalCustomRenderProvider: typeof import('./../components/gcustom-render/GlobalCustomRenderProvider.vue')['default']
    GModal: typeof import('./../components/gmodal/GModal.vue')['default']
    GPane: typeof import('./../components/gpane/GPane.vue')['default']
    GRestfulApi: typeof import('./../components/grestful-api/GRestfulApi.vue')['default']
    GRichText: typeof import('./../components/grichtext/GRichText.vue')['default']
    GTabs: typeof import('./../components/gtabs/GTabs.vue')['default']
    GTextShow: typeof import('./../components/gtext-show/GTextShow.vue')['default']
    GToolbar: typeof import('./../components/toolbar/GToolbar.vue')['default']
    GTree: typeof import('./../components/gtree/GTree.vue')['default']
    KeyValueEditor: typeof import('./../components/grestful-api/KeyValueEditor.vue')['default']
    LanguageSwitcher: typeof import('./../components/common/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteViewLoadingMask: typeof import('./../components/RouteViewLoadingMask.vue')['default']
    RsDataForm: typeof import('./../components/form/rs-data/RsDataForm.vue')['default']
    RsDataFormFields: typeof import('./../components/form/rs-data/RsDataFormFields.vue')['default']
    RsDataFormModal: typeof import('./../components/form/rs-data/RsDataFormModal.vue')['default']
    RsGrid: typeof import('./../components/rs-grid/RsGrid.vue')['default']
    RsSearchForm: typeof import('./../components/form/rs-search/RsSearchForm.vue')['default']
    RsTableAnalyticsPanel: typeof import('./../components/rs-table-analytics/RsTableAnalyticsPanel.vue')['default']
    SearchForm: typeof import('./../components/form/search/SearchForm.vue')['default']
    ThemeSwitcher: typeof import('./../components/common/ThemeSwitcher.vue')['default']
    ToolbarBtnFace: typeof import('./../components/toolbar/ToolbarBtnFace.vue')['default']
    ToolbarButton: typeof import('./../components/toolbar/ToolbarButton.vue')['default']
  }
}
