-- Service center E2E schema for SQLite. Tables only. Seed is done in Go.

CREATE TABLE IF NOT EXISTS HUB_SERVICE_INSTANCE (
    tenantId TEXT NOT NULL,
    instanceName TEXT NOT NULL,
    environment TEXT NOT NULL,
    serverType TEXT NOT NULL DEFAULT 'GRPC',
    listenAddress TEXT NOT NULL DEFAULT '0.0.0.0',
    listenPort INTEGER NOT NULL DEFAULT 12004,
    maxRecvMsgSize INTEGER NOT NULL DEFAULT 16777216,
    maxSendMsgSize INTEGER NOT NULL DEFAULT 16777216,
    keepAliveTime INTEGER NOT NULL DEFAULT 30,
    keepAliveTimeout INTEGER NOT NULL DEFAULT 10,
    keepAliveMinTime INTEGER NOT NULL DEFAULT 15,
    permitWithoutStream TEXT NOT NULL DEFAULT 'Y',
    maxConnectionIdle INTEGER NOT NULL DEFAULT 0,
    maxConnectionAge INTEGER NOT NULL DEFAULT 0,
    maxConnectionAgeGrace INTEGER NOT NULL DEFAULT 20,
    enableReflection TEXT NOT NULL DEFAULT 'Y',
    enableTLS TEXT NOT NULL DEFAULT 'N',
    certStorageType TEXT NOT NULL DEFAULT 'FILE',
    certFilePath TEXT,
    keyFilePath TEXT,
    certContent TEXT,
    keyContent TEXT,
    certChainContent TEXT,
    certPassword TEXT,
    enableMTLS TEXT NOT NULL DEFAULT 'N',
    maxConcurrentStreams INTEGER NOT NULL DEFAULT 250,
    readBufferSize INTEGER NOT NULL DEFAULT 32768,
    writeBufferSize INTEGER NOT NULL DEFAULT 32768,
    healthCheckInterval INTEGER NOT NULL DEFAULT 30,
    healthCheckTimeout INTEGER NOT NULL DEFAULT 5,
    instanceStatus TEXT NOT NULL DEFAULT 'STOPPED',
    statusMessage TEXT,
    lastStatusTime TEXT,
    lastHealthCheckTime TEXT,
    addTime TEXT NOT NULL DEFAULT (datetime('now')),
    addWho TEXT NOT NULL,
    editTime TEXT NOT NULL DEFAULT (datetime('now')),
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    enableAuth TEXT NOT NULL DEFAULT 'N',
    ipWhitelist TEXT,
    ipBlacklist TEXT,
    PRIMARY KEY (tenantId, instanceName, environment)
);

CREATE TABLE IF NOT EXISTS HUB_SERVICE_NAMESPACE (
    namespaceId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    instanceName TEXT NOT NULL,
    environment TEXT NOT NULL,
    namespaceName TEXT NOT NULL,
    namespaceDescription TEXT,
    serviceQuotaLimit INTEGER DEFAULT 200,
    configQuotaLimit INTEGER DEFAULT 200,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    PRIMARY KEY (tenantId, namespaceId)
);

CREATE TABLE IF NOT EXISTS HUB_SERVICE (
    tenantId TEXT NOT NULL,
    namespaceId TEXT NOT NULL,
    groupName TEXT NOT NULL DEFAULT 'DEFAULT_GROUP',
    serviceName TEXT NOT NULL,
    serviceType TEXT NOT NULL DEFAULT 'INTERNAL',
    serviceVersion TEXT,
    serviceDescription TEXT,
    externalServiceConfig TEXT,
    metadataJson TEXT,
    tagsJson TEXT,
    protectThreshold REAL DEFAULT 0.00,
    selectorJson TEXT,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    reserved1 TEXT,
    reserved2 TEXT,
    reserved3 TEXT,
    reserved4 TEXT,
    reserved5 TEXT,
    PRIMARY KEY (tenantId, namespaceId, groupName, serviceName)
);

CREATE TABLE IF NOT EXISTS HUB_SERVICE_NODE (
    nodeId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    namespaceId TEXT NOT NULL,
    groupName TEXT NOT NULL,
    serviceName TEXT NOT NULL,
    ipAddress TEXT NOT NULL,
    portNumber INTEGER NOT NULL,
    instanceStatus TEXT NOT NULL DEFAULT 'UP',
    healthyStatus TEXT NOT NULL DEFAULT 'UNKNOWN',
    ephemeral TEXT NOT NULL DEFAULT 'Y',
    weight REAL NOT NULL DEFAULT 1.00,
    metadataJson TEXT,
    registerTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastBeatTime DATETIME,
    lastCheckTime DATETIME,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    PRIMARY KEY (tenantId, nodeId)
);

CREATE TABLE IF NOT EXISTS HUB_SERVICE_CONFIG_DATA (
    configDataId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    namespaceId TEXT NOT NULL,
    groupName TEXT NOT NULL DEFAULT 'DEFAULT_GROUP',
    configContent TEXT NOT NULL,
    contentType TEXT DEFAULT 'text',
    configDescription TEXT,
    encrypted TEXT DEFAULT 'N',
    version INTEGER NOT NULL DEFAULT 1,
    md5Value TEXT,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    PRIMARY KEY (tenantId, namespaceId, groupName, configDataId)
);

CREATE TABLE IF NOT EXISTS HUB_SERVICE_CONFIG_HISTORY (
    configHistoryId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    configDataId TEXT NOT NULL,
    namespaceId TEXT NOT NULL,
    groupName TEXT NOT NULL,
    changeType TEXT NOT NULL,
    oldContent TEXT,
    newContent TEXT NOT NULL,
    oldVersion INTEGER,
    newVersion INTEGER NOT NULL,
    oldMd5Value TEXT,
    newMd5Value TEXT NOT NULL,
    changeReason TEXT,
    changedBy TEXT NOT NULL,
    changedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    PRIMARY KEY (tenantId, configHistoryId)
);

-- 认证：Basic 依赖 HUB_USER；Bearer API Token 依赖本表；JWT 密钥在实例 extProperty
CREATE TABLE IF NOT EXISTS HUB_USER (
    userId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    userName TEXT NOT NULL,
    password TEXT NOT NULL,
    realName TEXT NOT NULL,
    deptId TEXT NOT NULL DEFAULT 'D00000001',
    email TEXT,
    mobile TEXT,
    statusFlag TEXT NOT NULL DEFAULT 'Y',
    userExpireDate DATETIME NOT NULL DEFAULT '2099-12-31 23:59:59',
    pwdErrorCount INTEGER NOT NULL DEFAULT 0,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    PRIMARY KEY (userId, tenantId)
);

CREATE TABLE IF NOT EXISTS HUB_SERVICE_AUTH_TOKEN (
    tokenId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    tokenValue TEXT NOT NULL,
    userId TEXT NOT NULL,
    tokenName TEXT,
    expireTime DATETIME,
    statusFlag TEXT NOT NULL DEFAULT 'Y',
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    PRIMARY KEY (tenantId, tokenId)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_SC_AUTH_TOKEN_VALUE ON HUB_SERVICE_AUTH_TOKEN(tokenValue);
