
-- 31. 磁盘IO日志表
CREATE TABLE IF NOT EXISTS HUB_METRIC_DISK_IO_LOG (
    metricDiskIoLogId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    metricServerId TEXT NOT NULL,
    deviceName TEXT NOT NULL,
    readCount INTEGER NOT NULL DEFAULT 0,
    writeCount INTEGER NOT NULL DEFAULT 0,
    readBytes INTEGER NOT NULL DEFAULT 0,
    writeBytes INTEGER NOT NULL DEFAULT 0,
    readTime INTEGER NOT NULL DEFAULT 0,
    writeTime INTEGER NOT NULL DEFAULT 0,
    ioInProgress INTEGER NOT NULL DEFAULT 0,
    ioTime INTEGER NOT NULL DEFAULT 0,
    readRate REAL NOT NULL DEFAULT 0.00,
    writeRate REAL NOT NULL DEFAULT 0.00,
    collectTime DATETIME NOT NULL,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    reserved1 TEXT,
    reserved2 TEXT,
    reserved3 TEXT,
    reserved4 TEXT,
    reserved5 TEXT,
    reserved6 TEXT,
    reserved7 TEXT,
    reserved8 TEXT,
    reserved9 TEXT,
    reserved10 TEXT,
    PRIMARY KEY (tenantId, metricDiskIoLogId)
);
CREATE INDEX IDX_METRIC_DISK_IO_SERVER ON HUB_METRIC_DISK_IO_LOG(metricServerId);
CREATE INDEX IDX_METRIC_DISK_IO_TIME ON HUB_METRIC_DISK_IO_LOG(collectTime);
CREATE INDEX IDX_METRIC_DISK_IO_DEVICE ON HUB_METRIC_DISK_IO_LOG(deviceName);
CREATE INDEX IDX_METRIC_DISK_IO_ACTIVE ON HUB_METRIC_DISK_IO_LOG(activeFlag);
CREATE INDEX IDX_METRIC_DISK_IO_SRV_TIME ON HUB_METRIC_DISK_IO_LOG(metricServerId, collectTime);
CREATE INDEX IDX_METRIC_DISK_IO_SRV_DEV ON HUB_METRIC_DISK_IO_LOG(metricServerId, deviceName);
CREATE INDEX IDX_METRIC_DISK_IO_TNT_TIME ON HUB_METRIC_DISK_IO_LOG(tenantId, collectTime);