
-- 服务实例表 - 存储具体的服务实例
CREATE TABLE IF NOT EXISTS HUB_REGISTRY_SERVICE_INSTANCE (
  -- 主键和租户信息
  serviceInstanceId TEXT NOT NULL,
  tenantId TEXT NOT NULL,
  
  -- 关联服务和分组（主键关联）
  serviceGroupId TEXT NOT NULL,
  -- 冗余字段（便于查询和展示）
  serviceName TEXT NOT NULL,
  groupName TEXT NOT NULL,
  
  -- 网络连接信息
  hostAddress TEXT NOT NULL,
  portNumber INTEGER NOT NULL,
  contextPath TEXT DEFAULT '',
  
  -- 实例状态信息
  instanceStatus TEXT NOT NULL DEFAULT 'UP',
  healthStatus TEXT NOT NULL DEFAULT 'UNKNOWN',
  
  -- 负载均衡配置
  weightValue INTEGER NOT NULL DEFAULT 100,
  
  -- 客户端信息
  clientId TEXT,
  clientVersion TEXT,
  clientType TEXT DEFAULT 'SERVICE',
  tempInstanceFlag TEXT NOT NULL DEFAULT 'N',
  
  -- 健康检查统计
  heartbeatFailCount INTEGER NOT NULL DEFAULT 0,
  
  -- 元数据和标签
  metadataJson TEXT,
  tagsJson TEXT,
  
  -- 时间戳信息
  registerTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastHeartbeatTime DATETIME,
  lastHealthCheckTime DATETIME,
  
  -- 通用字段
  addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  addWho TEXT NOT NULL,
  editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  editWho TEXT NOT NULL,
  oprSeqFlag TEXT NOT NULL,
  currentVersion INTEGER NOT NULL DEFAULT 1,
  activeFlag TEXT NOT NULL DEFAULT 'Y',
  noteText TEXT,
  extProperty TEXT,
  reserved1 TEXT,
  reserved2 TEXT,
  reserved3 TEXT,
  reserved4 TEXT,
  reserved5 TEXT,
  reserved6 TEXT,
  reserved7 TEXT,
  reserved8 TEXT,
  reserved9 TEXT,
  reserved10 TEXT,
  
  PRIMARY KEY (tenantId, serviceInstanceId)
);

CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INSTANCE ON HUB_REGISTRY_SERVICE_INSTANCE(tenantId, serviceGroupId, serviceName, hostAddress, portNumber);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_GROUP_ID ON HUB_REGISTRY_SERVICE_INSTANCE(tenantId, serviceGroupId);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_SVC_NAME ON HUB_REGISTRY_SERVICE_INSTANCE(serviceName);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_GROUP_NAME ON HUB_REGISTRY_SERVICE_INSTANCE(groupName);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_STATUS ON HUB_REGISTRY_SERVICE_INSTANCE(instanceStatus);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_HEALTH ON HUB_REGISTRY_SERVICE_INSTANCE(healthStatus);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_HEARTBEAT ON HUB_REGISTRY_SERVICE_INSTANCE(lastHeartbeatTime);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_HOST_PORT ON HUB_REGISTRY_SERVICE_INSTANCE(hostAddress, portNumber);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_CLIENT ON HUB_REGISTRY_SERVICE_INSTANCE(clientId);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_ACTIVE ON HUB_REGISTRY_SERVICE_INSTANCE(activeFlag);
CREATE INDEX IF NOT EXISTS IDX_REGISTRY_INST_TEMP ON HUB_REGISTRY_SERVICE_INSTANCE(tempInstanceFlag);