-- =========================================

CREATE TABLE HUB_TUNNEL_SERVER_NODE (
  serverNodeId TEXT NOT NULL PRIMARY KEY,
  tenantId TEXT NOT NULL,
  tunnelServerId TEXT NOT NULL,
  nodeName TEXT NOT NULL UNIQUE,
  nodeType TEXT NOT NULL DEFAULT 'static',
  proxyType TEXT NOT NULL,
  listenAddress TEXT NOT NULL DEFAULT '0.0.0.0',
  listenPort INTEGER NOT NULL,
  targetAddress TEXT NOT NULL,
  targetPort INTEGER NOT NULL,
  customDomains TEXT,
  subDomain TEXT,
  httpUser TEXT,
  httpPassword TEXT,
  hostHeaderRewrite TEXT,
  headers TEXT,
  locations TEXT,
  compression TEXT NOT NULL DEFAULT 'Y' CHECK(compression IN ('Y', 'N')),
  encryption TEXT NOT NULL DEFAULT 'N' CHECK(encryption IN ('Y', 'N')),
  secretKey TEXT,
  healthCheckType TEXT DEFAULT 'tcp',
  healthCheckUrl TEXT,
  healthCheckInterval INTEGER DEFAULT 60,
  maxConnections INTEGER DEFAULT 100,
  nodeStatus TEXT NOT NULL DEFAULT 'active',
  lastHealthCheck TEXT,
  connectionCount INTEGER DEFAULT 0,
  totalConnections INTEGER DEFAULT 0,
  totalBytes INTEGER DEFAULT 0,
  createdTime TEXT NOT NULL DEFAULT (datetime('now')),
  addTime TEXT NOT NULL DEFAULT (datetime('now')),
  addWho TEXT NOT NULL,
  editTime TEXT NOT NULL DEFAULT (datetime('now')),
  editWho TEXT NOT NULL,
  oprSeqFlag TEXT NOT NULL,
  currentVersion INTEGER NOT NULL DEFAULT 1,
  activeFlag TEXT NOT NULL DEFAULT 'Y' CHECK(activeFlag IN ('Y', 'N')),
  noteText TEXT,
  extProperty TEXT,
  reserved1 TEXT,
  reserved2 TEXT,
  reserved3 TEXT,
  reserved4 TEXT,
  reserved5 TEXT,
  reserved6 TEXT,
  reserved7 TEXT,
  reserved8 TEXT,
  reserved9 TEXT,
  reserved10 TEXT,
  UNIQUE(listenAddress, listenPort, proxyType)
);
CREATE INDEX IDX_TUNNEL_NODE_TENANT ON HUB_TUNNEL_SERVER_NODE(tenantId);
CREATE INDEX IDX_TUNNEL_NODE_SERVER ON HUB_TUNNEL_SERVER_NODE(tunnelServerId);
CREATE INDEX IDX_TUNNEL_NODE_TYPE ON HUB_TUNNEL_SERVER_NODE(nodeType, proxyType);
CREATE INDEX IDX_TUNNEL_NODE_STATUS ON HUB_TUNNEL_SERVER_NODE(nodeStatus);
CREATE INDEX IDX_TUNNEL_NODE_HEALTH ON HUB_TUNNEL_SERVER_NODE(lastHealthCheck);