-- 服务中心 API Token（Bearer 不透明令牌）
CREATE TABLE IF NOT EXISTS HUB_SERVICE_AUTH_TOKEN (
    tokenId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    tokenValue TEXT NOT NULL,
    userId TEXT NOT NULL,
    tokenName TEXT,
    expireTime DATETIME,
    statusFlag TEXT NOT NULL DEFAULT 'Y',
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    PRIMARY KEY (tenantId, tokenId)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_SC_AUTH_TOKEN_VALUE ON HUB_SERVICE_AUTH_TOKEN(tokenValue);
CREATE INDEX IF NOT EXISTS IDX_SC_AUTH_TOKEN_USER ON HUB_SERVICE_AUTH_TOKEN(userId);
