
-- 2. 用户登录日志表
CREATE TABLE IF NOT EXISTS HUB_LOGIN_LOG (
    logId TEXT NOT NULL,
    userId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    userName TEXT NOT NULL,
    loginTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    loginIp TEXT NOT NULL,
    loginLocation TEXT,
    loginType INTEGER NOT NULL DEFAULT 1,
    deviceType TEXT,
    deviceInfo TEXT,
    browserInfo TEXT,
    osInfo TEXT,
    loginStatus TEXT NOT NULL DEFAULT 'N',
    logoutTime DATETIME,
    sessionDuration INTEGER,
    failReason TEXT,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    PRIMARY KEY (logId)
);
CREATE INDEX IDX_LOGIN_USER ON HUB_LOGIN_LOG(userId);
CREATE INDEX IDX_LOGIN_TIME ON HUB_LOGIN_LOG(loginTime);
CREATE INDEX IDX_LOGIN_TENANT ON HUB_LOGIN_LOG(tenantId);
CREATE INDEX IDX_LOGIN_STATUS ON HUB_LOGIN_LOG(loginStatus);
CREATE INDEX IDX_LOGIN_TYPE ON HUB_LOGIN_LOG(loginType);