-- 配置历史表 - 记录配置的变更历史，支持配置回滚和审计
CREATE TABLE IF NOT EXISTS HUB_SERVICE_CONFIG_HISTORY (
  -- 主键和租户信息
  configHistoryId TEXT NOT NULL,
  tenantId TEXT NOT NULL,
  
  -- 关联配置数据
  configDataId TEXT NOT NULL,
  namespaceId TEXT NOT NULL,
  groupName TEXT NOT NULL,
  
  -- 变更信息
  changeType TEXT NOT NULL,
  oldContent TEXT,
  newContent TEXT NOT NULL,
  oldVersion INTEGER,
  newVersion INTEGER NOT NULL,
  oldMd5Value TEXT,
  newMd5Value TEXT NOT NULL,
  
  -- 变更原因和操作人
  changeReason TEXT,
  changedBy TEXT NOT NULL,
  changedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  -- 通用字段
  addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  addWho TEXT NOT NULL,
  editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  editWho TEXT NOT NULL,
  oprSeqFlag TEXT NOT NULL,
  currentVersion INTEGER NOT NULL DEFAULT 1,
  activeFlag TEXT NOT NULL DEFAULT 'Y',
  noteText TEXT,
  extProperty TEXT,
  
  PRIMARY KEY (tenantId, configHistoryId)
);

CREATE INDEX IDX_SVC_CFG_HIST_DATA_ID ON HUB_SERVICE_CONFIG_HISTORY(tenantId, configDataId);
CREATE INDEX IDX_SVC_CFG_HIST_NS_ID ON HUB_SERVICE_CONFIG_HISTORY(tenantId, namespaceId);
CREATE INDEX IDX_SVC_CFG_HIST_GROUP_NAME ON HUB_SERVICE_CONFIG_HISTORY(tenantId, namespaceId, groupName);
CREATE INDEX IDX_SVC_CFG_HIST_TYPE ON HUB_SERVICE_CONFIG_HISTORY(changeType);
CREATE INDEX IDX_SVC_CFG_HIST_TIME ON HUB_SERVICE_CONFIG_HISTORY(changedAt);
CREATE INDEX IDX_SVC_CFG_HIST_BY ON HUB_SERVICE_CONFIG_HISTORY(changedBy);
CREATE INDEX IDX_SVC_CFG_HIST_VERSION ON HUB_SERVICE_CONFIG_HISTORY(newVersion);

