
-- 隧道服务器配置表 - 管理控制端口和核心配置
CREATE TABLE HUB_TUNNEL_SERVER (
  tunnelServerId TEXT NOT NULL PRIMARY KEY,
  tenantId TEXT NOT NULL,
  serverName TEXT NOT NULL UNIQUE,
  serverDescription TEXT,
  controlAddress TEXT NOT NULL DEFAULT '0.0.0.0',
  controlPort INTEGER NOT NULL DEFAULT 7000,
  dashboardPort INTEGER DEFAULT 7500,
  vhostHttpPort INTEGER DEFAULT 80,
  vhostHttpsPort INTEGER DEFAULT 443,
  maxClients INTEGER NOT NULL DEFAULT 1000,
  tokenAuth TEXT NOT NULL DEFAULT 'Y' CHECK(tokenAuth IN ('Y', 'N')),
  authToken TEXT,
  tlsEnable TEXT NOT NULL DEFAULT 'N' CHECK(tlsEnable IN ('Y', 'N')),
  tlsCertFile TEXT,
  tlsKeyFile TEXT,
  heartbeatInterval INTEGER NOT NULL DEFAULT 30,
  heartbeatTimeout INTEGER NOT NULL DEFAULT 90,
  logLevel TEXT NOT NULL DEFAULT 'info',
  maxPortsPerClient INTEGER DEFAULT 10,
  allowPorts TEXT,
  serverStatus TEXT NOT NULL DEFAULT 'stopped',
  startTime TEXT,
  configVersion TEXT,
  addTime TEXT NOT NULL DEFAULT (datetime('now')),
  addWho TEXT NOT NULL,
  editTime TEXT NOT NULL DEFAULT (datetime('now')),
  editWho TEXT NOT NULL,
  oprSeqFlag TEXT NOT NULL,
  currentVersion INTEGER NOT NULL DEFAULT 1,
  activeFlag TEXT NOT NULL DEFAULT 'Y' CHECK(activeFlag IN ('Y', 'N')),
  noteText TEXT,
  extProperty TEXT,
  reserved1 TEXT,
  reserved2 TEXT,
  reserved3 TEXT,
  reserved4 TEXT,
  reserved5 TEXT,
  reserved6 TEXT,
  reserved7 TEXT,
  reserved8 TEXT,
  reserved9 TEXT,
  reserved10 TEXT
);
CREATE INDEX IDX_TUNNEL_SVR_TENANT ON HUB_TUNNEL_SERVER(tenantId);
CREATE INDEX IDX_TUNNEL_SVR_CTRL ON HUB_TUNNEL_SERVER(controlAddress, controlPort);
CREATE INDEX IDX_TUNNEL_SVR_STATUS ON HUB_TUNNEL_SERVER(serverStatus);