
-- 30. 磁盘分区日志表
CREATE TABLE IF NOT EXISTS HUB_METRIC_DISK_PART_LOG (
    metricDiskPartitionLogId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    metricServerId TEXT NOT NULL,
    deviceName TEXT NOT NULL,
    mountPoint TEXT NOT NULL,
    fileSystem TEXT NOT NULL,
    totalSpace INTEGER NOT NULL DEFAULT 0,
    usedSpace INTEGER NOT NULL DEFAULT 0,
    freeSpace INTEGER NOT NULL DEFAULT 0,
    usagePercent REAL NOT NULL DEFAULT 0.00,
    inodesTotal INTEGER NOT NULL DEFAULT 0,
    inodesUsed INTEGER NOT NULL DEFAULT 0,
    inodesFree INTEGER NOT NULL DEFAULT 0,
    inodesUsagePercent REAL NOT NULL DEFAULT 0.00,
    collectTime DATETIME NOT NULL,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    reserved1 TEXT,
    reserved2 TEXT,
    reserved3 TEXT,
    reserved4 TEXT,
    reserved5 TEXT,
    reserved6 TEXT,
    reserved7 TEXT,
    reserved8 TEXT,
    reserved9 TEXT,
    reserved10 TEXT,
    PRIMARY KEY (tenantId, metricDiskPartitionLogId)
);
CREATE INDEX IDX_METRIC_DISK_PART_SERVER ON HUB_METRIC_DISK_PART_LOG(metricServerId);
CREATE INDEX IDX_METRIC_DISK_PART_TIME ON HUB_METRIC_DISK_PART_LOG(collectTime);
CREATE INDEX IDX_METRIC_DISK_PART_DEVICE ON HUB_METRIC_DISK_PART_LOG(deviceName);
CREATE INDEX IDX_METRIC_DISK_PART_USAGE ON HUB_METRIC_DISK_PART_LOG(usagePercent);
CREATE INDEX IDX_METRIC_DISK_PART_ACTIVE ON HUB_METRIC_DISK_PART_LOG(activeFlag);
CREATE INDEX IDX_METRIC_DISK_PART_SRV_TIME ON HUB_METRIC_DISK_PART_LOG(metricServerId, collectTime);
CREATE INDEX IDX_METRIC_DISK_PART_SRV_DEV ON HUB_METRIC_DISK_PART_LOG(metricServerId, deviceName);
CREATE INDEX IDX_METRIC_DISK_PART_TNT_TIME ON HUB_METRIC_DISK_PART_LOG(tenantId, collectTime);