
-- 20. 日志配置表
CREATE TABLE IF NOT EXISTS HUB_GW_LOG_CONFIG (
    tenantId TEXT NOT NULL,
    logConfigId TEXT NOT NULL,
    configName TEXT NOT NULL,
    configDesc TEXT,
    logFormat TEXT NOT NULL DEFAULT 'JSON',
    recordRequestBody TEXT NOT NULL DEFAULT 'N',
    recordResponseBody TEXT NOT NULL DEFAULT 'N',
    recordHeaders TEXT NOT NULL DEFAULT 'Y',
    maxBodySizeBytes INTEGER NOT NULL DEFAULT 4096,
    outputTargets TEXT NOT NULL DEFAULT 'CONSOLE',
    fileConfig TEXT,
    databaseConfig TEXT,
    mongoConfig TEXT,
    elasticsearchConfig TEXT,
    clickhouseConfig TEXT,
    enableAsyncLogging TEXT NOT NULL DEFAULT 'Y',
    asyncQueueSize INTEGER NOT NULL DEFAULT 10000,
    asyncFlushIntervalMs INTEGER NOT NULL DEFAULT 1000,
    enableBatchProcessing TEXT NOT NULL DEFAULT 'Y',
    batchSize INTEGER NOT NULL DEFAULT 100,
    batchTimeoutMs INTEGER NOT NULL DEFAULT 5000,
    logRetentionDays INTEGER NOT NULL DEFAULT 30,
    enableFileRotation TEXT NOT NULL DEFAULT 'Y',
    maxFileSizeMB INTEGER DEFAULT 100,
    maxFileCount INTEGER DEFAULT 10,
    rotationPattern TEXT DEFAULT 'DAILY',
    enableSensitiveDataMasking TEXT NOT NULL DEFAULT 'Y',
    sensitiveFields TEXT,
    maskingPattern TEXT DEFAULT '***',
    bufferSize INTEGER NOT NULL DEFAULT 8192,
    flushThreshold INTEGER NOT NULL DEFAULT 100,
    configPriority INTEGER NOT NULL DEFAULT 0,
    reserved1 TEXT,
    reserved2 TEXT,
    reserved3 INTEGER,
    reserved4 INTEGER,
    reserved5 DATETIME,
    extProperty TEXT,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    PRIMARY KEY (tenantId, logConfigId)
);
CREATE INDEX IF NOT EXISTS idx_HUB_GW_LOG_CONFIG_name ON HUB_GW_LOG_CONFIG(configName);
CREATE INDEX IF NOT EXISTS idx_HUB_GW_LOG_CONFIG_priority ON HUB_GW_LOG_CONFIG(configPriority);