
-- 34. 进程统计日志表
CREATE TABLE IF NOT EXISTS HUB_METRIC_PROCSTAT_LOG (
    metricProcessStatsLogId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    metricServerId TEXT NOT NULL,
    runningCount INTEGER NOT NULL DEFAULT 0,
    sleepingCount INTEGER NOT NULL DEFAULT 0,
    stoppedCount INTEGER NOT NULL DEFAULT 0,
    zombieCount INTEGER NOT NULL DEFAULT 0,
    totalCount INTEGER NOT NULL DEFAULT 0,
    collectTime DATETIME NOT NULL,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    reserved1 TEXT,
    reserved2 TEXT,
    reserved3 TEXT,
    reserved4 TEXT,
    reserved5 TEXT,
    reserved6 TEXT,
    reserved7 TEXT,
    reserved8 TEXT,
    reserved9 TEXT,
    reserved10 TEXT,
    PRIMARY KEY (tenantId, metricProcessStatsLogId)
);
CREATE INDEX IDX_METRIC_PROC_STATS_SERVER ON HUB_METRIC_PROCSTAT_LOG(metricServerId);
CREATE INDEX IDX_METRIC_PROC_STATS_TIME ON HUB_METRIC_PROCSTAT_LOG(collectTime);
CREATE INDEX IDX_METRIC_PROC_STATS_ACTIVE ON HUB_METRIC_PROCSTAT_LOG(activeFlag);
CREATE INDEX IDX_METRIC_PROC_STATS_SRV_TIME ON HUB_METRIC_PROCSTAT_LOG(metricServerId, collectTime);
CREATE INDEX IDX_METRIC_PROC_STATS_TNT_TIME ON HUB_METRIC_PROCSTAT_LOG(tenantId, collectTime);