-- 静态隧道服务器表 - 管理静态端口转发服务配置
CREATE TABLE HUB_TUNNEL_STATIC_SERVER (
  tunnelStaticServerId TEXT NOT NULL PRIMARY KEY,
  tenantId TEXT NOT NULL,
  serverName TEXT NOT NULL UNIQUE,
  serverDescription TEXT,
  listenAddress TEXT NOT NULL DEFAULT '0.0.0.0',
  listenPort INTEGER NOT NULL,
  serverType TEXT NOT NULL DEFAULT 'tcp',
  maxConnections INTEGER NOT NULL DEFAULT 1000,
  connectionTimeout INTEGER NOT NULL DEFAULT 60,
  readTimeout INTEGER NOT NULL DEFAULT 30,
  writeTimeout INTEGER NOT NULL DEFAULT 30,
  tlsEnable TEXT NOT NULL DEFAULT 'N' CHECK(tlsEnable IN ('Y', 'N')),
  tlsCertFile TEXT,
  tlsKeyFile TEXT,
  tlsCaFile TEXT,
  logLevel TEXT NOT NULL DEFAULT 'info',
  logFile TEXT,
  serverStatus TEXT NOT NULL DEFAULT 'stopped',
  startTime TEXT,
  stopTime TEXT,
  currentConnectionCount INTEGER DEFAULT 0,
  totalConnectionCount INTEGER DEFAULT 0,
  totalBytesReceived INTEGER DEFAULT 0,
  totalBytesSent INTEGER DEFAULT 0,
  healthCheckType TEXT DEFAULT 'tcp',
  healthCheckUrl TEXT,
  healthCheckInterval INTEGER DEFAULT 30,
  healthCheckTimeout INTEGER DEFAULT 5,
  healthCheckMaxFailures INTEGER DEFAULT 3,
  loadBalanceType TEXT DEFAULT 'roundrobin',
  serverConfig TEXT,
  addTime TEXT NOT NULL DEFAULT (datetime('now')),
  addWho TEXT NOT NULL,
  editTime TEXT NOT NULL DEFAULT (datetime('now')),
  editWho TEXT NOT NULL,
  oprSeqFlag TEXT NOT NULL,
  currentVersion INTEGER NOT NULL DEFAULT 1,
  activeFlag TEXT NOT NULL DEFAULT 'Y' CHECK(activeFlag IN ('Y', 'N')),
  noteText TEXT,
  extProperty TEXT,
  reserved1 TEXT,
  reserved2 TEXT,
  reserved3 TEXT,
  reserved4 TEXT,
  reserved5 TEXT,
  reserved6 TEXT,
  reserved7 TEXT,
  reserved8 TEXT,
  reserved9 TEXT,
  reserved10 TEXT,
  UNIQUE(listenAddress, listenPort, serverType)
);
CREATE INDEX IDX_TUNNEL_STATIC_SVR_TENANT ON HUB_TUNNEL_STATIC_SERVER(tenantId);
CREATE INDEX IDX_TUNNEL_STATIC_SVR_STATUS ON HUB_TUNNEL_STATIC_SERVER(serverStatus);
CREATE INDEX IDX_TUNNEL_STATIC_SVR_TYPE ON HUB_TUNNEL_STATIC_SERVER(serverType);

