
-- 28. CPU采集日志表
CREATE TABLE IF NOT EXISTS HUB_METRIC_CPU_LOG (
    metricCpuLogId TEXT NOT NULL,
    tenantId TEXT NOT NULL,
    metricServerId TEXT NOT NULL,
    usagePercent REAL NOT NULL DEFAULT 0.00,
    userPercent REAL NOT NULL DEFAULT 0.00,
    systemPercent REAL NOT NULL DEFAULT 0.00,
    idlePercent REAL NOT NULL DEFAULT 0.00,
    ioWaitPercent REAL NOT NULL DEFAULT 0.00,
    irqPercent REAL NOT NULL DEFAULT 0.00,
    softIrqPercent REAL NOT NULL DEFAULT 0.00,
    coreCount INTEGER NOT NULL DEFAULT 0,
    logicalCount INTEGER NOT NULL DEFAULT 0,
    loadAvg1 REAL NOT NULL DEFAULT 0.00,
    loadAvg5 REAL NOT NULL DEFAULT 0.00,
    loadAvg15 REAL NOT NULL DEFAULT 0.00,
    collectTime DATETIME NOT NULL,
    addTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    addWho TEXT NOT NULL,
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editWho TEXT NOT NULL,
    oprSeqFlag TEXT NOT NULL,
    currentVersion INTEGER NOT NULL DEFAULT 1,
    activeFlag TEXT NOT NULL DEFAULT 'Y',
    noteText TEXT,
    extProperty TEXT,
    reserved1 TEXT,
    reserved2 TEXT,
    reserved3 TEXT,
    reserved4 TEXT,
    reserved5 TEXT,
    reserved6 TEXT,
    reserved7 TEXT,
    reserved8 TEXT,
    reserved9 TEXT,
    reserved10 TEXT,
    PRIMARY KEY (tenantId, metricCpuLogId)
);
CREATE INDEX IDX_METRIC_CPU_SERVER ON HUB_METRIC_CPU_LOG(metricServerId);
CREATE INDEX IDX_METRIC_CPU_TIME ON HUB_METRIC_CPU_LOG(collectTime);
CREATE INDEX IDX_METRIC_CPU_USAGE ON HUB_METRIC_CPU_LOG(usagePercent);
CREATE INDEX IDX_METRIC_CPU_ACTIVE ON HUB_METRIC_CPU_LOG(activeFlag);
CREATE INDEX IDX_METRIC_CPU_SRV_TIME ON HUB_METRIC_CPU_LOG(metricServerId, collectTime);
CREATE INDEX IDX_METRIC_CPU_TNT_TIME ON HUB_METRIC_CPU_LOG(tenantId, collectTime);