# ===========================================
# 数据库与缓存系统配置文件
# ===========================================

# 数据库配置
database:
  # 默认连接名称
  default: oracle_main
  
  # 各种数据库连接的配置
  connections:
    # MySQL 主连接
    mysql:
      driver: mysql
      enabled: true # 启用状态（可选，默认为true）
      dsn: "" # 如果提供DSN，将忽略下面的结构化配置
      connection:
        host: 121.43.231.91
        port: 63306
        username: root
        password: "datahub"
        database: shangjian_test
        charset: utf8mb4
        parse_time: true
        loc: Local
      pool:
        max_open_conns: 100
        max_idle_conns: 25
        conn_max_lifetime: 3600 # 秒
        conn_max_idle_time: 1800 # 秒
      log:
        slow_threshold: 200 # 毫秒，超过此时间的查询被视为慢查询
        log_level: info # 日志级别: debug, info, warn, error
        enable: true # 是否启用日志
      transaction:
        default_isolation: 3 # 默认隔离级别: 1=读未提交, 2=读已提交, 3=可重复读, 4=可串行化
    # Oracle主数据库连接
    oracle_main:
      enabled: true
      driver: "oracle"
      
      # 方式1: 使用DSN连接字符串 (推荐)
      # Oracle DSN格式: oracle://username:password@host:port/service_name
      # 或者: username/password@host:port/service_name
      # 或者: username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host)(PORT=port))(CONNECT_DATA=(SERVICE_NAME=service_name)))
      # 支持的参数: TIMEZONE=Asia/Shanghai&NLS_LANG=AMERICAN_AMERICA.UTF8&CONNECTION_TIMEOUT=30
      # dsn: "oracle://scott:tiger@localhost:1521/XEPDB1"
      
      # 方式2: 使用结构化连接配置 (如果未设置dsn，将使用此配置自动生成)
      connection:
        host: "47.117.1.78"
        port: 62345
        username: "DATAHUB_250624"
        password: "20250624_TMPpAssw0d123"
        database: "fluxv6pdb"  # Oracle的SERVICE_NAME或SID
        
        # Oracle特有参数
        timezone: "Asia/Shanghai"  # 时区设置，默认为系统时区
        nls_lang: "AMERICAN_AMERICA.UTF8"  # NLS语言环境
        connection_timeout: 30     # 连接超时时间(秒)
        read_timeout: 30          # 读取超时时间(秒) 
        write_timeout: 30         # 写入超时时间(秒)
        prefetch_rows: 500        # 预取行数
        lob_prefetch_size: 4096   # LOB预取大小
        
      # 连接池配置
      pool:
        max_open_conns: 50      # 最大打开连接数
        max_idle_conns: 25      # 最大空闲连接数
        conn_max_lifetime: 3600 # 连接最大生命周期(秒)
        conn_max_idle_time: 1800 # 连接最大空闲时间(秒)
        
      # 日志配置
      log:
        enable: true           # 是否启用SQL日志
        slow_threshold: 200    # 慢查询阈值(毫秒)
        
      # 事务配置
      transaction:
        default_use: false     # 默认是否使用事务
    # MySQL 只读连接
    mysql_read:
      driver: mysql
      enabled: false
      connection:
        host: localhost 
        port: 3306
        username: readonly
        password: password
        database: gohub
        charset: utf8mb4
        parse_time: true
        loc: Local
      pool:
        max_open_conns: 50
        max_idle_conns: 10
      log:
        slow_threshold: 200
      transaction:
        default_isolation: 2 # 读已提交，适合只读连接

    # PostgreSQL 连接示例
    postgres:
      driver: postgres
      enabled: false # 禁用此连接
      connection:
        host: localhost
        port: 5432
        username: postgres
        password: postgres
        database: gohub
        sslmode: disable
      pool:
        max_open_conns: 50
        max_idle_conns: 10
      log:
        slow_threshold: 200

    # SQLite 连接示例
    sqlite:
      driver: sqlite
      enabled: false # 禁用此连接
      connection:
        database: database.sqlite
      log:
        slow_threshold: 100 

# ===========================================
# 缓存配置 - 支持Redis和内存缓存
# ===========================================
cache:
  # 默认使用的缓存连接名称
  default: memory_cache
  
  # 缓存连接配置 - 支持多种类型：redis, memory
  connections:
    # ===== Redis 缓存配置 =====
    
    # Redis 主连接 - 单机模式
    redis_primary:
      type: redis                 # 缓存类型：redis
      config:
        enabled: false             # 是否启用该连接
        mode: "single"            # 连接模式: single(单机), sentinel(哨兵), cluster(集群)
        
        # === 单机模式连接配置 ===
        host: 121.43.231.91       # Redis服务器地址
        port: 63791               # Redis服务器端口
        password: "3112a1e4c2ea11e4:Pwd20160308"  # Redis认证密码
        database: 0               # Redis数据库编号，范围0-15
        
        # === 连接池配置 ===
        pool_size: 100            # 连接池最大连接数
        min_idle_connections: 10  # 最小空闲连接数
        max_retries: 3            # 操作失败时的最大重试次数
        
        # === 超时配置 ===
        dial_timeout: "5s"        # 建立连接的超时时间
        read_timeout: "3s"        # 读取数据的超时时间
        write_timeout: "3s"       # 写入数据的超时时间
        pool_timeout: "4s"        # 从连接池获取连接的超时时间
        idle_timeout: "1800s"     # 空闲连接超时时间
        
        # === TLS配置 ===
        enable_tls: false         # 是否启用TLS
        insecure_skip_verify: false # 是否跳过TLS证书验证
        cert_file: ""             # TLS证书文件路径
        key_file: ""              # TLS私钥文件路径
        ca_file: ""               # TLS CA证书文件路径

    # Redis 哨兵模式连接示例
    redis_sentinel:
      type: redis
      config:
        enabled: false            # 默认禁用
        mode: "sentinel"          # 哨兵模式
        
        # === 哨兵配置 ===
        sentinel_addrs:           # 哨兵地址列表
          - "127.0.0.1:26379"
          - "127.0.0.1:26380" 
          - "127.0.0.1:26381"
        master_name: "mymaster"   # 主节点名称
        password: "datahub"       # Redis认证密码
        database: 0
        
        # === 连接池配置 ===
        pool_size: 100
        min_idle_connections: 10
        max_retries: 3
        
        # === 超时配置 ===
        dial_timeout: "5s"
        read_timeout: "3s"
        write_timeout: "3s"
        pool_timeout: "4s"
        idle_timeout: "1800s"

    # Redis 集群模式连接示例
    redis_cluster:
      type: redis
      config:
        enabled: false            # 默认禁用
        mode: "cluster"           # 集群模式
        
        # === 集群配置 ===
        cluster_addrs:            # 集群节点地址列表
          - "127.0.0.1:7000"
          - "127.0.0.1:7001"
          - "127.0.0.1:7002"
          - "127.0.0.1:7003"
          - "127.0.0.1:7004"
          - "127.0.0.1:7005"
        password: ""              # 集群密码
        
        # === 连接池配置 ===
        pool_size: 100
        min_idle_connections: 10
        max_retries: 3
        
        # === 超时配置 ===
        dial_timeout: "5s"
        read_timeout: "3s"
        write_timeout: "3s"
        pool_timeout: "4s"
        idle_timeout: "1800s"

    # ===== 内存缓存配置 =====
    
    # 内存缓存 - 主实例
    memory_cache:
      type: memory              # 缓存类型：memory
      config:
        enabled: true          # 是否启用该连接
        
        # === 容量配置 ===
        max_size: 10000         # 最大存储条目数
        
        # === 键配置 ===
        key_prefix: "gohub:"    # 键前缀，用于区分不同应用
        
        # === 淘汰策略 ===
        eviction_policy: "ttl"  # 淘汰策略: ttl(过期时间，已实现), lru(预留), random(预留), fifo(预留)
        
        # === 过期时间配置 ===
        default_expiration: "1h"    # 默认过期时间
        cleanup_interval: "10m"     # 清理过期数据的间隔
        enable_lazy_cleanup: true   # 是否启用惰性清理
        
        # === 监控配置 ===
        enable_metrics: true        # 是否启用指标收集
        metrics_namespace: "memory_cache"  # 指标命名空间

    # 内存缓存 - 临时缓存实例（用于短期数据）
    memory_temp:
      type: memory
      config:
        enabled: false          # 默认禁用
        max_size: 5000          # 较小的容量
        key_prefix: "temp:"
        eviction_policy: "ttl"  # 使用TTL策略
        default_expiration: "5m"    # 较短的过期时间
        cleanup_interval: "2m"      # 更频繁的清理
        enable_lazy_cleanup: true
        enable_metrics: false       # 临时缓存不需要指标

    # 内存缓存 - 会话缓存实例（用于用户会话）
    memory_session:
      type: memory
      config:
        enabled: false
        max_size: 20000         # 用户会话数据
        key_prefix: "session:"
        eviction_policy: "ttl"  # 使用TTL策略
        default_expiration: "30m"   # 会话超时时间
        cleanup_interval: "5m"
        enable_lazy_cleanup: true
        enable_metrics: true    # 需要监控会话指标
        metrics_namespace: "session_cache"

