# 数据库配置
database:
  # 默认连接名称
  default: mysql
  
  # 各种数据库连接的配置
  connections:
    # MySQL 主连接
    mysql:
      driver: mysql
      enabled: true # 启用状态（可选，默认为true）
      dsn: "" # 如果提供DSN，将忽略下面的结构化配置
      connection:
        host: 121.43.231.91
        port: 63306
        username: root
        password: "datahub"
        database: shangjian_test
        charset: utf8mb4
        parse_time: true
        loc: Local
      pool:
        max_open_conns: 100
        max_idle_conns: 25
        conn_max_lifetime: 3600 # 秒
        conn_max_idle_time: 1800 # 秒
      log:
        slow_threshold: 200 # 毫秒，超过此时间的查询被视为慢查询
        log_level: info # 日志级别: debug, info, warn, error
        enable: true # 是否启用日志
      transaction:
        default_isolation: 3 # 默认隔离级别: 1=读未提交, 2=读已提交, 3=可重复读, 4=可串行化

    # MySQL 只读连接
    mysql_read:
      driver: mysql
      enabled: false
      connection:
        host: localhost 
        port: 3306
        username: readonly
        password: password
        database: gohub
        charset: utf8mb4
        parse_time: true
        loc: Local
      pool:
        max_open_conns: 50
        max_idle_conns: 10
      log:
        slow_threshold: 200
      transaction:
        default_isolation: 2 # 读已提交，适合只读连接

    # PostgreSQL 连接示例
    postgres:
      driver: postgres
      enabled: false # 禁用此连接
      connection:
        host: localhost
        port: 5432
        username: postgres
        password: postgres
        database: gohub
        sslmode: disable
      pool:
        max_open_conns: 50
        max_idle_conns: 10
      log:
        slow_threshold: 200

    # SQLite 连接示例
    sqlite:
      driver: sqlite
      enabled: false # 禁用此连接
      connection:
        database: database.sqlite
      log:
        slow_threshold: 100 

# 缓存配置
cache:
  # 默认使用的Redis连接名称
  default: redis_default
  # Redis连接配置 - 支持多连接配置
  connections:
    # 默认Redis连接
    redis_default:
      enabled: true              # 是否启用该连接
      mode: "single"             # 连接模式: single(单机), sentinel(哨兵), cluster(集群)
      key_expire: 36000     # 缓存过期时间，默认10小时(S)
      # === 单机模式连接配置 ===
      host: 121.43.231.91        # Redis服务器地址
      port: 63791                 # Redis服务器端口
      password: "3112a1e4c2ea11e4:Pwd20160308"        # Redis认证密码
      db: 0                      # Redis数据库编号，范围0-15
      
      # === 连接池配置 ===
      pool_size: 100             # 连接池最大连接数
      min_idle_conns: 10         # 最小空闲连接数
      max_idle_conns: 100        # 最大空闲连接数
      max_active_conns: 100      # 最大活跃连接数
      idle_timeout: 1800000      # 空闲连接超时时间（毫秒）
      
      # === 超时配置 ===
      dial_timeout: 5s           # 建立连接的超时时间
      read_timeout: 3s           # 读取数据的超时时间
      write_timeout: 3s          # 写入数据的超时时间
      pool_timeout: 4s           # 从连接池获取连接的超时时间
      
      # === 重试配置 ===
      max_retries: 3             # 操作失败时的最大重试次数
      min_retry_backoff: 8ms     # 重试间隔的最小值
      max_retry_backoff: 512ms   # 重试间隔的最大值
      
      # === 其他配置 ===
      key_prefix: "gohub:"       # 缓存键前缀
      enable_pipelining: true    # 是否启用管道模式
      enable_compression: false  # 是否启用数据压缩

    # 哨兵模式Redis连接示例
    redis_sentinel:
      enabled: false             # 默认禁用
      mode: "sentinel"           # 哨兵模式
      key_expire: 36000     # 缓存过期时间，默认10小时(S)
      
      # === 哨兵配置 ===
      sentinel_addrs:            # 哨兵地址列表
        - "127.0.0.1:26379"
        - "127.0.0.1:26380" 
        - "127.0.0.1:26381"
      master_name: "mymaster"    # 主节点名称
      sentinel_password: ""      # 哨兵密码
      password: "datahub"        # Redis认证密码
      db: 0
      
      # === 连接池配置 ===
      pool_size: 100
      min_idle_conns: 10
      max_idle_conns: 100
      max_active_conns: 100
      idle_timeout: 1800000
      
      # === 超时配置 ===
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s
      pool_timeout: 4s
      
      # === 重试配置 ===
      max_retries: 3
      min_retry_backoff: 8ms
      max_retry_backoff: 512ms
      
      # === 其他配置 ===
      key_prefix: "gohub:sentinel:"
      enable_pipelining: true
      enable_compression: false

    # 集群模式Redis连接示例
    redis_cluster:
      enabled: false             # 默认禁用
      mode: "cluster"            # 集群模式
      key_expire: 36000     # 缓存过期时间，默认10小时(S)
      
      # === 集群配置 ===
      cluster_addrs:             # 集群节点地址列表
        - "127.0.0.1:7000"
        - "127.0.0.1:7001"
        - "127.0.0.1:7002"
        - "127.0.0.1:7003"
        - "127.0.0.1:7004"
        - "127.0.0.1:7005"
      password: ""               # 集群密码
      
      # === 连接池配置 ===
      pool_size: 100
      min_idle_conns: 10
      max_idle_conns: 100
      max_active_conns: 100
      idle_timeout: 1800000
      
      # === 超时配置 ===
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s
      pool_timeout: 4s
      
      # === 重试配置 ===
      max_retries: 3
      min_retry_backoff: 8ms
      max_retry_backoff: 512ms
      
      # === 其他配置 ===
      key_prefix: "gohub:cluster:"
      enable_pipelining: true
      enable_compression: false

