-- SQL Server 方言，由 scripts/db/mysql/HUB_SERVICE_NAMESPACE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
-- 命名空间表 - 存储服务和配置的命名空间信息，用于多租户和多环境隔离
IF OBJECT_ID(N'dbo.HUB_SERVICE_NAMESPACE', N'U') IS NULL
CREATE TABLE HUB_SERVICE_NAMESPACE (
  -- 主键和租户信息
  namespaceId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 关联服务中心实例
  instanceName NVARCHAR(100) NOT NULL,
  environment NVARCHAR(32) NOT NULL,
  
  -- 命名空间基本信息
  namespaceName NVARCHAR(100) NOT NULL,
  namespaceDescription NVARCHAR(500) DEFAULT NULL,
  
  -- 命名空间配置
  serviceQuotaLimit INT DEFAULT 200,
  configQuotaLimit INT DEFAULT 200,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, namespaceId),
  INDEX IDX_SVC_NS_NAME (tenantId, namespaceName),
  INDEX IDX_SVC_NS_INSTANCE (tenantId, instanceName, environment),
  INDEX IDX_SVC_NS_ENV (environment),
  INDEX IDX_SVC_NS_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_SERVICE_NAMESPACE ALTER COLUMN instanceName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_SERVICE_NAMESPACE ALTER COLUMN environment NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_NAMESPACE ALTER COLUMN namespaceName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_SERVICE_NAMESPACE ALTER COLUMN namespaceDescription NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE_NAMESPACE ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_NAMESPACE ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_NAMESPACE ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_NAMESPACE ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_SERVICE_NAMESPACE ALTER COLUMN noteText NVARCHAR(500) NULL;
