-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_ROUTER_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_ROUTER_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_ROUTER_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  routerConfigId NVARCHAR(32) NOT NULL,
  gatewayInstanceId NVARCHAR(32) NOT NULL,
  routerName NVARCHAR(100) NOT NULL,
  routerDesc NVARCHAR(200) DEFAULT NULL,
  
  -- Router基础配置
  defaultPriority INT NOT NULL DEFAULT 100,
  enableRouteCache NVARCHAR(1) NOT NULL DEFAULT N'Y',
  routeCacheTtlSeconds INT NOT NULL DEFAULT 300,
  maxRoutes INT DEFAULT 1000,
  routeMatchTimeout INT DEFAULT 100,
  
  -- Router高级配置
  enableStrictMode NVARCHAR(1) NOT NULL DEFAULT N'N',
  enableMetrics NVARCHAR(1) NOT NULL DEFAULT N'Y',
  enableTracing NVARCHAR(1) NOT NULL DEFAULT N'N',
  caseSensitive NVARCHAR(1) NOT NULL DEFAULT N'Y',
  removeTrailingSlash NVARCHAR(1) NOT NULL DEFAULT N'Y',
  
  -- 路由处理配置
  enableGlobalFilters NVARCHAR(1) NOT NULL DEFAULT N'Y',
  filterExecutionMode NVARCHAR(20) NOT NULL DEFAULT N'SEQUENTIAL',
  maxFilterChainDepth INT DEFAULT 50,
  
  -- 性能优化配置
  enableRoutePooling NVARCHAR(1) NOT NULL DEFAULT N'N',
  routePoolSize INT DEFAULT 100,
  enableAsyncProcessing NVARCHAR(1) NOT NULL DEFAULT N'N',
  
  -- 错误处理配置
  enableFallback NVARCHAR(1) NOT NULL DEFAULT N'Y',
  fallbackRoute NVARCHAR(200) DEFAULT NULL,
  notFoundStatusCode INT NOT NULL DEFAULT 404,
  notFoundMessage NVARCHAR(200) DEFAULT N'Route not found',
  
  -- 自定义配置
  routerMetadata NVARCHAR(MAX) DEFAULT NULL,
  customConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 标准数据库字段
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  
  PRIMARY KEY (tenantId, routerConfigId),
  INDEX IDX_GW_ROUTER_INST (gatewayInstanceId),
  INDEX IDX_GW_ROUTER_NAME (routerName),
  INDEX IDX_GW_ROUTER_ACTIVE (activeFlag),
  INDEX IDX_GW_ROUTER_CACHE (enableRouteCache)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN routerName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN routerDesc NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN enableRouteCache NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN enableStrictMode NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN enableMetrics NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN enableTracing NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN caseSensitive NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN removeTrailingSlash NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN enableGlobalFilters NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN filterExecutionMode NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN enableRoutePooling NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN enableAsyncProcessing NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN enableFallback NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN fallbackRoute NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN notFoundMessage NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTER_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
