-- SQL Server 方言，由 scripts/db/mysql/HUB_AUTH_DATA_PERMISSION.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
-- =====================================================
-- 数据权限表 - 存储用户和角色的数据访问权限
-- =====================================================
IF OBJECT_ID(N'dbo.HUB_AUTH_DATA_PERMISSION', N'U') IS NULL
CREATE TABLE HUB_AUTH_DATA_PERMISSION (
  -- 主键和租户信息
  dataPermissionId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 关联信息
  userId NVARCHAR(32) DEFAULT NULL,
  roleId NVARCHAR(32) DEFAULT NULL,
  
  -- 数据权限信息
  resourceType NVARCHAR(50) NOT NULL,
  resourceCode NVARCHAR(100) NOT NULL,
  scopeValue NVARCHAR(MAX) DEFAULT NULL,
  
  -- 权限条件
  filterCondition NVARCHAR(MAX) DEFAULT NULL,
  columnPermissions NVARCHAR(MAX) DEFAULT NULL,
  operationPermissions NVARCHAR(50) DEFAULT N'read',
  
  -- 生效时间
  effectiveTime DATETIME2 DEFAULT NULL,
  expireTime DATETIME2 DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, dataPermissionId),
  INDEX IDX_AUTH_DATA_PERM_USER (tenantId, userId),
  INDEX IDX_AUTH_DATA_PERM_ROLE (tenantId, roleId),
  INDEX IDX_AUTH_DATA_PERM_RESOURCE (resourceType, resourceCode),
  INDEX IDX_AUTH_DATA_PERM_EXPIRE (expireTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN resourceType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN resourceCode NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN operationPermissions NVARCHAR(50) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_DATA_PERMISSION ALTER COLUMN reserved10 NVARCHAR(500) NULL;
