-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_CIRCUIT_BREAKER_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_CIRCUIT_BREAKER_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  circuitBreakerConfigId NVARCHAR(32) NOT NULL,
  routeConfigId NVARCHAR(32) DEFAULT NULL,
  targetServiceId NVARCHAR(32) DEFAULT NULL,
  breakerName NVARCHAR(100) NOT NULL,
  
  -- 根据CircuitBreakerConfig结构设计基础配置
  keyStrategy NVARCHAR(50) NOT NULL DEFAULT N'node',
  
  -- 阈值配置
  errorRatePercent INT NOT NULL DEFAULT 50,
  minimumRequests INT NOT NULL DEFAULT 10,
  halfOpenMaxRequests INT NOT NULL DEFAULT 3,
  slowCallThreshold INT NOT NULL DEFAULT 60000,
  slowCallRatePercent INT NOT NULL DEFAULT 50,
  
  -- 时间配置
  openTimeoutSeconds INT NOT NULL DEFAULT 60,
  windowSizeSeconds INT NOT NULL DEFAULT 60,
  
  -- 错误处理配置
  errorStatusCode INT NOT NULL DEFAULT 503,
  errorMessage NVARCHAR(500) DEFAULT N'Service temporarily unavailable due to circuit breaker',
  
  -- 存储配置
  storageType NVARCHAR(50) NOT NULL DEFAULT N'memory',
  storageConfig NVARCHAR(MAX) DEFAULT NULL,
  
  configPriority INT NOT NULL DEFAULT 0,
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, circuitBreakerConfigId),
  INDEX IDX_GW_CB_ROUTE (routeConfigId),
  INDEX IDX_GW_CB_SERVICE (targetServiceId),
  INDEX IDX_GW_CB_STRATEGY (keyStrategy),
  INDEX IDX_GW_CB_STORAGE (storageType),
  INDEX IDX_GW_CB_PRIORITY (configPriority)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN breakerName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN keyStrategy NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN errorMessage NVARCHAR(500) NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN storageType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_CIRCUIT_BREAKER_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
