-- SQL Server 方言，由 scripts/db/mysql/HUB_RETENTION_LEASE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_RETENTION_LEASE', N'U') IS NULL
CREATE TABLE HUB_RETENTION_LEASE (
  tenantId NVARCHAR(32) NOT NULL,
  leaseKey NVARCHAR(64) NOT NULL,
  owner NVARCHAR(128) NOT NULL,
  expireTime DATETIME2 NOT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(64) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(64) NOT NULL,
  oprSeqFlag NVARCHAR(64) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(MAX) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  PRIMARY KEY (tenantId, leaseKey)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_RETENTION_LEASE ALTER COLUMN leaseKey NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_RETENTION_LEASE ALTER COLUMN owner NVARCHAR(128) NOT NULL;
ALTER TABLE HUB_RETENTION_LEASE ALTER COLUMN addWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_RETENTION_LEASE ALTER COLUMN editWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_RETENTION_LEASE ALTER COLUMN oprSeqFlag NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_RETENTION_LEASE ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
