-- SQL Server 方言，由 scripts/db/mysql/HUB_SERVICE_CONFIG_DATA.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
-- 配置数据表 - 存储具体的配置数据，支持多种配置格式
IF OBJECT_ID(N'dbo.HUB_SERVICE_CONFIG_DATA', N'U') IS NULL
CREATE TABLE HUB_SERVICE_CONFIG_DATA (
  -- 主键和租户信息
  configDataId NVARCHAR(100) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 关联命名空间和分组
  namespaceId NVARCHAR(32) NOT NULL,
  groupName NVARCHAR(64) NOT NULL DEFAULT N'DEFAULT_GROUP',
  
  -- 配置基本信息
  configContent NVARCHAR(MAX) NOT NULL,
  contentType NVARCHAR(50) DEFAULT N'text',
  
  -- 配置描述和属性
  configDescription NVARCHAR(500) DEFAULT NULL,
  encrypted NVARCHAR(1) DEFAULT N'N',
  
  -- 版本信息
  version BIGINT NOT NULL DEFAULT 1,
  
  -- MD5校验值（用于配置变更检测）
  md5Value NVARCHAR(32) DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, namespaceId, groupName, configDataId),
  INDEX IDX_SVC_CFG_DATA_NS_ID (tenantId, namespaceId),
  INDEX IDX_SVC_CFG_DATA_MD5 (md5Value),
  INDEX IDX_SVC_CFG_DATA_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN groupName NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN contentType NVARCHAR(50) NULL;
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN configDescription NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN encrypted NVARCHAR(1) NULL;
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN md5Value NVARCHAR(32) NULL;
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_DATA ALTER COLUMN noteText NVARCHAR(500) NULL;
