-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_SERVICE_NODE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_SERVICE_NODE', N'U') IS NULL
CREATE TABLE HUB_GW_SERVICE_NODE (
  tenantId NVARCHAR(32) NOT NULL,
  serviceNodeId NVARCHAR(32) NOT NULL,
  serviceDefinitionId VARCHAR(32) NOT NULL,
  nodeId NVARCHAR(100) NOT NULL,
  -- 根据NodeConfig.URL字段设计,分解为host+port+protocol便于查询和管理
  nodeUrl NVARCHAR(500) NOT NULL,
  nodeHost NVARCHAR(100) NOT NULL,
  nodePort INT NOT NULL,
  nodeProtocol NVARCHAR(10) NOT NULL DEFAULT N'HTTP',
  
  -- 根据NodeConfig.Weight字段设计
  nodeWeight INT NOT NULL DEFAULT 100,
  
  -- 根据NodeConfig.Health字段设计
  healthStatus NVARCHAR(1) NOT NULL DEFAULT N'Y',

  -- 根据NodeConfig.Metadata字段设计
  nodeMetadata NVARCHAR(MAX) DEFAULT NULL,
  
  -- 运行时状态字段(非NodeConfig结构,但运维需要)
  nodeStatus INT NOT NULL DEFAULT 1,
  lastHealthCheckTime DATETIME2 DEFAULT NULL,
  healthCheckResult NVARCHAR(MAX) DEFAULT NULL,
  
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, serviceNodeId),
  INDEX IDX_GW_NODE_SERVICE (serviceDefinitionId),
  INDEX IDX_GW_NODE_ENDPOINT (nodeHost, nodePort),
  INDEX IDX_GW_NODE_HEALTH (healthStatus),
  INDEX IDX_GW_NODE_STATUS (nodeStatus)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN nodeUrl NVARCHAR(500) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN nodeHost NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN nodeProtocol NVARCHAR(10) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN healthStatus NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_NODE ALTER COLUMN noteText NVARCHAR(500) NULL;
