-- SQL Server 方言，由 scripts/db/mysql/HUB_CLUSTER_NODE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_CLUSTER_NODE', N'U') IS NULL
CREATE TABLE HUB_CLUSTER_NODE (
  nodeId NVARCHAR(64) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  nodeIp NVARCHAR(100) DEFAULT NULL,
  hostname NVARCHAR(255) DEFAULT NULL,
  startedTime DATETIME2 NOT NULL,
  lastSeenTime DATETIME2 NOT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(64) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(64) NOT NULL,
  oprSeqFlag NVARCHAR(64) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(MAX) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(64) DEFAULT NULL,
  reserved2 NVARCHAR(64) DEFAULT NULL,
  reserved3 NVARCHAR(100) DEFAULT NULL,
  reserved4 NVARCHAR(100) DEFAULT NULL,
  reserved5 NVARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (tenantId, nodeId),
  INDEX IDX_CLS_NODE_SEEN (tenantId, lastSeenTime)
);
