-- SQL Server 方言，由 scripts/db/mysql/HUB_TIMER_SCHEDULER.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_TIMER_SCHEDULER', N'U') IS NULL
CREATE TABLE HUB_TIMER_SCHEDULER (
  schedulerId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  schedulerName NVARCHAR(100) NOT NULL,
  schedulerInstanceId NVARCHAR(100) DEFAULT NULL,
  
  -- 调度器配置
  maxWorkers INT NOT NULL DEFAULT 5,
  queueSize INT NOT NULL DEFAULT 100,
  defaultTimeoutSeconds BIGINT NOT NULL DEFAULT 1800,
  defaultRetries INT NOT NULL DEFAULT 3,
  
  -- 调度器状态
  schedulerStatus INT NOT NULL DEFAULT 1,
  lastStartTime DATETIME2 DEFAULT NULL,
  lastStopTime DATETIME2 DEFAULT NULL,
  
  -- 服务器信息
  serverName NVARCHAR(100) DEFAULT NULL,
  serverIp NVARCHAR(50) DEFAULT NULL,
  serverPort INT DEFAULT NULL,
  
  -- 监控信息
  totalTaskCount INT NOT NULL DEFAULT 0,
  runningTaskCount INT NOT NULL DEFAULT 0,
  lastHeartbeatTime DATETIME2 DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  PRIMARY KEY (tenantId, schedulerId),
  INDEX IDX_TIMER_SCHED_NAME (schedulerName),
  INDEX IDX_TIMER_SCHED_INST (schedulerInstanceId),
  INDEX IDX_TIMER_SCHED_STATUS (schedulerStatus),
  INDEX IDX_TIMER_SCHED_HEART (lastHeartbeatTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN schedulerName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN serverName NVARCHAR(100) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN serverIp NVARCHAR(50) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_SCHEDULER ALTER COLUMN reserved10 NVARCHAR(500) NULL;
