-- SQL Server 方言，由 scripts/db/mysql/HUB_AUTH_AUDIT_LOG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
-- =====================================================
-- 权限审计表 - 记录谁在哪个模块对哪条数据做了何种操作
-- =====================================================
-- 已建库补列：
-- ALTER TABLE HUB_AUTH_AUDIT_LOG ADD moduleCode VARCHAR(64) DEFAULT NULL;
-- ALTER TABLE HUB_AUTH_AUDIT_LOG ADD targetName VARCHAR(255) DEFAULT NULL;
IF OBJECT_ID(N'dbo.HUB_AUTH_AUDIT_LOG', N'U') IS NULL
CREATE TABLE HUB_AUTH_AUDIT_LOG (
  auditId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  userId NVARCHAR(32) NOT NULL,
  userName NVARCHAR(100) DEFAULT NULL,

  action NVARCHAR(32) NOT NULL,
  moduleCode NVARCHAR(64) DEFAULT NULL,
  targetType NVARCHAR(32) DEFAULT NULL,
  targetId NVARCHAR(128) DEFAULT NULL,
  targetName NVARCHAR(255) DEFAULT NULL,
  resourceCode NVARCHAR(128) DEFAULT NULL,
  requestPath NVARCHAR(255) DEFAULT NULL,
  requestMethod NVARCHAR(16) DEFAULT NULL,
  clientIP NVARCHAR(128) DEFAULT NULL,
  result NVARCHAR(1) NOT NULL DEFAULT N'Y',
  detail NVARCHAR(MAX) DEFAULT NULL,

  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',

  PRIMARY KEY (auditId),
  INDEX IDX_AUTH_AUDIT_TENANT (tenantId, addTime),
  INDEX IDX_AUTH_AUDIT_USER (userId, addTime),
  INDEX IDX_AUTH_AUDIT_ACTION (action),
  INDEX IDX_AUTH_AUDIT_MODULE (tenantId, moduleCode, addTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN userName NVARCHAR(100) NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN action NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN moduleCode NVARCHAR(64) NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN targetType NVARCHAR(32) NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN targetName NVARCHAR(255) NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN resourceCode NVARCHAR(128) NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN requestPath NVARCHAR(255) NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN requestMethod NVARCHAR(16) NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN clientIP NVARCHAR(128) NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN result NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_AUDIT_LOG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
