-- SQL Server 方言，由 scripts/db/mysql/HUB_SERVICE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
-- 服务表 - 存储服务的基本信息和元数据
IF OBJECT_ID(N'dbo.HUB_SERVICE', N'U') IS NULL
CREATE TABLE HUB_SERVICE (
  -- 主键和租户信息
  tenantId NVARCHAR(32) NOT NULL,
  namespaceId NVARCHAR(32) NOT NULL,
  groupName NVARCHAR(64) NOT NULL DEFAULT N'DEFAULT_GROUP',
  serviceName NVARCHAR(100) NOT NULL,
  
  -- 服务类型
  serviceType NVARCHAR(50) NOT NULL DEFAULT N'INTERNAL',
  
  -- 服务基本信息
  serviceVersion NVARCHAR(50) DEFAULT NULL,
  serviceDescription NVARCHAR(500) DEFAULT NULL,
  
  -- 外部服务配置（仅当serviceType非INTERNAL时使用）
  externalServiceConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 服务元数据
  metadataJson NVARCHAR(MAX) DEFAULT NULL,
  tagsJson NVARCHAR(MAX) DEFAULT NULL,
  
  -- 服务保护阈值（0-1之间的小数，表示健康实例比例低于该值时触发保护）
  protectThreshold DECIMAL(3,2) DEFAULT 0.00,
  
  -- 服务选择器（用于服务路由）
  selectorJson NVARCHAR(MAX) DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 预留字段
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, namespaceId, groupName, serviceName),
  INDEX IDX_SVC_NS_ID (tenantId, namespaceId),
  INDEX IDX_SVC_NAME (serviceName),
  INDEX IDX_SVC_TYPE (serviceType),
  INDEX IDX_SVC_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_SERVICE ALTER COLUMN groupName NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN serviceName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN serviceType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN serviceVersion NVARCHAR(50) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN serviceDescription NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE ALTER COLUMN reserved10 NVARCHAR(500) NULL;
