-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_RATE_LIMIT_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_RATE_LIMIT_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_RATE_LIMIT_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  rateLimitConfigId NVARCHAR(32) NOT NULL,
  gatewayInstanceId NVARCHAR(32) DEFAULT NULL,
  routeConfigId NVARCHAR(32) DEFAULT NULL,
  limitName NVARCHAR(100) NOT NULL,
  
  -- 修改：统一算法标识格式
  algorithm NVARCHAR(50) NOT NULL DEFAULT N'token-bucket',
  
  -- 修改：限流键策略（替代原limitType和keyExpression）
  keyStrategy NVARCHAR(50) NOT NULL DEFAULT N'ip',
  
  -- 保持原有字段但调整默认值
  limitRate INT NOT NULL,
  burstCapacity INT NOT NULL DEFAULT 0,
  timeWindowSeconds INT NOT NULL DEFAULT 1,
  rejectionStatusCode INT NOT NULL DEFAULT 429,
  rejectionMessage NVARCHAR(200) DEFAULT N'请求过于频繁，请稍后再试',
  configPriority INT NOT NULL DEFAULT 0,
  customConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 保留现有的标准字段
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  
  PRIMARY KEY (tenantId, rateLimitConfigId),
  INDEX IDX_GW_RATE_INST (gatewayInstanceId),
  INDEX IDX_GW_RATE_ROUTE (routeConfigId),
  INDEX IDX_GW_RATE_STRATEGY (keyStrategy),
  INDEX IDX_GW_RATE_ALGORITHM (algorithm),
  INDEX IDX_GW_RATE_PRIORITY (configPriority),
  INDEX IDX_GW_RATE_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN limitName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN algorithm NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN keyStrategy NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN rejectionMessage NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_RATE_LIMIT_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
