-- SQL Server 方言，由 scripts/db/mysql/HUB_TOOL_CONFIG_GROUP.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_TOOL_CONFIG_GROUP', N'U') IS NULL
CREATE TABLE HUB_TOOL_CONFIG_GROUP (
  configGroupId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 分组信息
  groupName NVARCHAR(100) NOT NULL,
  groupDescription NVARCHAR(500) DEFAULT NULL,
  parentGroupId NVARCHAR(32) DEFAULT NULL,
  groupLevel INT DEFAULT 1,
  groupPath NVARCHAR(500) DEFAULT NULL,
  
  -- 分组属性
  groupType NVARCHAR(50) DEFAULT NULL,
  sortOrder INT DEFAULT 100,
  groupIcon NVARCHAR(100) DEFAULT NULL,
  groupColor NVARCHAR(20) DEFAULT NULL,
  
  -- 权限控制
  accessLevel NVARCHAR(20) DEFAULT N'private',
  allowedUsers NVARCHAR(MAX) DEFAULT NULL,
  allowedRoles NVARCHAR(MAX) DEFAULT NULL,
  
  -- 标准字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  PRIMARY KEY (tenantId, configGroupId),
  INDEX IDX_TOOL_GROUP_NAME (groupName),
  INDEX IDX_TOOL_GROUP_PARENT (parentGroupId),
  INDEX IDX_TOOL_GROUP_TYPE (groupType),
  INDEX IDX_TOOL_GROUP_SORT (sortOrder),
  INDEX IDX_TOOL_GROUP_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN groupName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN groupDescription NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN groupPath NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN groupType NVARCHAR(50) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN groupIcon NVARCHAR(100) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN groupColor NVARCHAR(20) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN accessLevel NVARCHAR(20) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG_GROUP ALTER COLUMN reserved10 NVARCHAR(500) NULL;
