-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_BACKEND_TRACE_LOG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_BACKEND_TRACE_LOG', N'U') IS NULL
CREATE TABLE HUB_GW_BACKEND_TRACE_LOG (
  tenantId NVARCHAR(32) NOT NULL,
  traceId NVARCHAR(64) NOT NULL,
  backendTraceId NVARCHAR(64) NOT NULL,

  -- 服务信息（单个后端服务一次转发一条记录）
  serviceDefinitionId VARCHAR(32) DEFAULT NULL,
  serviceName NVARCHAR(300) DEFAULT NULL,

  -- 转发信息
  forwardAddress NVARCHAR(MAX) DEFAULT NULL,
  forwardMethod NVARCHAR(10) DEFAULT NULL,
  forwardPath NVARCHAR(1000) DEFAULT NULL,
  forwardQuery NVARCHAR(MAX) DEFAULT NULL,
  forwardHeaders NVARCHAR(MAX) DEFAULT NULL,
  forwardBody NVARCHAR(MAX) DEFAULT NULL,
  requestSize INT DEFAULT 0,

  -- 负载均衡信息
  loadBalancerStrategy NVARCHAR(100) DEFAULT NULL,
  loadBalancerDecision NVARCHAR(500) DEFAULT NULL,

  -- 时间信息
  requestStartTime DATETIME2(3) NOT NULL,
  responseReceivedTime DATETIME2(3) DEFAULT NULL,
  requestDurationMs INT DEFAULT NULL,

  -- 响应信息
  statusCode INT DEFAULT NULL,
  responseSize INT DEFAULT 0,
  responseHeaders NVARCHAR(MAX) DEFAULT NULL,
  responseBody NVARCHAR(MAX) DEFAULT NULL,

  -- 错误信息
  errorCode NVARCHAR(100) DEFAULT NULL,
  errorMessage NVARCHAR(MAX) DEFAULT NULL,

  -- 状态信息
  successFlag NVARCHAR(1) NOT NULL DEFAULT N'N',
  traceStatus NVARCHAR(20) NOT NULL DEFAULT N'pending',
  retryCount INT NOT NULL DEFAULT 0,

  -- 扩展信息
  extProperty NVARCHAR(MAX) DEFAULT NULL,

  -- 标准数据库字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,

  PRIMARY KEY (traceId, backendTraceId)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN serviceName NVARCHAR(300) NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN forwardMethod NVARCHAR(10) NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN forwardPath NVARCHAR(1000) NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN loadBalancerStrategy NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN loadBalancerDecision NVARCHAR(500) NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN errorCode NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN successFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN traceStatus NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_BACKEND_TRACE_LOG ALTER COLUMN noteText NVARCHAR(500) NULL;


-- 索引设计：参考数据库规范，兼顾多租户与常用查询场景
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_GW_BTRACE_TRACE' AND object_id = OBJECT_ID(N'dbo.HUB_GW_BACKEND_TRACE_LOG'))
CREATE INDEX IDX_GW_BTRACE_TRACE ON HUB_GW_BACKEND_TRACE_LOG (tenantId, traceId);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_GW_BTRACE_SERVICE' AND object_id = OBJECT_ID(N'dbo.HUB_GW_BACKEND_TRACE_LOG'))
CREATE INDEX IDX_GW_BTRACE_SERVICE ON HUB_GW_BACKEND_TRACE_LOG (tenantId, serviceDefinitionId, requestStartTime);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_GW_BTRACE_TIME' AND object_id = OBJECT_ID(N'dbo.HUB_GW_BACKEND_TRACE_LOG'))
CREATE INDEX IDX_GW_BTRACE_TIME ON HUB_GW_BACKEND_TRACE_LOG (requestStartTime);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_GW_BTRACE_TSTATUS' AND object_id = OBJECT_ID(N'dbo.HUB_GW_BACKEND_TRACE_LOG'))
CREATE INDEX IDX_GW_BTRACE_TSTATUS ON HUB_GW_BACKEND_TRACE_LOG (tenantId, traceStatus, requestStartTime);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_GW_BTRACE_ADDTIME' AND object_id = OBJECT_ID(N'dbo.HUB_GW_BACKEND_TRACE_LOG'))
CREATE INDEX IDX_GW_BTRACE_ADDTIME ON HUB_GW_BACKEND_TRACE_LOG (tenantId, addTime);
