-- SQL Server 方言，由 scripts/db/mysql/HUB_TUNNEL_STATIC_NODE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_TUNNEL_STATIC_NODE', N'U') IS NULL
CREATE TABLE HUB_TUNNEL_STATIC_NODE (
  -- 主键和租户
  tunnelStaticNodeId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  tunnelStaticServerId NVARCHAR(32) NOT NULL,
  
  -- 业务字段
  nodeName NVARCHAR(100) NOT NULL,
  nodeDescription NVARCHAR(500) DEFAULT NULL,
  targetAddress NVARCHAR(50) NOT NULL,
  targetPort INT NOT NULL,
  proxyType NVARCHAR(20) NOT NULL DEFAULT N'tcp',
  maxConnections INT DEFAULT 100,
  connectionTimeout INT DEFAULT 30,
  readTimeout INT DEFAULT 30,
  writeTimeout INT DEFAULT 30,
  retryCount INT DEFAULT 3,
  retryInterval INT DEFAULT 5,
  compression NVARCHAR(1) NOT NULL DEFAULT N'N',
  encryption NVARCHAR(1) NOT NULL DEFAULT N'N',
  secretKey NVARCHAR(100) DEFAULT NULL,
  customHeaders NVARCHAR(MAX) DEFAULT NULL,
  nodeStatus NVARCHAR(20) NOT NULL DEFAULT N'active',
  lastHealthCheck DATETIME2 DEFAULT NULL,
  healthCheckStatus NVARCHAR(20) DEFAULT N'unknown',
  currentConnectionCount INT DEFAULT 0,
  totalConnectionCount BIGINT DEFAULT 0,
  totalBytesReceived BIGINT DEFAULT 0,
  totalBytesSent BIGINT DEFAULT 0,
  failureCount INT DEFAULT 0,
  lastFailureTime DATETIME2 DEFAULT NULL,
  nodeConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 预留字段
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  CONSTRAINT PK_TUNNEL_STATIC_NODE PRIMARY KEY (tunnelStaticNodeId),
  CONSTRAINT IDX_TUNNEL_STATIC_NODE_NAME UNIQUE (nodeName),
  CONSTRAINT IDX_TUNNEL_STATIC_NODE_TARGET UNIQUE (tunnelStaticServerId, targetAddress, targetPort),
  INDEX IDX_TUNNEL_STATIC_NODE_TENANT (tenantId),
  INDEX IDX_TUNNEL_STATIC_NODE_SERVER (tunnelStaticServerId),
  INDEX IDX_TUNNEL_STATIC_NODE_TYPE (proxyType),
  INDEX IDX_TUNNEL_STATIC_NODE_STATUS (nodeStatus),
  INDEX IDX_TUNNEL_STATIC_NODE_HEALTH (healthCheckStatus, lastHealthCheck)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN nodeName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN nodeDescription NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN targetAddress NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN proxyType NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN compression NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN encryption NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN secretKey NVARCHAR(100) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN nodeStatus NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN healthCheckStatus NVARCHAR(20) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_NODE ALTER COLUMN reserved10 NVARCHAR(500) NULL;
