-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_ROUTE_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_ROUTE_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_ROUTE_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  routeConfigId NVARCHAR(32) NOT NULL,
  gatewayInstanceId NVARCHAR(32) NOT NULL,
  routeName NVARCHAR(100) NOT NULL,
  routePath NVARCHAR(200) NOT NULL,
  allowedMethods NVARCHAR(200) DEFAULT NULL,
  allowedHosts NVARCHAR(500) DEFAULT NULL,
  matchType INT NOT NULL DEFAULT 1,
  routePriority INT NOT NULL DEFAULT 100,
  stripPathPrefix NVARCHAR(1) NOT NULL DEFAULT N'N',
  rewritePath NVARCHAR(200) DEFAULT NULL,
  enableWebsocket NVARCHAR(1) NOT NULL DEFAULT N'N',
  timeoutMs INT NOT NULL DEFAULT 30000,
  retryCount INT NOT NULL DEFAULT 0,
  retryIntervalMs INT NOT NULL DEFAULT 1000,
  
  -- 服务关联字段，直接关联服务定义表
  serviceDefinitionId VARCHAR(32) DEFAULT NULL,
  
  -- 日志配置关联字段
  logConfigId NVARCHAR(32) DEFAULT NULL,
  
  -- 路由元数据，用于存储额外配置信息
  routeMetadata NVARCHAR(MAX) DEFAULT NULL,
  
  -- 注意：使用activeFlag代替enabled字段，保持数据库设计一致性
  -- activeFlag='Y'表示路由启用，activeFlag='N'表示路由禁用
  -- 在代码中将activeFlag映射为enabled字段
  
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, routeConfigId),
  INDEX IDX_GW_ROUTE_INST (gatewayInstanceId),
  INDEX IDX_GW_ROUTE_SERVICE (serviceDefinitionId),
  INDEX IDX_GW_ROUTE_LOG (logConfigId),
  INDEX IDX_GW_ROUTE_PRIORITY (routePriority),
  INDEX IDX_GW_ROUTE_PATH (routePath),
  INDEX IDX_GW_ROUTE_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN routeName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN routePath NVARCHAR(200) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN allowedMethods NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN allowedHosts NVARCHAR(500) NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN stripPathPrefix NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN rewritePath NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN enableWebsocket NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;


-- 兼容已存在的数据库，修改字段长度
-- 注意：由于字段长度增加到 VARCHAR(1000)，需要先删除索引，修改字段后再重建前缀索引
IF EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'IDX_GW_ROUTE_SERVICE' AND parent_object_id = OBJECT_ID(N'dbo.HUB_GW_ROUTE_CONFIG'))
ALTER TABLE HUB_GW_ROUTE_CONFIG DROP CONSTRAINT IDX_GW_ROUTE_SERVICE;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_GW_ROUTE_SERVICE' AND object_id = OBJECT_ID(N'dbo.HUB_GW_ROUTE_CONFIG') AND is_primary_key = 0 AND is_unique_constraint = 0)
DROP INDEX IDX_GW_ROUTE_SERVICE ON HUB_GW_ROUTE_CONFIG;
ALTER TABLE HUB_GW_ROUTE_CONFIG ALTER COLUMN serviceDefinitionId VARCHAR(1000) NULL;
-- 重建索引，使用前缀索引（前255个字符，255*4=1020字节，在3072字节限制内）
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_GW_ROUTE_SERVICE' AND object_id = OBJECT_ID(N'dbo.HUB_GW_ROUTE_CONFIG'))
CREATE INDEX IDX_GW_ROUTE_SERVICE ON HUB_GW_ROUTE_CONFIG (serviceDefinitionId);

-- 历史库升级：建表已执行过的不会再跑 CREATE，只补列。空值视为服务代理。
IF COL_LENGTH(N'dbo.HUB_GW_ROUTE_CONFIG', N'backendType') IS NULL
ALTER TABLE HUB_GW_ROUTE_CONFIG ADD backendType NVARCHAR(16) DEFAULT N'proxy';
UPDATE HUB_GW_ROUTE_CONFIG SET backendType = N'proxy' WHERE backendType IS NULL OR backendType = N'';
IF COL_LENGTH(N'dbo.HUB_GW_ROUTE_CONFIG', N'redirectStatus') IS NULL
ALTER TABLE HUB_GW_ROUTE_CONFIG ADD redirectStatus INT DEFAULT 0;
IF COL_LENGTH(N'dbo.HUB_GW_ROUTE_CONFIG', N'redirectLocation') IS NULL
ALTER TABLE HUB_GW_ROUTE_CONFIG ADD redirectLocation NVARCHAR(500) DEFAULT NULL;
