-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_PROXY_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_PROXY_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_PROXY_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  proxyConfigId NVARCHAR(32) NOT NULL,
  gatewayInstanceId NVARCHAR(32) NOT NULL,
  proxyName NVARCHAR(100) NOT NULL,
  
  -- 根据ProxyType枚举值设计
  proxyType NVARCHAR(50) NOT NULL DEFAULT N'http',
  
  -- 基础配置
  proxyId NVARCHAR(100) DEFAULT NULL,
  configPriority INT NOT NULL DEFAULT 0,
  
  -- 通用配置，JSON格式存储不同类型的具体配置
  proxyConfig NVARCHAR(MAX) NOT NULL,
  customConfig NVARCHAR(MAX) DEFAULT NULL,
  
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, proxyConfigId),
  INDEX IDX_GW_PROXY_INST (gatewayInstanceId),
  INDEX IDX_GW_PROXY_TYPE (proxyType),
  INDEX IDX_GW_PROXY_PRIORITY (configPriority),
  INDEX IDX_GW_PROXY_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_PROXY_CONFIG ALTER COLUMN proxyName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_PROXY_CONFIG ALTER COLUMN proxyType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_PROXY_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_PROXY_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_PROXY_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_PROXY_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_PROXY_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_PROXY_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_PROXY_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
