-- SQL Server 方言，由 scripts/db/mysql/HUB_SERVICE_NODE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
-- 服务节点表 - 存储服务节点的详细信息，包括网络地址、健康状态等
IF OBJECT_ID(N'dbo.HUB_SERVICE_NODE', N'U') IS NULL
CREATE TABLE HUB_SERVICE_NODE (
  -- 主键和租户信息
  nodeId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 关联服务（通过联合主键关联HUB_SERVICE表）
  namespaceId NVARCHAR(32) NOT NULL,
  groupName NVARCHAR(64) NOT NULL,
  serviceName NVARCHAR(100) NOT NULL,
  
  -- 网络连接信息
  ipAddress NVARCHAR(50) NOT NULL,
  portNumber INT NOT NULL,
  
  -- 节点状态信息
  instanceStatus NVARCHAR(20) NOT NULL DEFAULT N'UP',
  healthyStatus NVARCHAR(20) NOT NULL DEFAULT N'UNKNOWN',
  ephemeral NVARCHAR(1) NOT NULL DEFAULT N'Y',
  
  -- 负载均衡配置
  weight DECIMAL(6,2) NOT NULL DEFAULT 1.00,
  
  -- 节点元数据
  metadataJson NVARCHAR(MAX) DEFAULT NULL,
  
  -- 时间戳信息
  registerTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  lastBeatTime DATETIME2 DEFAULT NULL,
  lastCheckTime DATETIME2 DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, nodeId),
  CONSTRAINT IDX_SVC_NODE_UNIQUE UNIQUE (tenantId, namespaceId, groupName, serviceName, ipAddress, portNumber),
  INDEX IDX_SVC_NODE_SERVICE (tenantId, namespaceId, groupName, serviceName),
  INDEX IDX_SVC_NODE_SERVICE_NAME (tenantId, serviceName),
  INDEX IDX_SVC_NODE_NS_ID (tenantId, namespaceId),
  INDEX IDX_SVC_NODE_GROUP_NAME (tenantId, namespaceId, groupName),
  INDEX IDX_SVC_NODE_IP_PORT (ipAddress, portNumber),
  INDEX IDX_SVC_NODE_STATUS (instanceStatus),
  INDEX IDX_SVC_NODE_HEALTHY (healthyStatus),
  INDEX IDX_SVC_NODE_EPHEMERAL (ephemeral),
  INDEX IDX_SVC_NODE_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN groupName NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN serviceName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN ipAddress NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN instanceStatus NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN healthyStatus NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN ephemeral NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_SERVICE_NODE ALTER COLUMN noteText NVARCHAR(500) NULL;
