-- SQL Server 方言，由 scripts/db/mysql/HUB_CLUSTER_EVENT_ACK.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_CLUSTER_EVENT_ACK', N'U') IS NULL
CREATE TABLE HUB_CLUSTER_EVENT_ACK (
  -- 主键和租户信息
  ackId NVARCHAR(64) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  eventId NVARCHAR(64) NOT NULL,
  
  -- 处理节点
  nodeId NVARCHAR(100) NOT NULL,
  nodeIp NVARCHAR(100) DEFAULT NULL,
  
  -- 处理状态
  ackStatus NVARCHAR(20) NOT NULL DEFAULT N'PENDING',
  processTime DATETIME2 DEFAULT NULL,
  resultMessage NVARCHAR(2000) DEFAULT NULL,
  retryCount INT NOT NULL DEFAULT 0,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(64) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(64) NOT NULL,
  oprSeqFlag NVARCHAR(64) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(MAX) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, ackId),
  -- 优化后的复合索引：支持 NOT EXISTS 子查询高效执行
  -- 查询模式: WHERE eventId=? AND nodeId=? AND ackStatus='SUCCESS'
  INDEX IDX_CLS_ACK_EVT_NODE (eventId, nodeId, ackStatus),
  -- 辅助索引：用于按节点查询处理状态
  INDEX IDX_CLS_ACK_NODE (nodeId, ackStatus, processTime),
  -- 辅助索引：用于清理任务
  INDEX IDX_CLS_ACK_CLEANUP (tenantId, addTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN nodeIp NVARCHAR(100) NULL;
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN ackStatus NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN resultMessage NVARCHAR(2000) NULL;
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN addWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN editWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN oprSeqFlag NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_CLUSTER_EVENT_ACK ALTER COLUMN reserved3 NVARCHAR(500) NULL;
