-- SQL Server 方言，由 scripts/db/mysql/HUB_METRIC_NETWORK_LOG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_METRIC_NETWORK_LOG', N'U') IS NULL
CREATE TABLE HUB_METRIC_NETWORK_LOG (
  metricNetworkLogId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  metricServerId NVARCHAR(32) NOT NULL,
  interfaceName NVARCHAR(100) NOT NULL,
  hardwareAddr NVARCHAR(50) DEFAULT NULL,
  ipAddresses NVARCHAR(MAX) DEFAULT NULL,
  interfaceStatus NVARCHAR(20) NOT NULL,
  interfaceType NVARCHAR(50) DEFAULT NULL,
  bytesReceived BIGINT NOT NULL DEFAULT 0,
  bytesSent BIGINT NOT NULL DEFAULT 0,
  packetsReceived BIGINT NOT NULL DEFAULT 0,
  packetsSent BIGINT NOT NULL DEFAULT 0,
  errorsReceived BIGINT NOT NULL DEFAULT 0,
  errorsSent BIGINT NOT NULL DEFAULT 0,
  droppedReceived BIGINT NOT NULL DEFAULT 0,
  droppedSent BIGINT NOT NULL DEFAULT 0,
  receiveRate DECIMAL(20,2) DEFAULT 0,
  sendRate DECIMAL(20,2) DEFAULT 0,
  collectTime DATETIME2 NOT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, metricNetworkLogId),
  INDEX IDX_METRIC_NETWORK_SERVER (metricServerId),
  INDEX IDX_METRIC_NETWORK_TIME (collectTime),
  INDEX IDX_METRIC_NETWORK_INTERFACE (interfaceName),
  INDEX IDX_METRIC_NETWORK_STATUS (interfaceStatus),
  INDEX IDX_METRIC_NETWORK_ACTIVE (activeFlag),
  INDEX IDX_METRIC_NETWORK_SRV_TIME (metricServerId, collectTime),
  INDEX IDX_METRIC_NETWORK_SRV_INT (metricServerId, interfaceName),
  INDEX IDX_METRIC_NETWORK_TNT_TIME (tenantId, collectTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN interfaceName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN hardwareAddr NVARCHAR(50) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN interfaceStatus NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN interfaceType NVARCHAR(50) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_NETWORK_LOG ALTER COLUMN reserved10 NVARCHAR(500) NULL;
