-- SQL Server 方言，由 scripts/db/mysql/HUB_TOOL_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_TOOL_CONFIG', N'U') IS NULL
CREATE TABLE HUB_TOOL_CONFIG (
  toolConfigId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 工具基础信息
  toolName NVARCHAR(100) NOT NULL,
  toolType NVARCHAR(50) NOT NULL,
  toolVersion NVARCHAR(20) DEFAULT NULL,
  configName NVARCHAR(100) NOT NULL,
  configDescription NVARCHAR(500) DEFAULT NULL,
  
  -- 分组信息
  configGroupId NVARCHAR(32) DEFAULT NULL,
  configGroupName NVARCHAR(100) DEFAULT NULL,
  
  -- 连接配置
  hostAddress NVARCHAR(255) DEFAULT NULL,
  portNumber INT DEFAULT NULL,
  protocolType NVARCHAR(20) DEFAULT NULL,
  
  -- 认证配置
  authType NVARCHAR(50) DEFAULT NULL,
  userName NVARCHAR(100) DEFAULT NULL,
  passwordEncrypted NVARCHAR(500) DEFAULT NULL,
  keyFilePath NVARCHAR(500) DEFAULT NULL,
  keyFileContent NVARCHAR(MAX) DEFAULT NULL,
  
  -- 配置参数
  configParameters NVARCHAR(MAX) DEFAULT NULL,
  environmentVariables NVARCHAR(MAX) DEFAULT NULL,
  customSettings NVARCHAR(MAX) DEFAULT NULL,
  
  -- 状态和控制
  configStatus NVARCHAR(1) NOT NULL DEFAULT N'Y',
  defaultFlag NVARCHAR(1) NOT NULL DEFAULT N'N',
  priorityLevel INT DEFAULT 100,
  
  -- 安全和加密
  encryptionType NVARCHAR(50) DEFAULT NULL,
  encryptionKey NVARCHAR(100) DEFAULT NULL,
  
  -- 标准字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  PRIMARY KEY (tenantId, toolConfigId),
  INDEX IDX_TOOL_CONFIG_NAME (toolName),
  INDEX IDX_TOOL_CONFIG_TYPE (toolType),
  INDEX IDX_TOOL_CONFIG_CFGNAME (configName),
  INDEX IDX_TOOL_CONFIG_GROUP (configGroupId),
  INDEX IDX_TOOL_CONFIG_STATUS (configStatus),
  INDEX IDX_TOOL_CONFIG_DEFAULT (defaultFlag),
  INDEX IDX_TOOL_CONFIG_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN toolName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN toolType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN toolVersion NVARCHAR(20) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN configName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN configDescription NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN configGroupName NVARCHAR(100) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN hostAddress NVARCHAR(255) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN protocolType NVARCHAR(20) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN authType NVARCHAR(50) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN userName NVARCHAR(100) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN passwordEncrypted NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN keyFilePath NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN configStatus NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN defaultFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN encryptionType NVARCHAR(50) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN encryptionKey NVARCHAR(100) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_TOOL_CONFIG ALTER COLUMN reserved10 NVARCHAR(500) NULL;
