-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_AUTH_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_AUTH_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_AUTH_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  authConfigId NVARCHAR(32) NOT NULL,
  gatewayInstanceId NVARCHAR(32) DEFAULT NULL,
  routeConfigId NVARCHAR(32) DEFAULT NULL,
  authName NVARCHAR(100) NOT NULL,
  authType NVARCHAR(50) NOT NULL,
  authStrategy NVARCHAR(50) DEFAULT N'REQUIRED',
  authConfig NVARCHAR(MAX) NOT NULL,
  exemptPaths NVARCHAR(MAX) DEFAULT NULL,
  exemptHeaders NVARCHAR(MAX) DEFAULT NULL,
  failureStatusCode INT NOT NULL DEFAULT 401,
  failureMessage NVARCHAR(200) DEFAULT N'认证失败',
  configPriority INT NOT NULL DEFAULT 0,
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, authConfigId),
  INDEX IDX_GW_AUTH_INST (gatewayInstanceId),
  INDEX IDX_GW_AUTH_ROUTE (routeConfigId),
  INDEX IDX_GW_AUTH_TYPE (authType),
  INDEX IDX_GW_AUTH_PRIORITY (configPriority)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN authName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN authType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN authStrategy NVARCHAR(50) NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN failureMessage NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_AUTH_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
