-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_INSTANCE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_INSTANCE', N'U') IS NULL
CREATE TABLE HUB_GW_INSTANCE (
  tenantId NVARCHAR(32) NOT NULL,
  gatewayInstanceId NVARCHAR(32) NOT NULL,
  instanceName NVARCHAR(100) NOT NULL,
  instanceDesc NVARCHAR(200) DEFAULT NULL,
  bindAddress NVARCHAR(100) DEFAULT N'0.0.0.0',

  -- HTTP/HTTPS 端口配置
  httpPort INT DEFAULT NULL,
  httpsPort INT DEFAULT NULL,
  tlsEnabled NVARCHAR(1) NOT NULL DEFAULT N'N',

  -- 证书配置 - 支持文件路径和数据库存储
  certStorageType NVARCHAR(20) NOT NULL DEFAULT N'FILE',
  certFilePath NVARCHAR(255) DEFAULT NULL,
  keyFilePath NVARCHAR(255) DEFAULT NULL,
  certContent NVARCHAR(MAX) DEFAULT NULL,
  keyContent NVARCHAR(MAX) DEFAULT NULL,
  certChainContent NVARCHAR(MAX) DEFAULT NULL,
  certPassword NVARCHAR(255) DEFAULT NULL,

  -- Go HTTP Server 核心配置
  maxConnections INT NOT NULL DEFAULT 10000,
  readTimeoutMs INT NOT NULL DEFAULT 30000,
  writeTimeoutMs INT NOT NULL DEFAULT 30000,
  idleTimeoutMs INT NOT NULL DEFAULT 60000,
  maxHeaderBytes INT NOT NULL DEFAULT 1048576,

  -- 性能和并发配置
  maxWorkers INT NOT NULL DEFAULT 1000,
  keepAliveEnabled NVARCHAR(1) NOT NULL DEFAULT N'Y',
  tcpKeepAliveEnabled NVARCHAR(1) NOT NULL DEFAULT N'Y',
  gracefulShutdownTimeoutMs INT NOT NULL DEFAULT 30000,

  -- TLS安全配置
  enableHttp2 NVARCHAR(1) NOT NULL DEFAULT N'Y',
  tlsVersion NVARCHAR(10) DEFAULT N'1.2',
  tlsCipherSuites NVARCHAR(1000) DEFAULT NULL,
  disableGeneralOptionsHandler NVARCHAR(1) NOT NULL DEFAULT N'N',
  -- 日志配置关联字段
  logConfigId NVARCHAR(32) DEFAULT NULL,
  healthStatus NVARCHAR(1) NOT NULL DEFAULT N'Y',
  lastHeartbeatTime DATETIME2 DEFAULT NULL,
  instanceMetadata NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, gatewayInstanceId),
  INDEX IDX_GW_INST_BIND_HTTP (bindAddress, httpPort),
  INDEX IDX_GW_INST_BIND_HTTPS (bindAddress, httpsPort),
  INDEX IDX_GW_INST_LOG (logConfigId),
  INDEX IDX_GW_INST_HEALTH (healthStatus),
  INDEX IDX_GW_INST_TLS (tlsEnabled)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN instanceName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN instanceDesc NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN bindAddress NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN tlsEnabled NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN certStorageType NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN certFilePath NVARCHAR(255) NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN keyFilePath NVARCHAR(255) NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN certPassword NVARCHAR(255) NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN keepAliveEnabled NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN tcpKeepAliveEnabled NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN enableHttp2 NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN tlsVersion NVARCHAR(10) NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN tlsCipherSuites NVARCHAR(1000) NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN disableGeneralOptionsHandler NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN healthStatus NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_INSTANCE ALTER COLUMN noteText NVARCHAR(500) NULL;
