-- SQL Server 方言，由 scripts/db/mysql/HUB_ALERT_LOG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_ALERT_LOG', N'U') IS NULL
CREATE TABLE HUB_ALERT_LOG (
  -- 主键和租户
  tenantId NVARCHAR(32) NOT NULL,
  alertLogId NVARCHAR(32) NOT NULL,
  
  -- 告警基本信息
  alertLevel NVARCHAR(20) NOT NULL DEFAULT N'INFO',
  alertType NVARCHAR(100) DEFAULT NULL,
  alertTitle NVARCHAR(500) NOT NULL,
  alertContent NVARCHAR(MAX) DEFAULT NULL,
  alertTimestamp DATETIME2 NOT NULL,
  
  -- 关联信息
  channelName NVARCHAR(100) DEFAULT NULL,
  
  -- 发送信息
  sendStatus NVARCHAR(20) DEFAULT NULL,
  sendTime DATETIME2 DEFAULT NULL,
  sendResult NVARCHAR(MAX) DEFAULT NULL,
  sendErrorMessage NVARCHAR(MAX) DEFAULT NULL,
  
  -- 标签和扩展信息
  alertTags NVARCHAR(MAX) DEFAULT NULL,
  alertExtra NVARCHAR(MAX) DEFAULT NULL,
  tableData NVARCHAR(MAX) DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 预留字段
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, alertLogId),
  INDEX IDX_ALERT_LOG_TENANT (tenantId),
  INDEX IDX_ALERT_LOG_LEVEL (alertLevel),
  INDEX IDX_ALERT_LOG_TYPE (alertType),
  INDEX IDX_ALERT_LOG_TIMESTAMP (alertTimestamp),
  INDEX IDX_ALERT_LOG_CHANNEL (channelName),
  INDEX IDX_ALERT_LOG_SEND_STATUS (sendStatus),
  INDEX idx_ALERT_LOG_TIME_STATUS (alertTimestamp, sendStatus),
  INDEX IDX_ALERT_LOG_CLEANUP (tenantId, alertTimestamp)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN alertLevel NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN alertType NVARCHAR(100) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN alertTitle NVARCHAR(500) NOT NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN channelName NVARCHAR(100) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN sendStatus NVARCHAR(20) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_LOG ALTER COLUMN reserved10 NVARCHAR(500) NULL;
