-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_CORS_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_CORS_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_CORS_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  corsConfigId NVARCHAR(32) NOT NULL,
  gatewayInstanceId NVARCHAR(32) DEFAULT NULL,
  routeConfigId NVARCHAR(32) DEFAULT NULL,
  configName NVARCHAR(100) NOT NULL,
  allowOrigins NVARCHAR(MAX) NOT NULL,
  allowMethods NVARCHAR(200) NOT NULL DEFAULT N'GET,POST,PUT,DELETE,OPTIONS',
  allowHeaders NVARCHAR(MAX) DEFAULT NULL,
  exposeHeaders NVARCHAR(MAX) DEFAULT NULL,
  allowCredentials NVARCHAR(1) NOT NULL DEFAULT N'N',
  maxAgeSeconds INT NOT NULL DEFAULT 86400,
  configPriority INT NOT NULL DEFAULT 0,
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, corsConfigId),
  INDEX IDX_GW_CORS_INST (gatewayInstanceId),
  INDEX IDX_GW_CORS_ROUTE (routeConfigId),
  INDEX IDX_GW_CORS_PRIORITY (configPriority)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN configName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN allowMethods NVARCHAR(200) NOT NULL;
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN allowCredentials NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_CORS_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
