-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_LOG_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_LOG_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_LOG_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  logConfigId NVARCHAR(32) NOT NULL,
  configName NVARCHAR(100) NOT NULL,
  configDesc NVARCHAR(200) DEFAULT NULL,
  
  -- 日志内容控制
  logFormat NVARCHAR(50) NOT NULL DEFAULT N'JSON',
  recordRequestBody NVARCHAR(1) NOT NULL DEFAULT N'N',
  recordResponseBody NVARCHAR(1) NOT NULL DEFAULT N'N',
  recordHeaders NVARCHAR(1) NOT NULL DEFAULT N'Y',
  maxBodySizeBytes INT NOT NULL DEFAULT 4096,
  
  -- 日志输出目标配置
  outputTargets NVARCHAR(200) NOT NULL DEFAULT N'CONSOLE',
  fileConfig NVARCHAR(MAX) DEFAULT NULL,
  databaseConfig NVARCHAR(MAX) DEFAULT NULL,
  mongoConfig NVARCHAR(MAX) DEFAULT NULL,
  elasticsearchConfig NVARCHAR(MAX) DEFAULT NULL,
  clickhouseConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 异步和批量处理配置
  enableAsyncLogging NVARCHAR(1) NOT NULL DEFAULT N'Y',
  asyncQueueSize INT NOT NULL DEFAULT 10000,
  asyncFlushIntervalMs INT NOT NULL DEFAULT 1000,
  enableBatchProcessing NVARCHAR(1) NOT NULL DEFAULT N'Y',
  batchSize INT NOT NULL DEFAULT 100,
  batchTimeoutMs INT NOT NULL DEFAULT 5000,
  
  -- 日志保留和轮转配置
  logRetentionDays INT NOT NULL DEFAULT 30,
  enableFileRotation NVARCHAR(1) NOT NULL DEFAULT N'Y',
  maxFileSizeMB INT DEFAULT 100,
  maxFileCount INT DEFAULT 10,
  rotationPattern NVARCHAR(100) DEFAULT N'DAILY',
  
  -- 敏感数据处理
  enableSensitiveDataMasking NVARCHAR(1) NOT NULL DEFAULT N'Y',
  sensitiveFields NVARCHAR(MAX) DEFAULT NULL,
  maskingPattern NVARCHAR(100) DEFAULT N'***',
  
  -- 性能优化配置
  bufferSize INT NOT NULL DEFAULT 8192,
  flushThreshold INT NOT NULL DEFAULT 100,
  
  configPriority INT NOT NULL DEFAULT 0,
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, logConfigId),
  INDEX idx_HUB_GW_LOG_CONFIG_name (configName),
  INDEX idx_HUB_GW_LOG_CONFIG_priority (configPriority)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN configName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN configDesc NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN logFormat NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN recordRequestBody NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN recordResponseBody NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN recordHeaders NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN outputTargets NVARCHAR(200) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN enableAsyncLogging NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN enableBatchProcessing NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN enableFileRotation NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN rotationPattern NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN enableSensitiveDataMasking NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN maskingPattern NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_LOG_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
