-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_FILTER_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_FILTER_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_FILTER_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  filterConfigId NVARCHAR(32) NOT NULL,
  gatewayInstanceId NVARCHAR(32) DEFAULT NULL,
  routeConfigId NVARCHAR(32) DEFAULT NULL,
  filterName NVARCHAR(100) NOT NULL,
  
  -- 根据FilterType枚举值设计
  filterType NVARCHAR(50) NOT NULL,
  
  -- 根据FilterAction枚举值设计
  filterAction NVARCHAR(50) NOT NULL,
  
  filterOrder INT NOT NULL DEFAULT 0,
  filterConfig NVARCHAR(MAX) NOT NULL,
  filterDesc NVARCHAR(200) DEFAULT NULL,
  
  -- 根据FilterConfig结构设计的附属字段
  configId NVARCHAR(100) DEFAULT NULL,
  
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, filterConfigId),
  INDEX IDX_GW_FILTER_INST (gatewayInstanceId),
  INDEX IDX_GW_FILTER_ROUTE (routeConfigId),
  INDEX IDX_GW_FILTER_TYPE (filterType),
  INDEX IDX_GW_FILTER_ACTION (filterAction),
  INDEX IDX_GW_FILTER_ORDER (filterOrder),
  INDEX IDX_GW_FILTER_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN filterName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN filterType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN filterAction NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN filterDesc NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_FILTER_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
