-- SQL Server 方言，由 scripts/db/mysql/HUB_TIMER_TASK.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_TIMER_TASK', N'U') IS NULL
CREATE TABLE HUB_TIMER_TASK (
  -- 主键信息
  taskId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 任务配置信息
  taskName NVARCHAR(200) NOT NULL,
  taskDescription NVARCHAR(500) DEFAULT NULL,
  taskPriority INT NOT NULL DEFAULT 1,
  schedulerId NVARCHAR(32) DEFAULT NULL,
  schedulerName NVARCHAR(100) DEFAULT NULL,
  
  -- 调度配置
  scheduleType INT NOT NULL,
  cronExpression NVARCHAR(100) DEFAULT NULL,
  intervalSeconds BIGINT DEFAULT NULL,
  delaySeconds BIGINT DEFAULT NULL,
  startTime DATETIME2 DEFAULT NULL,
  endTime DATETIME2 DEFAULT NULL,
  
  -- 执行配置
  maxRetries INT NOT NULL DEFAULT 0,
  retryIntervalSeconds BIGINT NOT NULL DEFAULT 60,
  timeoutSeconds BIGINT NOT NULL DEFAULT 1800,
  taskParams NVARCHAR(MAX) DEFAULT NULL,
  
  -- 任务执行器配置 - 关联到具体工具配置
  executorType NVARCHAR(50) DEFAULT NULL,
  toolConfigId NVARCHAR(32) DEFAULT NULL,
  toolConfigName NVARCHAR(100) DEFAULT NULL,
  operationType NVARCHAR(100) DEFAULT NULL,
  operationConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 运行时状态
  taskStatus INT NOT NULL DEFAULT 1,
  nextRunTime DATETIME2 DEFAULT NULL,
  lastRunTime DATETIME2 DEFAULT NULL,
  runCount BIGINT NOT NULL DEFAULT 0,
  successCount BIGINT NOT NULL DEFAULT 0,
  failureCount BIGINT NOT NULL DEFAULT 0,
  
  -- 最后执行结果
  lastExecutionId NVARCHAR(32) DEFAULT NULL,
  lastExecutionStartTime DATETIME2 DEFAULT NULL,
  lastExecutionEndTime DATETIME2 DEFAULT NULL,
  lastExecutionDurationMs BIGINT DEFAULT NULL,
  lastExecutionStatus INT DEFAULT NULL,
  lastResultSuccess NVARCHAR(1) DEFAULT NULL,
  lastErrorMessage NVARCHAR(MAX) DEFAULT NULL,
  lastRetryCount INT DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  PRIMARY KEY (tenantId, taskId),
  INDEX IDX_TIMER_TASK_NAME (taskName),
  INDEX IDX_TIMER_TASK_SCHED (schedulerId),
  INDEX IDX_TIMER_TASK_TYPE (scheduleType),
  INDEX IDX_TIMER_TASK_STATUS (taskStatus),
  INDEX IDX_TIMER_TASK_NEXT (nextRunTime),
  INDEX IDX_TIMER_TASK_LAST (lastRunTime),
  INDEX IDX_TIMER_TASK_ACTIVE (activeFlag),
  INDEX IDX_TIMER_TASK_EXEC (executorType),
  INDEX IDX_TIMER_TASK_TOOL (toolConfigId),
  INDEX IDX_TIMER_TASK_OP (operationType)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN taskName NVARCHAR(200) NOT NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN taskDescription NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN schedulerName NVARCHAR(100) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN cronExpression NVARCHAR(100) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN executorType NVARCHAR(50) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN toolConfigName NVARCHAR(100) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN operationType NVARCHAR(100) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN lastResultSuccess NVARCHAR(1) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_TASK ALTER COLUMN reserved10 NVARCHAR(500) NULL;
