-- SQL Server 方言，由 scripts/db/mysql/HUB_CLUSTER_EVENT.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_CLUSTER_EVENT', N'U') IS NULL
CREATE TABLE HUB_CLUSTER_EVENT (
  -- 主键和租户信息
  eventId NVARCHAR(64) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 事件来源(发布者)
  sourceNodeId NVARCHAR(100) NOT NULL,
  sourceNodeIp NVARCHAR(100) DEFAULT NULL,
  
  -- 事件信息
  eventType NVARCHAR(50) NOT NULL,
  eventAction NVARCHAR(50) NOT NULL,
  eventPayload NVARCHAR(MAX) DEFAULT NULL,
  
  -- 事件时间
  eventTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  expireTime DATETIME2 DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(64) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(64) NOT NULL,
  oprSeqFlag NVARCHAR(64) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(MAX) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, eventId),
  -- 优化后的复合索引：支持高效的待处理事件查询
  -- 查询模式: WHERE tenantId=? AND activeFlag='Y' AND eventTime>? AND sourceNodeId!=?
  INDEX IDX_CLS_EVT_QUERY (tenantId, activeFlag, eventTime, eventId),
  -- 辅助索引：用于特定场景查询
  INDEX IDX_CLS_EVT_SOURCE (sourceNodeId),
  INDEX IDX_CLS_EVT_TYPE (eventType, eventTime),
  INDEX IDX_CLS_EVT_EXPIRE (expireTime),
  INDEX IDX_CLS_EVT_CLEANUP (tenantId, eventTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN sourceNodeIp NVARCHAR(100) NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN eventType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN eventAction NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN addWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN editWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN oprSeqFlag NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_CLUSTER_EVENT ALTER COLUMN reserved5 NVARCHAR(500) NULL;
