-- SQL Server 方言，由 scripts/db/mysql/HUB_SYS_SETTING.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_SYS_SETTING', N'U') IS NULL
CREATE TABLE HUB_SYS_SETTING (
  tenantId NVARCHAR(32) NOT NULL,
  groupCode NVARCHAR(64) NOT NULL,
  content NVARCHAR(MAX) NOT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(64) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(64) NOT NULL,
  oprSeqFlag NVARCHAR(64) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(MAX) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  PRIMARY KEY (tenantId, groupCode)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_SYS_SETTING ALTER COLUMN groupCode NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SYS_SETTING ALTER COLUMN addWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SYS_SETTING ALTER COLUMN editWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SYS_SETTING ALTER COLUMN oprSeqFlag NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SYS_SETTING ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
