-- SQL Server 方言，由 scripts/db/mysql/HUB_TUNNEL_STATIC_SERVER.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_TUNNEL_STATIC_SERVER', N'U') IS NULL
CREATE TABLE HUB_TUNNEL_STATIC_SERVER (
  -- 主键和租户
  tunnelStaticServerId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 业务字段
  serverName NVARCHAR(100) NOT NULL,
  serverDescription NVARCHAR(500) DEFAULT NULL,
  listenAddress NVARCHAR(50) NOT NULL DEFAULT N'0.0.0.0',
  listenPort INT NOT NULL,
  serverType NVARCHAR(20) NOT NULL DEFAULT N'tcp',
  maxConnections INT NOT NULL DEFAULT 1000,
  connectionTimeout INT NOT NULL DEFAULT 60,
  readTimeout INT NOT NULL DEFAULT 30,
  writeTimeout INT NOT NULL DEFAULT 30,
  tlsEnable NVARCHAR(1) NOT NULL DEFAULT N'N',
  tlsCertFile NVARCHAR(255) DEFAULT NULL,
  tlsKeyFile NVARCHAR(255) DEFAULT NULL,
  tlsCaFile NVARCHAR(255) DEFAULT NULL,
  logLevel NVARCHAR(10) NOT NULL DEFAULT N'info',
  logFile NVARCHAR(255) DEFAULT NULL,
  serverStatus NVARCHAR(20) NOT NULL DEFAULT N'stopped',
  startTime DATETIME2 DEFAULT NULL,
  stopTime DATETIME2 DEFAULT NULL,
  currentConnectionCount INT DEFAULT 0,
  totalConnectionCount BIGINT DEFAULT 0,
  totalBytesReceived BIGINT DEFAULT 0,
  totalBytesSent BIGINT DEFAULT 0,
  healthCheckType NVARCHAR(20) DEFAULT N'tcp',
  healthCheckUrl NVARCHAR(255) DEFAULT NULL,
  healthCheckInterval INT DEFAULT 30,
  healthCheckTimeout INT DEFAULT 5,
  healthCheckMaxFailures INT DEFAULT 3,
  loadBalanceType NVARCHAR(20) DEFAULT N'roundrobin',
  serverConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 预留字段
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  CONSTRAINT PK_TUNNEL_STATIC_SVR PRIMARY KEY (tunnelStaticServerId),
  CONSTRAINT IDX_TUNNEL_STATIC_SVR_NAME UNIQUE (serverName),
  CONSTRAINT IDX_TUNNEL_STATIC_SVR_PORT UNIQUE (listenAddress, listenPort, serverType),
  INDEX IDX_TUNNEL_STATIC_SVR_TENANT (tenantId),
  INDEX IDX_TUNNEL_STATIC_SVR_STATUS (serverStatus),
  INDEX IDX_TUNNEL_STATIC_SVR_TYPE (serverType)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN serverName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN serverDescription NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN listenAddress NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN serverType NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN tlsEnable NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN tlsCertFile NVARCHAR(255) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN tlsKeyFile NVARCHAR(255) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN tlsCaFile NVARCHAR(255) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN logLevel NVARCHAR(10) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN logFile NVARCHAR(255) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN serverStatus NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN healthCheckType NVARCHAR(20) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN healthCheckUrl NVARCHAR(255) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN loadBalanceType NVARCHAR(20) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_TUNNEL_STATIC_SERVER ALTER COLUMN reserved10 NVARCHAR(500) NULL;
