-- SQL Server 方言，由 scripts/db/mysql/HUB_SERVICE_CONFIG_HISTORY.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
-- 配置历史表 - 记录配置的变更历史，支持配置回滚和审计
IF OBJECT_ID(N'dbo.HUB_SERVICE_CONFIG_HISTORY', N'U') IS NULL
CREATE TABLE HUB_SERVICE_CONFIG_HISTORY (
  -- 主键和租户信息
  configHistoryId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 关联配置数据
  configDataId NVARCHAR(100) NOT NULL,
  namespaceId NVARCHAR(32) NOT NULL,
  groupName NVARCHAR(64) NOT NULL,
  
  -- 变更信息
  changeType NVARCHAR(20) NOT NULL,
  oldContent NVARCHAR(MAX) DEFAULT NULL,
  newContent NVARCHAR(MAX) NOT NULL,
  oldVersion BIGINT DEFAULT NULL,
  newVersion BIGINT NOT NULL,
  oldMd5Value NVARCHAR(32) DEFAULT NULL,
  newMd5Value NVARCHAR(32) NOT NULL,
  
  -- 变更原因和操作人
  changeReason NVARCHAR(500) DEFAULT NULL,
  changedBy NVARCHAR(32) NOT NULL,
  changedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, configHistoryId),
  INDEX IDX_SVC_CFG_HIST_DATA_ID (tenantId, configDataId),
  INDEX IDX_SVC_CFG_HIST_NS_ID (tenantId, namespaceId),
  INDEX IDX_SVC_CFG_HIST_GROUP_NAME (tenantId, namespaceId, groupName),
  INDEX IDX_SVC_CFG_HIST_TYPE (changeType),
  INDEX IDX_SVC_CFG_HIST_TIME (changedAt),
  INDEX IDX_SVC_CFG_HIST_BY (changedBy),
  INDEX IDX_SVC_CFG_HIST_VERSION (newVersion)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN groupName NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN changeType NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN oldMd5Value NVARCHAR(32) NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN newMd5Value NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN changeReason NVARCHAR(500) NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN changedBy NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_SERVICE_CONFIG_HISTORY ALTER COLUMN noteText NVARCHAR(500) NULL;
