-- SQL Server 方言，由 scripts/db/mysql/HUB_METRIC_TEMP_LOG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_METRIC_TEMP_LOG', N'U') IS NULL
CREATE TABLE HUB_METRIC_TEMP_LOG (
  metricTemperatureLogId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  metricServerId NVARCHAR(32) NOT NULL,
  sensorName NVARCHAR(100) NOT NULL,
  temperatureValue DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  highThreshold DECIMAL(6,2) DEFAULT NULL,
  criticalThreshold DECIMAL(6,2) DEFAULT NULL,
  collectTime DATETIME2 NOT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, metricTemperatureLogId),
  INDEX IDX_METRIC_TEMP_SERVER (metricServerId),
  INDEX IDX_METRIC_TEMP_TIME (collectTime),
  INDEX IDX_METRIC_TEMP_SENSOR (sensorName),
  INDEX IDX_METRIC_TEMP_ACTIVE (activeFlag),
  INDEX IDX_METRIC_TEMP_SRV_TIME (metricServerId, collectTime),
  INDEX IDX_METRIC_TEMP_SRV_SENSOR (metricServerId, sensorName),
  INDEX IDX_METRIC_TEMP_TNT_TIME (tenantId, collectTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN sensorName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_TEMP_LOG ALTER COLUMN reserved10 NVARCHAR(500) NULL;
