-- SQL Server 方言，由 scripts/db/mysql/HUB_ALERT_TEMPLATE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_ALERT_TEMPLATE', N'U') IS NULL
CREATE TABLE HUB_ALERT_TEMPLATE (
  -- 主键和租户
  tenantId NVARCHAR(32) NOT NULL,
  templateName NVARCHAR(100) NOT NULL,
  
  -- 模板基本信息
  templateDesc NVARCHAR(500) DEFAULT NULL,
  channelType NVARCHAR(50) DEFAULT NULL,
  
  -- 模板内容
  titleTemplate NVARCHAR(500) DEFAULT NULL,
  contentTemplate NVARCHAR(MAX) DEFAULT NULL,
  displayFormat NVARCHAR(20) NOT NULL DEFAULT N'table',
  templateVariables NVARCHAR(MAX) DEFAULT NULL,
  
  -- 附件配置
  attachmentConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 预留字段
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, templateName),
  INDEX IDX_ALERT_TEMPLATE_TENANT (tenantId),
  INDEX IDX_ALERT_TEMPLATE_CHANNEL (channelType),
  INDEX IDX_ALERT_TEMPLATE_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN templateName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN templateDesc NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN channelType NVARCHAR(50) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN titleTemplate NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN displayFormat NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_TEMPLATE ALTER COLUMN reserved10 NVARCHAR(500) NULL;
