-- SQL Server 方言，由 scripts/db/mysql/HUB_AUTH_USER_ROLE.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
-- =====================================================
-- 用户角色关联表 - 存储用户与角色的关联关系
-- =====================================================
IF OBJECT_ID(N'dbo.HUB_AUTH_USER_ROLE', N'U') IS NULL
CREATE TABLE HUB_AUTH_USER_ROLE (
  -- 主键和租户信息
  userRoleId NVARCHAR(100) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  
  -- 关联信息
  userId NVARCHAR(32) NOT NULL,
  roleId NVARCHAR(32) NOT NULL,
  
  -- 授权控制
  grantedBy NVARCHAR(32) NOT NULL,
  grantedTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  expireTime DATETIME2 DEFAULT NULL,
  primaryRoleFlag NVARCHAR(1) NOT NULL DEFAULT N'N',
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, userRoleId),
  CONSTRAINT IDX_AUTH_USER_ROLE_UNIQUE UNIQUE (tenantId, userId, roleId),
  INDEX IDX_AUTH_USER_ROLE_USER (tenantId, userId),
  INDEX IDX_AUTH_USER_ROLE_ROLE (tenantId, roleId),
  INDEX IDX_AUTH_USER_ROLE_PRIMARY (primaryRoleFlag),
  INDEX IDX_AUTH_USER_ROLE_EXPIRE (expireTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN grantedBy NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN primaryRoleFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_AUTH_USER_ROLE ALTER COLUMN reserved10 NVARCHAR(500) NULL;
