-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_ROUTE_ASSERTION.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_ROUTE_ASSERTION', N'U') IS NULL
CREATE TABLE HUB_GW_ROUTE_ASSERTION (
  tenantId NVARCHAR(32) NOT NULL,
  routeAssertionId NVARCHAR(32) NOT NULL,
  routeConfigId NVARCHAR(32) NOT NULL,
  assertionName NVARCHAR(100) NOT NULL,
  assertionType NVARCHAR(50) NOT NULL,
  assertionOperator NVARCHAR(20) NOT NULL DEFAULT N'EQUAL',
  fieldName NVARCHAR(100) DEFAULT NULL,
  expectedValue NVARCHAR(500) DEFAULT NULL,
  patternValue NVARCHAR(500) DEFAULT NULL,
  caseSensitive NVARCHAR(1) NOT NULL DEFAULT N'Y',
  assertionOrder INT NOT NULL DEFAULT 0,
  isRequired NVARCHAR(1) NOT NULL DEFAULT N'Y',
  assertionDesc NVARCHAR(200) DEFAULT NULL,
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, routeAssertionId),
  INDEX IDX_GW_ASSERT_ROUTE (routeConfigId),
  INDEX IDX_GW_ASSERT_TYPE (assertionType),
  INDEX IDX_GW_ASSERT_ORDER (assertionOrder)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN assertionName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN assertionType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN assertionOperator NVARCHAR(20) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN fieldName NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN expectedValue NVARCHAR(500) NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN patternValue NVARCHAR(500) NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN caseSensitive NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN isRequired NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN assertionDesc NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_ROUTE_ASSERTION ALTER COLUMN noteText NVARCHAR(500) NULL;
