-- SQL Server 方言，由 scripts/db/mysql/HUB_SERVICE_AUTH_TOKEN.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
-- 服务中心 API Token（Bearer 不透明令牌）
IF OBJECT_ID(N'dbo.HUB_SERVICE_AUTH_TOKEN', N'U') IS NULL
CREATE TABLE HUB_SERVICE_AUTH_TOKEN (
    tokenId NVARCHAR(64) NOT NULL,
    tenantId NVARCHAR(32) NOT NULL,
    tokenValue NVARCHAR(256) NOT NULL,
    userId NVARCHAR(64) NOT NULL,
    tokenName NVARCHAR(128) DEFAULT NULL,
    expireTime DATETIME2 DEFAULT NULL,
    statusFlag NCHAR(1) NOT NULL DEFAULT N'Y',
    addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
    addWho NVARCHAR(64) NOT NULL,
    editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
    editWho NVARCHAR(64) NOT NULL,
    oprSeqFlag NVARCHAR(64) NOT NULL,
    currentVersion INT NOT NULL DEFAULT 1,
    activeFlag NCHAR(1) NOT NULL DEFAULT N'Y',
    noteText NVARCHAR(512) DEFAULT NULL,
    extProperty NVARCHAR(MAX),
    PRIMARY KEY (tenantId, tokenId),
    CONSTRAINT UK_SC_AUTH_TOKEN_VALUE UNIQUE (tokenValue),
    INDEX IDX_SC_AUTH_TOKEN_USER (userId)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_SERVICE_AUTH_TOKEN ALTER COLUMN tokenValue NVARCHAR(256) NOT NULL;
ALTER TABLE HUB_SERVICE_AUTH_TOKEN ALTER COLUMN tokenName NVARCHAR(128) NULL;
ALTER TABLE HUB_SERVICE_AUTH_TOKEN ALTER COLUMN statusFlag NCHAR(1) NOT NULL;
ALTER TABLE HUB_SERVICE_AUTH_TOKEN ALTER COLUMN addWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SERVICE_AUTH_TOKEN ALTER COLUMN editWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SERVICE_AUTH_TOKEN ALTER COLUMN oprSeqFlag NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_SERVICE_AUTH_TOKEN ALTER COLUMN activeFlag NCHAR(1) NOT NULL;
ALTER TABLE HUB_SERVICE_AUTH_TOKEN ALTER COLUMN noteText NVARCHAR(512) NULL;
