-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_STATIC_HOST_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_STATIC_HOST_CONFIG', N'U') IS NULL
CREATE TABLE HUB_GW_STATIC_HOST_CONFIG (
  tenantId NVARCHAR(32) NOT NULL,
  staticHostConfigId NVARCHAR(32) NOT NULL,
  routeConfigId NVARCHAR(32) NOT NULL,
  configName NVARCHAR(100) NOT NULL,
  rootDirectory NVARCHAR(500) NOT NULL,
  stripRoutePrefix NVARCHAR(1) NOT NULL DEFAULT N'Y',
  indexFiles NVARCHAR(MAX) DEFAULT NULL,
  rewriteRules NVARCHAR(MAX) DEFAULT NULL,
  spaFallback NVARCHAR(1) NOT NULL DEFAULT N'N',
  cacheControlMaxAge INT NOT NULL DEFAULT 3600,
  allowedExtensions NVARCHAR(MAX) DEFAULT NULL,
  maxFileSizeBytes BIGINT NOT NULL DEFAULT 0,
  followSymlinks NVARCHAR(1) NOT NULL DEFAULT N'N',
  enablePrecompress NVARCHAR(1) NOT NULL DEFAULT N'Y',
  errorPage404 NVARCHAR(200) DEFAULT NULL,
  errorPage403 NVARCHAR(200) DEFAULT NULL,
  configPriority INT NOT NULL DEFAULT 0,
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, staticHostConfigId),
  INDEX IDX_GW_STATIC_ROUTE (routeConfigId),
  INDEX IDX_GW_STATIC_PRIORITY (configPriority),
  INDEX IDX_GW_STATIC_ACTIVE (activeFlag)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN configName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN rootDirectory NVARCHAR(500) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN stripRoutePrefix NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN spaFallback NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN followSymlinks NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN enablePrecompress NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN errorPage404 NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN errorPage403 NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;


-- 已建表环境补列（新库 CREATE 已包含，重复执行会报列已存在，可忽略）
-- ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD rewriteRules TEXT DEFAULT NULL;
-- ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD allowedExtensions TEXT DEFAULT NULL;
-- ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD maxFileSizeBytes BIGINT NOT NULL DEFAULT 0;
-- ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD followSymlinks VARCHAR(1) NOT NULL DEFAULT 'N';
-- ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD enablePrecompress VARCHAR(1) NOT NULL DEFAULT 'Y';
-- ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD errorPage404 VARCHAR(200) DEFAULT NULL;
-- ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD errorPage403 VARCHAR(200) DEFAULT NULL;

-- 历史库升级：建表已执行过的不会再跑 CREATE，只补列。
IF COL_LENGTH(N'dbo.HUB_GW_STATIC_HOST_CONFIG', N'redirectDirectorySlash') IS NULL
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD redirectDirectorySlash NVARCHAR(1) NOT NULL DEFAULT N'N';
IF COL_LENGTH(N'dbo.HUB_GW_STATIC_HOST_CONFIG', N'rootTokenExact') IS NULL
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD rootTokenExact NVARCHAR(1) NOT NULL DEFAULT N'N';
IF COL_LENGTH(N'dbo.HUB_GW_STATIC_HOST_CONFIG', N'fallbackRoots') IS NULL
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD fallbackRoots NVARCHAR(MAX) DEFAULT NULL;
IF COL_LENGTH(N'dbo.HUB_GW_STATIC_HOST_CONFIG', N'cacheControlByExt') IS NULL
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD cacheControlByExt NVARCHAR(MAX) DEFAULT NULL;
IF COL_LENGTH(N'dbo.HUB_GW_STATIC_HOST_CONFIG', N'enableGzip') IS NULL
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD enableGzip NVARCHAR(1) NOT NULL DEFAULT N'N';
IF COL_LENGTH(N'dbo.HUB_GW_STATIC_HOST_CONFIG', N'securityHeaders') IS NULL
ALTER TABLE HUB_GW_STATIC_HOST_CONFIG ADD securityHeaders NVARCHAR(MAX) DEFAULT NULL;
