-- SQL Server 方言，由 scripts/db/mysql/HUB_METRIC_SERVER_INFO.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_METRIC_SERVER_INFO', N'U') IS NULL
CREATE TABLE HUB_METRIC_SERVER_INFO (
  metricServerId NVARCHAR(64) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  hostname NVARCHAR(255) NOT NULL,
  osType NVARCHAR(100) NOT NULL,
  osVersion NVARCHAR(255) NOT NULL,
  kernelVersion NVARCHAR(255) DEFAULT NULL,
  architecture NVARCHAR(100) NOT NULL,
  bootTime DATETIME2 NOT NULL,
  ipAddress NVARCHAR(45) DEFAULT NULL,
  macAddress NVARCHAR(50) DEFAULT NULL,
  serverLocation NVARCHAR(255) DEFAULT NULL,
  serverType NVARCHAR(50) DEFAULT NULL,
  lastUpdateTime DATETIME2 NOT NULL,
  -- 新增网络信息字段
  networkInfo NVARCHAR(MAX) DEFAULT NULL,
  systemInfo NVARCHAR(MAX) DEFAULT NULL,
  hardwareInfo NVARCHAR(MAX) DEFAULT NULL,
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(64) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(64) NOT NULL,
  oprSeqFlag NVARCHAR(64) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(MAX) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, metricServerId),
  CONSTRAINT IDX_METRIC_SERVER_HOST UNIQUE (hostname),
  INDEX IDX_METRIC_SERVER_OS (osType),
  INDEX IDX_METRIC_SERVER_IP (ipAddress),
  INDEX IDX_METRIC_SERVER_TYPE (serverType),
  INDEX IDX_METRIC_SERVER_ACTIVE (activeFlag),
  INDEX IDX_METRIC_SERVER_UPDATE (lastUpdateTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN hostname NVARCHAR(255) NOT NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN osType NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN osVersion NVARCHAR(255) NOT NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN kernelVersion NVARCHAR(255) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN architecture NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN ipAddress NVARCHAR(45) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN macAddress NVARCHAR(50) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN serverLocation NVARCHAR(255) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN serverType NVARCHAR(50) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN addWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN editWho NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN oprSeqFlag NVARCHAR(64) NOT NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_METRIC_SERVER_INFO ALTER COLUMN reserved10 NVARCHAR(500) NULL;


-- 兼容历史项目：删除hostname唯一索引
IF EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'IDX_METRIC_SERVER_HOST' AND parent_object_id = OBJECT_ID(N'dbo.HUB_METRIC_SERVER_INFO'))
ALTER TABLE HUB_METRIC_SERVER_INFO DROP CONSTRAINT IDX_METRIC_SERVER_HOST;
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IDX_METRIC_SERVER_HOST' AND object_id = OBJECT_ID(N'dbo.HUB_METRIC_SERVER_INFO') AND is_primary_key = 0 AND is_unique_constraint = 0)
DROP INDEX IDX_METRIC_SERVER_HOST ON HUB_METRIC_SERVER_INFO;
