-- SQL Server 方言，由 scripts/db/mysql/HUB_TIMER_EXECUTION_LOG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_TIMER_EXECUTION_LOG', N'U') IS NULL
CREATE TABLE HUB_TIMER_EXECUTION_LOG (
  -- 主键信息
  executionId NVARCHAR(32) NOT NULL,
  tenantId NVARCHAR(32) NOT NULL,
  taskId NVARCHAR(32) NOT NULL,
  
  -- 任务信息（冗余）
  taskName NVARCHAR(200) DEFAULT NULL,
  schedulerId NVARCHAR(32) DEFAULT NULL,
  
  -- 执行信息
  executionStartTime DATETIME2 NOT NULL,
  executionEndTime DATETIME2 DEFAULT NULL,
  executionDurationMs BIGINT DEFAULT NULL,
  executionStatus INT NOT NULL,
  resultSuccess NVARCHAR(1) NOT NULL DEFAULT N'N',
  
  -- 错误信息
  errorMessage NVARCHAR(MAX) DEFAULT NULL,
  errorStackTrace NVARCHAR(MAX) DEFAULT NULL,
  
  -- 重试信息
  retryCount INT NOT NULL DEFAULT 0,
  maxRetryCount INT NOT NULL DEFAULT 0,
  
  -- 参数和结果
  executionParams NVARCHAR(MAX) DEFAULT NULL,
  executionResult NVARCHAR(MAX) DEFAULT NULL,
  
  -- 执行环境
  executorServerName NVARCHAR(100) DEFAULT NULL,
  executorServerIp NVARCHAR(50) DEFAULT NULL,
  
  -- 日志信息
  logLevel NVARCHAR(10) DEFAULT NULL,
  logMessage NVARCHAR(MAX) DEFAULT NULL,
  logTimestamp DATETIME2 DEFAULT NULL,
  
  -- 执行上下文
  executionPhase NVARCHAR(50) DEFAULT NULL,
  threadName NVARCHAR(100) DEFAULT NULL,
  className NVARCHAR(200) DEFAULT NULL,
  methodName NVARCHAR(100) DEFAULT NULL,
  
  -- 异常信息
  exceptionClass NVARCHAR(200) DEFAULT NULL,
  exceptionMessage NVARCHAR(MAX) DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  PRIMARY KEY (tenantId, executionId),
  INDEX IDX_TIMER_LOG_TASK (taskId),
  INDEX IDX_TIMER_LOG_NAME (taskName),
  INDEX IDX_TIMER_LOG_SCHED (schedulerId),
  INDEX IDX_TIMER_LOG_START (executionStartTime),
  INDEX IDX_TIMER_LOG_STATUS (executionStatus),
  INDEX IDX_TIMER_LOG_SUCCESS (resultSuccess),
  INDEX IDX_TIMER_LOG_LEVEL (logLevel),
  INDEX IDX_TIMER_LOG_TIME (logTimestamp),
  INDEX IDX_TIMER_LOG_CLEANUP (tenantId, addTime)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN taskName NVARCHAR(200) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN resultSuccess NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN executorServerName NVARCHAR(100) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN executorServerIp NVARCHAR(50) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN logLevel NVARCHAR(10) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN executionPhase NVARCHAR(50) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN threadName NVARCHAR(100) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN className NVARCHAR(200) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN methodName NVARCHAR(100) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN exceptionClass NVARCHAR(200) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_TIMER_EXECUTION_LOG ALTER COLUMN reserved10 NVARCHAR(500) NULL;
