-- SQL Server 方言，由 scripts/db/mysql/HUB_ALERT_CONFIG.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_ALERT_CONFIG', N'U') IS NULL
CREATE TABLE HUB_ALERT_CONFIG (
  -- 主键和租户
  tenantId NVARCHAR(32) NOT NULL,
  channelName NVARCHAR(100) NOT NULL,
  
  -- 渠道基本信息
  channelType NVARCHAR(50) NOT NULL,
  channelDesc NVARCHAR(500) DEFAULT NULL,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  defaultFlag NVARCHAR(1) NOT NULL DEFAULT N'N',
  priorityLevel INT NOT NULL DEFAULT 10,
  defaultTemplateName NVARCHAR(100) DEFAULT NULL,
  
  -- 服务器配置（JSON格式）
  serverConfig NVARCHAR(MAX) DEFAULT NULL,
  sendConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 消息格式配置
  messageContentFormat NVARCHAR(20) DEFAULT NULL,
  
  -- 重试和超时配置
  timeoutSeconds INT NOT NULL DEFAULT 30,
  retryCount INT NOT NULL DEFAULT 3,
  retryIntervalSecs INT NOT NULL DEFAULT 5,
  asyncSendFlag NVARCHAR(1) NOT NULL DEFAULT N'N',
  
  -- 统计信息
  totalSentCount BIGINT NOT NULL DEFAULT 0,
  successCount BIGINT NOT NULL DEFAULT 0,
  failureCount BIGINT NOT NULL DEFAULT 0,
  lastSendTime DATETIME2 DEFAULT NULL,
  lastSuccessTime DATETIME2 DEFAULT NULL,
  lastFailureTime DATETIME2 DEFAULT NULL,
  lastErrorMessage NVARCHAR(1000) DEFAULT NULL,
  
  -- 通用字段
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  noteText NVARCHAR(500) DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  
  -- 预留字段
  reserved1 NVARCHAR(500) DEFAULT NULL,
  reserved2 NVARCHAR(500) DEFAULT NULL,
  reserved3 NVARCHAR(500) DEFAULT NULL,
  reserved4 NVARCHAR(500) DEFAULT NULL,
  reserved5 NVARCHAR(500) DEFAULT NULL,
  reserved6 NVARCHAR(500) DEFAULT NULL,
  reserved7 NVARCHAR(500) DEFAULT NULL,
  reserved8 NVARCHAR(500) DEFAULT NULL,
  reserved9 NVARCHAR(500) DEFAULT NULL,
  reserved10 NVARCHAR(500) DEFAULT NULL,
  
  -- 主键和索引
  PRIMARY KEY (tenantId, channelName),
  INDEX IDX_ALERT_CONFIG_TENANT (tenantId),
  INDEX IDX_ALERT_CONFIG_TYPE (channelType),
  INDEX IDX_ALERT_CONFIG_ACTIVE (activeFlag),
  INDEX IDX_ALERT_CONFIG_DEFAULT (defaultFlag),
  INDEX IDX_ALERT_CONFIG_PRIORITY (priorityLevel),
  INDEX IDX_ALERT_CONFIG_TEMPLATE (defaultTemplateName)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN channelName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN channelType NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN channelDesc NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN defaultFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN defaultTemplateName NVARCHAR(100) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN messageContentFormat NVARCHAR(20) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN asyncSendFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN lastErrorMessage NVARCHAR(1000) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN noteText NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved1 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved2 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved3 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved4 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved5 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved6 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved7 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved8 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved9 NVARCHAR(500) NULL;
ALTER TABLE HUB_ALERT_CONFIG ALTER COLUMN reserved10 NVARCHAR(500) NULL;
