-- SQL Server 方言，由 scripts/db/mysql/HUB_GW_SERVICE_DEFINITION.sql 转换。程序初始化会执行本目录除 init.sql 外的全部 .sql。
IF OBJECT_ID(N'dbo.HUB_GW_SERVICE_DEFINITION', N'U') IS NULL
CREATE TABLE HUB_GW_SERVICE_DEFINITION (
  tenantId NVARCHAR(32) NOT NULL,
  serviceDefinitionId VARCHAR(32) NOT NULL,
  serviceName NVARCHAR(100) NOT NULL,
  serviceDesc NVARCHAR(200) DEFAULT NULL,
  serviceType INT NOT NULL DEFAULT 0,
  
  -- 代理配置关联字段
  proxyConfigId NVARCHAR(32) NOT NULL,
  
  -- 根据ServiceConfig.Strategy字段设计负载均衡策略
  loadBalanceStrategy NVARCHAR(50) NOT NULL DEFAULT N'round-robin',
  
  -- 服务发现配置
  discoveryType NVARCHAR(50) DEFAULT NULL,
  discoveryConfig NVARCHAR(MAX) DEFAULT NULL,
  
  -- 根据LoadBalancerConfig结构设计负载均衡配置
  sessionAffinity NVARCHAR(1) NOT NULL DEFAULT N'N',
  stickySession NVARCHAR(1) NOT NULL DEFAULT N'N',
  maxRetries INT NOT NULL DEFAULT 3,
  retryTimeoutMs INT NOT NULL DEFAULT 5000,
  enableCircuitBreaker NVARCHAR(1) NOT NULL DEFAULT N'N',
  
  -- 根据HealthConfig结构设计健康检查配置
  healthCheckEnabled NVARCHAR(1) NOT NULL DEFAULT N'Y',
  healthCheckPath NVARCHAR(200) DEFAULT N'/health',
  healthCheckMethod NVARCHAR(10) DEFAULT N'GET',
  healthCheckIntervalSeconds INT DEFAULT 30,
  healthCheckTimeoutMs INT DEFAULT 5000,
  healthyThreshold INT DEFAULT 2,
  unhealthyThreshold INT DEFAULT 3,
  expectedStatusCodes NVARCHAR(200) DEFAULT N'200',
  healthCheckHeaders NVARCHAR(MAX) DEFAULT NULL,
  
  -- 负载均衡器配置(JSON格式存储完整的LoadBalancerConfig)
  loadBalancerConfig NVARCHAR(MAX) DEFAULT NULL,
  serviceMetadata NVARCHAR(MAX) DEFAULT NULL,
  
  reserved1 NVARCHAR(100) DEFAULT NULL,
  reserved2 NVARCHAR(100) DEFAULT NULL,
  reserved3 INT DEFAULT NULL,
  reserved4 INT DEFAULT NULL,
  reserved5 DATETIME2 DEFAULT NULL,
  extProperty NVARCHAR(MAX) DEFAULT NULL,
  addTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  addWho NVARCHAR(32) NOT NULL,
  editTime DATETIME2 NOT NULL DEFAULT GETDATE(),
  editWho NVARCHAR(32) NOT NULL,
  oprSeqFlag NVARCHAR(32) NOT NULL,
  currentVersion INT NOT NULL DEFAULT 1,
  activeFlag NVARCHAR(1) NOT NULL DEFAULT N'Y',
  noteText NVARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (tenantId, serviceDefinitionId),
  INDEX IDX_GW_SVC_NAME (serviceName),
  INDEX IDX_GW_SVC_TYPE (serviceType),
  INDEX IDX_GW_SVC_STRATEGY (loadBalanceStrategy),
  INDEX IDX_GW_SVC_HEALTH (healthCheckEnabled),
  INDEX IDX_GW_SVC_PROXY (proxyConfigId)
);
-- 已有库：把原 VARCHAR 列升为 NVARCHAR，便于后续 N'...' 写入中文。
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN serviceName NVARCHAR(100) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN serviceDesc NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN loadBalanceStrategy NVARCHAR(50) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN discoveryType NVARCHAR(50) NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN sessionAffinity NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN stickySession NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN enableCircuitBreaker NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN healthCheckEnabled NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN healthCheckPath NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN healthCheckMethod NVARCHAR(10) NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN expectedStatusCodes NVARCHAR(200) NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN reserved1 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN reserved2 NVARCHAR(100) NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN addWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN editWho NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN oprSeqFlag NVARCHAR(32) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN activeFlag NVARCHAR(1) NOT NULL;
ALTER TABLE HUB_GW_SERVICE_DEFINITION ALTER COLUMN noteText NVARCHAR(500) NULL;
